### ISSUE TITLE
Error: Missing helper: "New" jsreport handlebars

### ISSUE THREAD

**Issue by mai1x9** [jsreport/jsreport#1001]
Error creating pdf when html code is passed to convert to pdf.
```
Error: Missing helper: "New"
    at Object.<anonymous> (/home/lns_vm05/Desktop/Compliance_v0.1/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
    at Object.wrapper (/home/lns_vm05/Desktop/Compliance_v0.1/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at Object.main (eval at compile (/home/lns_vm05/Desktop/Compliance_v0.1/node_modules/@jsreport/jsreport-handlebars/lib/handlebarsEngine.js:35:30), <anonymous>:12:96)
    at main (/home/lns_vm05/Desktop/Compliance_v0.1/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at ret (/home/lns_vm05/Desktop/Compliance_v0.1/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at Object.execute (/home/lns_vm05/Desktop/Compliance_v0.1/node_modules/@jsreport/jsreport-handlebars/lib/handlebarsEngine.js:80:14)
    at Object.execute (/home/lns_vm05/Desktop/Compliance_v0.1/node_modules/@jsreport/jsreport-handlebars/lib/worker.js:27:43)
    at executionFn (/home/lns_vm05/Desktop/Compliance_v0.1/node_modules/@jsreport/jsreport-core/lib/worker/render/executeEngine.js:213:40)
    at VM2 Wrapper.apply (/home/lns_vm05/Desktop/Compliance_v0.1/node_modules/vm2/lib/bridge.js:485:11)
    at sandbox.js:13:18 {
  description: undefined,
  fileName: undefined,
  lineNumber: undefined,
  endLineNumber: undefined,
  number: undefined,
  statusCode: 400,
  weak: true,
  property: 'helpers',
  logged: true,
  previousOperationId: 'd348h12xtzijg7j'
```

The html code seems to be fine with no errors, but still jsreport has thrown error, which is something related to handlebars.

**Comment by pofider** [comment]
You probably have something like `{{New}}` in your html.
If you don't want handlebars to be evaluated, use `engine: none`.
