### ISSUE TITLE
EMFile Error winston logging js-report

### ISSUE THREAD

**Issue by mai1x9** [jsreport/jsreport#1018]
Looks like jsreport core uses winston, and below error occurred, while load testing the server. **Does the library seem to have a bug of leaking file descriptors ?**

```
ode:internal/process/per_thread:169
    _memoryUsage(memValues);
    ^

Error: EMFILE: too many open files, uv_resident_set_memory
    at process.memoryUsage (node:internal/process/per_thread:169:5)
    at ExceptionHandler.getProcessInfo (/home/lns_vm05/Desktop/traqez_admin_beta_8700/node_modules/@jsreport/jsreport-core/node_modules/winston/lib/winston/exception-handler.js:111:28)
    at ExceptionHandler.getAllInfo (/home/lns_vm05/Desktop/traqez_admin_beta_8700/node_modules/@jsreport/jsreport-core/node_modules/winston/lib/winston/exception-handler.js:92:21)
    at ExceptionHandler._uncaughtException (/home/lns_vm05/Desktop/traqez_admin_beta_8700/node_modules/@jsreport/jsreport-core/node_modules/winston/lib/winston/exception-handler.js:167:23)
    at process.emit (node:events:527:28)
    at processEmit [as emit] (/home/lns_vm05/Desktop/traqez_admin_beta_8700/node_modules/signal-exit/index.js:161:32)
    at process._fatalException (node:internal/process/execution:167:25)
    at processPromiseRejections (node:internal/process/promises:279:13)
    at processTicksAndRejections (node:internal/process/task_queues:97:32) {
  errno: -24,
  code: 'EMFILE',
  syscall: 'uv_resident_set_memory'
}
```

**Comment by pofider** [comment]
Are you able to share the load test so we can replicate the issue?

**Comment by pofider** [comment]
Closing because we are missing additional information.
However, feel free to submit more info later. 
I will happily check it out.
