### ISSUE TITLE
DOMPoint and DOMMatrix are undefined

### ISSUE THREAD

**Issue by kai-dorschner-twinsity** [jsreport/jsreport#1020]
Hey guys,
as the title already describes I'm trying to do some matrix transformations inside of a jsreport global-helper.js but as it seems both DOMPoint and DOMMatrix (with their respective -ReadOnly counterparts) are undefined.

I need those to transform SVG shapes  / calculate their precise bounding boxes.

As far as I understood jsreport uses chrome-pdf, which I thought would use its entire JavaScript VM. Unfortunately I get the following error when trying to run the template:
![image](https://user-images.githubusercontent.com/92744645/211837879-cc18a241-6ccc-4d11-9862-90f1a97a86d1.png)

At a first glance it looks like I mistyped DOMMatrix, but I double-checked and I didn't.

Here's the codepart from the helper function:

```js
function createViewBox(shape) {
    if (shape.Type === 'Rectangle' || shape.Type === null) {
        const identityMatrix = new DOMMatrix();
        
        const origin = new DOMPoint(shape.X + (shape.Width / 2), shape.Y + (shape.Height / 2));
        const rotationMatrix = identityMatrix.translate(origin.x, origin.y).rotate(shape.Rotation).translate(-origin.x, -origin.y);

        const translate = new DOMPoint(shape.X, shape.Y).matrixTransform(rotationMatrix);
        const dimensions = new DOMPoint(shape.Width, shape.Height).matrixTransform(rotationMatrix);
        return [
            translate.x - viewBoxMargin,
            translate.y - viewBoxMargin,
            dimensions.x + viewBoxMargin * 2,
            dimensions.y + viewBoxMargin * 2,
        ].join(' ');
    }
  
    // ...
}
```

Here's the full error log:

```
(global-helpers.js line 117:32)

  115 | function createViewBox(shape) {
  116 |     if (shape.Type === 'Rectangle' || shape.Type === null) {
> 117 |         const identityMatrix = new DOMMatrix();
      |                                ^
  118 |         
  119 |         const origin = new DOMPoint(shape.X + (shape.Width / 2), shape.Y + (shape.Height / 2));
  120 |         const rotationMatrix = identityMatrix.translate(origin.x, origin.y).rotate(shape.Rotation).translate(-origin.x, -origin.y);

(system-helpers.js line 126:12)

  124 |     }
  125 |
> 126 |     return await jsreport.templatingEngines.evaluate({
      |            ^
  127 |       engine: entity.engine,
  128 |       content: entity.content,
  129 |       helpers: entity.helpers,


ReferenceError: DOMMatrix is not defined
    at Object.createViewBox (global-helpers.js:117:32)
    at Object.<anonymous> (C:\jsreport\npm-test\jsreport\node_modules\@jsreport\jsreport-core\lib\worker\render\executeEngine.js:344:23)
    at Object.<anonymous> (C:\jsreport\npm-test\jsreport\node_modules\@jsreport\jsreport-core\lib\worker\render\executeEngine.js:323:27)
    at Object.wrapper (C:\jsreport\npm-test\jsreport\node_modules\handlebars\dist\cjs\handlebars\internal\wrapHelper.js:15:19)
    at 4 (eval at compile (C:\jsreport\npm-test\jsreport\packages\jsreport-handlebars\lib\handlebarsEngine.js:35:30), <anonymous>:54:116)
    at prog (C:\jsreport\npm-test\jsreport\node_modules\handlebars\dist\cjs\handlebars\runtime.js:268:12)
    at execIteration (C:\jsreport\npm-test\jsreport\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:51:19)
    at Object.<anonymous> (C:\jsreport\npm-test\jsreport\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:61:13)
    at Object.wrapper (C:\jsreport\npm-test\jsreport\node_modules\handlebars\dist\cjs\handlebars\internal\wrapHelper.js:15:19)
    at 1 (eval at compile (C:\jsreport\npm-test\jsreport\packages\jsreport-handlebars\lib\handlebarsEngine.js:35:30), <anonymous>:28:49)
```

I'm using jsreport v3.10.0

**Comment by kai-dorschner-twinsity** [comment]
which means I cannot compute the viewbox at handlebars evaluation time, or I'll have to polyfill that matrix transform stuff.

**Comment by kai-dorschner-twinsity** [comment]
For anyone coming here from google, I solved it by making use of jsreport's ability to [load and install npm modules](https://jsreport.net/learn/npm#use-npm-module-in-helper-or-jsreport-script).

I added the following scripts to the top of the global-helpers.js

```js

const jsreport = require('jsreport-proxy');

const matrix = await jsreport.npm.require('transformation-matrix@2.14.0')
```

and used the imported library later like this:

```js
function createViewBox(shape) {
    if (shape.Type === 'Rectangle' || shape.Type === null) {
        const origin = {x: shape.X + (shape.Width / 2), y: shape.Y + (shape.Height / 2)};
        const rotationMatrix = matrix.compose(
            matrix.translate(origin.x, origin.y),
            matrix.rotate(shape.Rotation),
            matrix.translate(-origin.x, -origin.y)
        );

        const translate = matrix.applyToPoint(rotationMatrix, {x: shape.X, y: shape.Y});
        const dimensions = matrix.applyToPoint(rotationMatrix, {x: shape.Width, y: shape.Height});
        
        return [
            translate.x - viewBoxMargin,
            translate.y - viewBoxMargin,
            dimensions.x + viewBoxMargin * 2,
            dimensions.y + viewBoxMargin * 2,
        ].join(' ');
    }

    // ...
}
