### ISSUE TITLE
Localization not working : JSReport

### ISSUE THREAD

**Issue by abhijeeta94** [jsreport/jsreport#1035]
Hi Team,

Right now I am working on java and jsreport to create a pdf report. We are using java utility to render report. Currently I am working on localization support to pdf report for that I have created different json file for different language and trying to set language using java code :
```java
           JsReportService reportingService = new JsReportServiceImpl("http://localhost:5488/");
            RenderRequest renderRequest = new RenderRequest(getTemplateInfo(), dataBindingToTemplate(vinNumber, listOfEcu));
            Options options  =  new Options();
            options.setLanguage("en");
            renderRequest.setOptions(options);
            Report report = reportingService.renderAsync(renderRequest).get();
```
and In the JSReport template I am using like(already added those files as asset)
```
{{localize "dtccode" "localization"}}
```

localization is a folder and it contains multiple different language json file(like en.json, de.json etc). and in template I keep localization setup as default language. 
When I tried to generate report I am getting error in java:
```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-2.7.8.jar:2.7.8]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) ~[spring-boot-2.7.8.jar:2.7.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.7.8.jar:2.7.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.8.jar:2.7.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.8.jar:2.7.8]
	at com.kpit.JsReportDemoApplication.main(JsReportDemoApplication.java:21) ~[classes/:na]
Caused by: java.util.concurrent.ExecutionException: net.jsreport.java.JsReportException: Invalid status code (400) !!!
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999) ~[na:na]
	at com.kpit.service.ReportService.jsreportService(ReportService.java:81) ~[classes/:na]
	at com.kpit.JsReportDemoApplication.run(JsReportDemoApplication.java:29) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768) ~[spring-boot-2.7.8.jar:2.7.8]
	... 5 common frames omitted
Caused by: net.jsreport.java.JsReportException: Invalid status code (400) !!!
	at net.jsreport.java.service.JsReportServiceImpl$3.onResponse(JsReportServiceImpl.java:182) ~[jsreport-javaclient-1.0.11.jar:na]
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161) ~[retrofit-2.9.0.jar:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.9.3.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```
And error from JSReport side:
```
2023-02-27T09:51:23.939Z - warn: Error when processing render request 17
(because) error when evaluating engine handlebars for template /machine_report_ecu/machine_report
(because) "localize" helper call failed
(because) can't call localize without specified language

(system-helpers.js line 162:32)

  160 |     folder = null
  161 |   }
> 162 |   return jsreport.localization.localize(key, folder)
      |                                ^
  163 | }
  164 |
  165 | /* eslint-disable no-unused-vars */


Error: Can't call localize without specified language
    at Object.localize (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-localization\lib\worker.js:48:17)
    at Object.localize (system-helpers.js:162:32)
    at Object.<anonymous> (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\render\executeEngine.js:344:23)
    at Object.<anonymous> (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\render\executeEngine.js:323:27)
    at Object.wrapper (D:\JSREPORT\jsreportapp\node_modules\handlebars\dist\cjs\handlebars\internal\wrapHelper.js:15:19)
    at Object.main (eval at compile (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-handlebars\lib\handlebarsEngine.js:35:30), <anonymous>:102:106)
    at main (D:\JSREPORT\jsreportapp\node_modules\handlebars\dist\cjs\handlebars\runtime.js:208:32)
    at ret (D:\JSREPORT\jsreportapp\node_modules\handlebars\dist\cjs\handlebars\runtime.js:212:12)
    at Object.execute (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-handlebars\lib\handlebarsEngine.js:80:14)
    at Object.execute (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-handlebars\lib\worker.js:27:43)
wrapped by:
Error: "localize" helper call failed
(because) can't call localize without specified language
    at module.exports (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\shared\createError.js:10:13)
    at WorkerReporter.createError (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\shared\reporter.js:49:12)
    at getEnhancedHelperError (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\render\executeEngine.js:340:54)
    at D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\render\executeEngine.js:354:15
    at async D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\render\executeEngine.js:222:40
    at async Promise.all (index 0)
    at async executionFn (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\render\executeEngine.js:221:9)
    at async run (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\sandbox\createSandbox.js:184:24)
    at async WorkerReporter._runInSandbox (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\sandbox\runInSandbox.js:180:14)
    at async executeEngine (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\render\executeEngine.js:263:14)
wrapped by:
Error: Error when evaluating engine handlebars for template /machine_report_ecu/machine_report
(because) "localize" helper call failed
(because) can't call localize without specified language
    at module.exports (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\shared\createError.js:10:13)
    at WorkerReporter.createError (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\shared\reporter.js:49:12)
    at executeEngine (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\render\executeEngine.js:286:33)
    at async engine.engine (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\render\executeEngine.js:115:14)
    at async invokeRender (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\render\render.js:62:23)
    at async WorkerReporter._render (D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\render\render.js:147:7)
    at async D:\JSREPORT\jsreportapp\node_modules\@jsreport\jsreport-core\lib\worker\reporter.js:179:19
    at async Domain.<anonymous> (D:\JSREPORT\jsreportapp\node_modules\@jsreport\advanced-workers\lib\workerHandler.js:141:19) rootId=953j4of786jze2v, id=953j4of786jze2v
2023-02-27T09:51:23.946Z - warn: Rendering request 17 finished with error in 46 ms rootId=953j4of786jze2v, id=953j4of786jze2v
2023-02-27T09:51:23.949Z - warn: Error during processing request at http://localhost:5488/api/report
```
Attaching setup screenshot as well:
![image](https://user-images.githubusercontent.com/126459882/221532193-e7f93df4-885b-41f1-82fc-0dfa54a419b6.png)

Can you please help me to fix this issue.

**Comment by pofider** [comment]
Thanks, I've fixed the problem in master, but it will take some time until we release jsreport update.

However, there will be a workaround ready after the java client will be released shortly. I keep you updated.

**Comment by pofider** [comment]
If you update now java client, you should be able to do the following:

```java
JsReportService reportingService = new JsReportServiceImpl("http://localhost:5488/");
RenderRequest renderRequest = new RenderRequest(getTemplateInfo(), dataBindingToTemplate(vinNumber, listOfEcu));
Options options  =  new Options();
LocalizationOptions lo = new LocalizationOptions();
lo.setLanguage("en");
options.setLocalization(lo);
renderRequest.setOptions(options);
```
This should work for you now, the next release of jsreport 3.11.0 should fix also your previous code.

**Comment by abhijeeta94** [comment]
Thanks for the update
