### ISSUE TITLE
update webpack for build with node 18 

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#1043]
Current webpack throws with node 18 the following

```
C:\work\a x\jsreport-extension-starter-kit>npm run build

> custom-extension@0.0.0 build
> jsreport-studio-build

 10% building 0/1 modules 1 active ...xtension-starter-kit\studio\main_dev.jsC:\work\a x\jsreport-extension-starter-kit\node_modules\loader-runner\lib\LoaderRunner.js:133
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\work\a x\jsreport-extension-starter-kit\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\work\a x\jsreport-extension-starter-kit\node_modules\webpack\lib\NormalModule.js:402:16)
    at handleParseError (C:\work\a x\jsreport-extension-starter-kit\node_modules\webpack\lib\NormalModule.js:450:10)
    at C:\work\a x\jsreport-extension-starter-kit\node_modules\webpack\lib\NormalModule.js:482:5
    at C:\work\a x\jsreport-extension-starter-kit\node_modules\webpack\lib\NormalModule.js:343:12
    at C:\work\a x\jsreport-extension-starter-kit\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\work\a x\jsreport-extension-starter-kit\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\work\a x\jsreport-extension-starter-kit\node_modules\loader-runner\lib\LoaderRunner.js:221:10) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0
```

**Comment by pofider** [comment]
Seems like we fixed this with node flag. The webpack update can come later...
