### ISSUE TITLE
Getting Request Timeout Issue With JSReport

### ISSUE THREAD

**Issue by abhijeeta94** [jsreport/jsreport#1071]
Hi Team,

I am getting closed network exception when I tried to generate report using java client.

Error:
2023-06-21T09:38:55.867Z - info: Rendering template { name: machine_report, recipe: chrome-pdf, engine: handlebars, preview: false } rootId=k9fl7e247apnrcx, id=k9fl7e247apnrcx
2023-06-21T09:39:05.798Z - warn: Report render failed
(because) report cancelled by the client or closed network
Error: Report cancelled by the client or closed network
    at Object.close (C:\snapshot\jsreport\packages\advanced-workers\lib\threadWorker.js:156:21)
    at Object.release (C:\snapshot\jsreport\packages\advanced-workers\lib\pool.js:50:22)
    at EventEmitter.<anonymous> (C:\snapshot\jsreport\packages\jsreport-core\lib\main\reporter.js:404:18)
    at Object.onceWrapper (node:events:509:28)
    at EventEmitter.emit (node:events:390:28)
    at Socket.<anonymous> (C:\snapshot\jsreport\packages\jsreport-express\lib\routes.js:67:20)
    at Object.onceWrapper (node:events:510:26)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12) rootId=k9fl7e247apnrcx, id=k9fl7e247apnrcx
2023-06-21T09:39:05.802Z - warn: Error during processing request at http://localhost:5488/api/report, details: Report cancelled by the client or closed network, stack: Error: Report cancelled by the client or closed network
    at Object.close (C:\snapshot\jsreport\packages\advanced-workers\lib\threadWorker.js:156:21)
    at Object.release (C:\snapshot\jsreport\packages\advanced-workers\lib\pool.js:50:22)
    at EventEmitter.<anonymous> (C:\snapshot\jsreport\packages\jsreport-core\lib\main\reporter.js:404:18)
    at Object.onceWrapper (node:events:509:28)
    at EventEmitter.emit (node:events:390:28)
    at Socket.<anonymous> (C:\snapshot\jsreport\packages\jsreport-express\lib\routes.js:67:20)
    at Object.onceWrapper (node:events:510:26)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12)

Configuration : 
```js
{
  "httpPort": 5488,
  "store": {
    "provider": "fs"
  },
  "blobStorage": {
    "provider": "fs"
  },
  "logger": {
    "file": {
      "transport": "file",
      "level": "info",
      "filename": "logs/reporter.log"
    },
    "error": {
      "transport": "file",
      "level": "error",
      "filename": "logs/error.log"
    }
  },
  "trustUserCode": false,
  "reportTimeout": 2000000,
  "workers": {
    "numberOfWorkers": 3
  },
  "extensions": {
    "authentication": {
      "cookieSession": {},
      "admin": {
        "username": "admin",
        "password": "password"
      },
      "enabled": false
    },
	"studio": {
      "enabled": false
    },
	"express": {
	"enabled": true,
	"inputRequestLimit": "200mb"
	},
	"scripts": {
		"timeout": 2000000
	},
	"chrome-pdf": {
		"timeout": 2000000
		}
	},
	"templatingEngines": {
		"timeout": 2000000
	},
	"chrome": {
		"timeout": 2000000
	}
}
```

The way I am accessing the Report using java client:
```js
private static final int TIMEOUT = 2000000;
//SERVER_URL = http://localhost:5488
public Collection<ReportTemplate> generateReport(ReportData reportData) {
        String reportFilePath = null;
        try {
            LocalizationOptions localization = new LocalizationOptions();
            localization.setLanguage(this.languageSupplier.get().getLanguage());
            ReportOptions options = new ReportOptions();
            options.setLocalization(localization);
            options.setTimeout(TIMEOUT);
            RenderRequest renderRequest = new RenderRequest(getTemplateInfo(), dataBindingToTemplate(reportData));
            renderRequest.setOptions(options);
            // Initialize JSReport Engine
            JsReportService reportingService = new JsReportServiceImpl(env.getProperty(SERVER_URL), new ServiceTimeout().setCallTimeout(Duration.ofMillis(TIMEOUT)));
            Report report = reportingService.renderAsync(renderRequest).get();
            reportFilePath = createOutputReport(report.getContent().readAllBytes());
        } catch (InterruptedException | ExecutionException | IOException e) {
            LOGGER.error("Report Not Created. Exception while creating report. vinNumber: {}, {}", reportData.getDiagSystemEntity().getVin(), e.getMessage());
            return List.of(new ReportTemplate(ReportGenerationStatus.JSREPORT_ERROR, null));
        }
        return List.of(new ReportTemplate(ReportGenerationStatus.SUCCESS, reportFilePath));
    }

private Template getTemplateInfo() {
        // Provide Template info
        Template template = new Template(env.getProperty(REPORT_NAME));
        template.setEngine(Engine.HANDLEBARS);
        template.setRecipe(Recipe.CHROME_PDF);
        return template;

    }
```
Can you guys please help me into this to resolve the issue.

contact - abhijeet.avaghade@kpit.com

Thanks,
Abhijeet

**Comment by abhijeeta94** [comment]
Hi @Everyone, Can you guys please help me into this

**Comment by pofider** [comment]
What jsreport version do you use?
The 3.11.2 includes the particular fix to this.

**Comment by abhijeeta94** [comment]
Hi @pofider ,

We are using 3.12.0.
The configuration we are using I have already attached above. Do we need to add any configuration?

**Comment by pofider** [comment]
The error is the client-side timeout which closes the socket and causes the server to disconnect and log the mentioned message.

Please try to configure the client like this
```
ServiceTimeout timeout = new ServiceTimeout();
timeout.setReadTimeout(Duration.of(0, ChronoUnit.MILLIS));
JsReportService reportingService = new JsReportServiceImpl("http://localhost:5488", timeout);
```

**Comment by abhijeeta94** [comment]
Hi @pofider , Thank you for the update Issue is resolved.
