### ISSUE TITLE
[BUG] jsreport_ProfileType.timeout does not exist

### ISSUE THREAD

**Issue by mteichtahl** [jsreport/jsreport#1080]
We are seeing the error below

```
Profile cleanup failed column jsreport_ProfileType.timeout does not exist length=126, name=error, severity=ERROR, code=42703, detail=undefined, hint=undefined, position=38, internalPosition=undefined, internalQuery=undefined, where=undefined, schema=undefined, table=undefined, column=undefined, dataType=undefined, constraint=undefined, file=parse_relation.c, line=3606, routine=errorMissingColumn, stack=error: column jsreport_ProfileType.timeout does not exist
```

We have not updated, changed or upgraded and are running `` jsreport (version: 3.11.2, configuration file: jsreport.config.json, nodejs: 16.19.1)```

Im hoping for some direction/assistance to help us resolve this issue

Further logs below

```


  | 2023-07-31T10:58:54.740+10:00 | 2023-07-31T00:58:54.740Z - [33mwarn[39m: Profile cleanup failed column jsreport_ProfileType.timeout does not exist length=126, name=error, severity=ERROR, code=42703, detail=undefined, hint=undefined, position=38, internalPosition=undefined, internalQuery=undefined, where=undefined, schema=undefined, table=undefined, column=undefined, dataType=undefined, constraint=undefined, file=parse_relation.c, line=3606, routine=errorMissingColumn, stack=error: column jsreport_ProfileType.timeout does not exist
-- | -- | --
  | 2023-07-31T10:58:54.740+10:00 | at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
  | 2023-07-31T10:58:54.740+10:00 | at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
  | 2023-07-31T10:58:54.740+10:00 | at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
  | 2023-07-31T10:58:54.740+10:00 | at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
  | 2023-07-31T10:58:54.740+10:00 | at Socket.emit (node:events:513:28)
  | 2023-07-31T10:58:54.740+10:00 | at Socket.emit (node:domain:489:12)
  | 2023-07-31T10:58:54.740+10:00 | at addChunk (node:internal/streams/readable:315:12)
  | 2023-07-31T10:58:54.740+10:00 | at readableAddChunk (node:internal/streams/readable:289:9)
  | 2023-07-31T10:58:54.740+10:00 | at Socket.Readable.push (node:internal/streams/readable:228:10)
  | 2023-07-31T10:58:54.740+10:00 | at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

```

**Comment by pofider** [comment]
Please add the mentioned column `jsreport_ProfileType.timeout` as an integer number to your database
