### ISSUE TITLE
Unable to require jsdom

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#1128]
https://playground.jsreport.net/w/anon/Nq7CyAhG

```
Error when evaluating custom script /script
Unable to require module /tmp/jsreport/npm/modules/jsdom@17.0.0/node_modules/jsdom. resolveModulePath is not a function
TypeError: resolveModulePath is not a function
    at resolveFilename (/app/node_modules/@jsreport/jsreport-core/lib/worker/sandbox/resolveFilename.js:19:24)
    at Function.resolve (/app/node_modules/@jsreport/jsreport-core/lib/worker/sandbox/isolatedRequire.js:195:12)
    at Object.<anonymous> (/tmp/jsreport/npm/modules/jsdom@17.0.0/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:31:50)
```

**Comment by davericher** [comment]
Interested!
