### ISSUE TITLE
[Bug]: Docx nested ul/li doesn't work properly 

### ISSUE THREAD

**Issue by alwyn974** [jsreport/jsreport#1133]
Hi, I found this bug while trying to make a list from ul/li. It was already there when I created #1119
Here some screenshot

---
Wrong type of chips used

![image](https://github.com/jsreport/jsreport/assets/47529956/7c9111f7-eaf9-4d26-bcee-3e2d3f406127)

It should look like this 

![image](https://github.com/jsreport/jsreport/assets/47529956/7d89b492-a5cc-4587-aef9-f1bf7f8c401a)

---
Here the playground link https://playground.jsreport.net/w/alwyn974/xEnhA7Yu
There's also another example with the maximum depth allowed by word.
Also, an error occurs if I try to add another nested element. I've included it in the json as a `tooMuchNested` property.

```js
Report "template" render failed.

Error while executing docx recipe
(because) cannot read properties of undefined (reading 'hasAttribute')
TypeError: Cannot read properties of undefined (reading 'hasAttribute')
    at addOrGetNumbering (/app/node_modules/@jsreport/jsreport-docx/lib/postprocess/html/convertDocxMetaToNodes.js:1195:20)
    at convertDocxMetaToNodes (/app/node_modules/@jsreport/jsreport-docx/lib/postprocess/html/convertDocxMetaToNodes.js:96:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async processParagraphHtmlEmbedContainer (/app/node_modules/@jsreport/jsreport-docx/lib/postprocess/html/index.js:130:22)
    at async /app/node_modules/@jsreport/jsreport-docx/lib/postprocess/html/index.js:35:33
    at async Promise.all (index 1)
    at async module.exports (/app/node_modules/@jsreport/jsreport-docx/lib/postprocess/html/index.js:22:23)
    at async module.exports (/app/node_modules/@jsreport/jsreport-docx/lib/postprocess/postprocess.js:28:3)
    at async module.exports (/app/node_modules/@jsreport/jsreport-docx/lib/processDocx.js:92:5)
    at async module.exports (/app/node_modules/@jsreport/jsreport-docx/lib/recipe.js:35:28)
wrapped by:
Error: Error while executing docx recipe
(because) cannot read properties of undefined (reading 'hasAttribute')
    at module.exports (/app/node_modules/@jsreport/jsreport-core/lib/shared/createError.js:10:13)
    at WorkerReporter.createError (/app/node_modules/@jsreport/jsreport-core/lib/shared/reporter.js:53:12)
    at module.exports (/app/node_modules/@jsreport/jsreport-docx/lib/processDocx.js:117:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/app/node_modules/@jsreport/jsreport-docx/lib/recipe.js:35:28)
    at async invokeRender (/app/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:93:5)
    at async WorkerReporter._render (/app/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:148:7)
    at async /app/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js:227:24
    at async processAndResponse (/app/node_modules/@jsreport/advanced-workers/lib/workerHandler.js:41:17)
```

Tested on jsreport version 4.2.0-full and 4.3.1-full

**Comment by bjrmatos** [comment]
thanks, we will check
