### ISSUE TITLE
Raises errors when using PNPM

### ISSUE THREAD

**Issue by ml653** [jsreport/jsreport#1137]
It appears as though default installation of jsreport and @jsreport/jsreport-cli raises errors when using PNPM. 

### Steps to reproduce

Node version: v22.2.0
PNPM version: 9.1.0

package.json
```
{
  "name": "jsreport_test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "@jsreport/jsreport-cli": "^4.0.4",
    "jsreport": "^4.3.1"
  }
}
```
After pnpm installing and running the following commands:
```
pnpm install
pnpm exec jsreport init
pnpm exec jsreport configure
pnpm exec jsreport start
```
 The very last command fails due to the following errors and is reproducible every time.  I don't get this error when using npm or yarn, only with npm with the same package.json.  Any ideas what might be causing this? 

```
2024-05-20T07:19:29.685Z - info: Initializing jsreport (version: 4.3.1, configuration file: none, nodejs: 22.2.0)
2024-05-20T07:19:29.686Z - info: Searching for available extensions in /Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/jsreport@4.3.1_react@16.14.0/
2024-05-20T07:19:29.689Z - info: Extensions location cache contains up to date information, skipping crawling in /Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/jsreport@4.3.1_react@16.14.0/
2024-05-20T07:19:29.728Z - info: Found 35 extension(s)
2024-05-20T07:19:29.745Z - debug: Writing extension locations cache to /var/folders/lm/s4ltv92107x4yf451bbqj8sw0000gp/T/jsreport/core/locations.json
2024-05-20T07:19:29.746Z - debug: Discovered 35 extensions
2024-05-20T07:19:29.765Z - info: Using extension authentication@4.1.1
2024-05-20T07:19:29.848Z - debug: Extension authentication@4.1.1 was disabled
2024-05-20T07:19:29.848Z - info: Using extension base@4.0.0
2024-05-20T07:19:29.851Z - info: Using extension child-templates@4.1.0
2024-05-20T07:19:29.851Z - info: Using extension cli@4.0.4
2024-05-20T07:19:29.852Z - info: Using extension components@4.0.0
2024-05-20T07:19:29.853Z - info: Using extension data@4.1.0
2024-05-20T07:19:29.853Z - info: Using extension express@4.1.1
2024-05-20T07:19:30.032Z - info: Using extension freeze@4.0.0
2024-05-20T07:19:30.033Z - info: Using extension fs-store@4.0.3
2024-05-20T07:19:30.096Z - debug: Extension fs-store@4.0.3 was disabled
2024-05-20T07:19:30.097Z - info: Using extension handlebars@4.0.1
2024-05-20T07:19:30.098Z - info: Using extension import-export@4.0.3
2024-05-20T07:19:30.104Z - info: Using extension jsrender@4.0.0
2024-05-20T07:19:30.105Z - info: Using extension licensing@4.0.2
2024-05-20T07:19:30.108Z - info: Using extension localization@4.0.1
2024-05-20T07:19:30.108Z - info: Using extension npm@4.0.0
2024-05-20T07:19:30.110Z - info: Using extension pdf-utils@4.1.1
2024-05-20T07:19:30.111Z - info: Using extension reports@4.1.1
2024-05-20T07:19:30.112Z - info: Using extension tags@4.0.1
2024-05-20T07:19:30.113Z - info: Using extension text@4.0.0
2024-05-20T07:19:30.113Z - info: Using extension version-control@4.0.0
2024-05-20T07:19:30.122Z - info: Using extension assets@4.1.0
2024-05-20T07:19:30.133Z - info: Using extension authorization@4.0.0
2024-05-20T07:19:30.137Z - debug: Extension authorization@4.0.0 was disabled
2024-05-20T07:19:30.137Z - info: Using extension browser-client@4.1.0
2024-05-20T07:19:30.138Z - info: Using extension chrome-pdf@4.1.0
2024-05-20T07:19:30.139Z - debug: Chrome strategy is chrome-pool, numberOfWorkers: 1
2024-05-20T07:19:30.139Z - info: Using extension docx@4.2.1
2024-05-20T07:19:30.145Z - info: Using extension html-to-xlsx@4.1.1
2024-05-20T07:19:30.343Z - info: html-to-xlsx detected chrome as available html engine
2024-05-20T07:19:30.343Z - info: Using extension pptx@4.2.0
2024-05-20T07:19:30.344Z - info: Using extension scheduling@4.0.0
2024-05-20T07:19:30.361Z - info: Using extension scripts@4.1.0
2024-05-20T07:19:30.362Z - info: Using extension static-pdf@4.1.0
2024-05-20T07:19:30.362Z - info: Using extension studio@4.1.0
2024-05-20T07:19:30.401Z - info: Using extension xlsx@4.1.0
2024-05-20T07:19:30.402Z - info: Using extension public-templates@4.0.0
2024-05-20T07:19:30.403Z - debug: Extension public-templates@4.0.0 was disabled
2024-05-20T07:19:30.403Z - info: Using extension sample-template@4.0.0
2024-05-20T07:19:30.404Z - info: Using extension studio-theme-dark@4.0.0
2024-05-20T07:19:30.405Z - info: Using general timeout for rendering (reportTimeout: 60000)
2024-05-20T07:19:30.405Z - info: Using memory provider for template store. The saved templates will be lost after restart
2024-05-20T07:19:30.409Z - debug: studio default theme is: light
2024-05-20T07:19:30.411Z - info: Creating default express app.
2024-05-20T07:19:30.426Z - info: jsreport server successfully started on http port: 5488
2024-05-20T07:19:30.428Z - info: Verifying license key free
2024-05-20T07:19:30.429Z - info: Using free license
2024-05-20T07:19:30.432Z - info: Migrating templates chrome settings (waitForNetworkIddle -> waitForNetworkIdle)
2024-05-20T07:19:30.432Z - info: Migration successful
2024-05-20T07:19:30.433Z - debug: Creating samples is disabled
2024-05-20T07:19:30.433Z - info: Initializing worker threads
2024-05-20T07:19:30.433Z - debug: Extensions in workers: base, child-templates, components, data, express, handlebars, jsrender, localization, npm, pdf-utils, reports, text, version-control, assets, browser-client, chrome-pdf, docx, html-to-xlsx, pptx, scripts, static-pdf, studio, xlsx
2024-05-20T07:19:30.879Z - error: Error occurred during reporter init: TypeError: Accessor not expected at intrinsics.%IteratorPrototype%.constructor
  at isAllowedProperty (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:4029:13)
  at visitProperties (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:4076:26)
  at isAllowedPropertyValue (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:3963:7)
  at isAllowedProperty (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:4026:14)
  at visitProperties (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:4076:26)
  at whitelistIntrinsics (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:4119:3)
  at repairIntrinsics (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:9808:3)
  at globalThis.lockdown (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:9897:28)
  at WorkerReporter.init (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+jsreport-core@4.2.2/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js:91:7)
  at async processAndResponse (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+advanced-workers@2.0.2/node_modules/@jsreport/advanced-workers/lib/workerHandler.js:41:17)
An error ocurred while trying to execute "start" command (3)
(because) an error has occurred when trying to initialize jsreport (2)
(because) accessor not expected at intrinsics.%IteratorPrototype%.constructor (1)

-- error (1) --
-> stack
TypeError:
  at isAllowedProperty (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:4029:13)
  at visitProperties (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:4076:26)
  at isAllowedPropertyValue (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:3963:7)
  at isAllowedProperty (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:4026:14)
  at visitProperties (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:4076:26)
  at whitelistIntrinsics (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:4119:3)
  at repairIntrinsics (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:9808:3)
  at globalThis.lockdown (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+ses@1.0.1/node_modules/@jsreport/ses/index.js:9897:28)
  at WorkerReporter.init (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+jsreport-core@4.2.2/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js:91:7)
  at async processAndResponse (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+advanced-workers@2.0.2/node_modules/@jsreport/advanced-workers/lib/workerHandler.js:41:17)
wrapped by:
-- error (2) --
-> stack
Error:
    at /Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+jsreport-cli@4.0.4/node_modules/@jsreport/jsreport-cli/lib/instanceHandler.js:31:29
    at async executeCommand (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+jsreport-cli@4.0.4/node_modules/@jsreport/jsreport-cli/lib/commander/executeCommand.js:22:20)
    at async Object.handler (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+jsreport-cli@4.0.4/node_modules/@jsreport/jsreport-cli/lib/commander/registerCommand.js:76:9)
    at async parseCLI (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+jsreport-cli@4.0.4/node_modules/@jsreport/jsreport-cli/lib/commander/startCommand.js:156:3)
    at async startCLI (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+jsreport-cli@4.0.4/node_modules/@jsreport/jsreport-cli/lib/commander/startCommand.js:121:20)
    at async startCommand (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+jsreport-cli@4.0.4/node_modules/@jsreport/jsreport-cli/lib/commander/startCommand.js:67:5)
    at async startProcessing (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+jsreport-cli@4.0.4/node_modules/@jsreport/jsreport-cli/lib/commander/startProcessing.js:195:3)
wrapped by:
-- error (3) --
-> stack
Error:
    at startCLI (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+jsreport-cli@4.0.4/node_modules/@jsreport/jsreport-cli/lib/commander/startCommand.js:127:19)
    at async startCommand (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+jsreport-cli@4.0.4/node_modules/@jsreport/jsreport-cli/lib/commander/startCommand.js:67:5)
    at async startProcessing (/Users/stevenli/git/jsreport_pnpm/node_modules/.pnpm/@jsreport+jsreport-cli@4.0.4/node_modules/@jsreport/jsreport-cli/lib/commander/startProcessing.js:195:3)
```

**Comment by bjrmatos** [comment]
hi @ml653 

we will see if this error goes away after updating ses, thanks for reporting

**Comment by bjrmatos** [comment]
updating ses make this to work.

however FYI we are not sure if the extensions loading will work the same with pnpm, we have a particular way to load extensions and it depends on how packages are stored in `node_modules`, which pnpm stores it differently. anyway, what you were testing will work in the next version of jsreport. 

feel free to report new bugs around pnpm, it is not our high priority we will try to check them as they appear

**Comment by ml653** [comment]
Thank you!

**Comment by pdecat** [comment]
Can confirm using pnpm breaks extensions such as fs-store:
```
# ./node_modules/.bin/jsreport start
2024-09-11T13:06:52.986Z - info: Initializing jsreport (version: 4.6.0, configuration file: none, nodejs: 20.17.0)
2024-09-11T13:06:52.988Z - info: Searching for available extensions in /home/patrick/workspaces/myproject/node_modules/.pnpm/jsreport@4.6.0_react@16.14.0_typescript@5.4.2/
2024-09-11T13:06:52.992Z - info: Extensions location cache contains up to date information, skipping crawling in /home/patrick/workspaces/myproject/node_modules/.pnpm/jsreport@4.6.0_react@16.14.0_typescript@5.4.2/
2024-09-11T13:06:53.018Z - info: Found 35 extension(s)
2024-09-11T13:06:53.032Z - debug: Writing extension locations cache to /tmp/jsreport/core/locations.json
2024-09-11T13:06:53.034Z - debug: Discovered 35 extensions
2024-09-11T13:06:53.076Z - info: Using extension authentication@4.2.1
2024-09-11T13:06:53.166Z - debug: Extension authentication@4.2.1 was disabled
2024-09-11T13:06:53.166Z - info: Using extension base@4.0.0
2024-09-11T13:06:53.169Z - info: Using extension child-templates@4.1.0
2024-09-11T13:06:53.170Z - info: Using extension cli@4.0.4
2024-09-11T13:06:53.171Z - info: Using extension components@4.0.2
2024-09-11T13:06:53.173Z - info: Using extension data@4.1.0
2024-09-11T13:06:53.173Z - info: Using extension express@4.1.2
2024-09-11T13:06:53.316Z - info: Using extension freeze@4.0.0
2024-09-11T13:06:53.318Z - info: Using extension fs-store@4.0.4
2024-09-11T13:06:53.376Z - debug: Extension fs-store@4.0.4 was disabled
...
```

**Comment by chris-lingwood-korelabs-co** [comment]
I've done far too much digging on this today. Its not broken as such, it just doesn't work. It comes down to jsreports getting the rootDirectory "wrong". It ends up pointing somwhere inside the `node_modules/.pnpm` directory. This is great for autodetecting the extensions but its unlikely to be where your where your config, assets and templates are. You can't just fix the rootDirectory because then extension autodetection breaks (maybe there is a fix for that which I missed).

You need to fix a few things which are controlable by env vars, you can also do these in code which is what we have done at the start of our `main.js`.
First you need to load your config, that should reenable the fs-store extension.
```
process.env.configFile = process.cwd()+"/jsreport.config.json";
```
You can manually assign an _absolute_ path to that env var too.
We had a relative path for our fs-store data directory in the config file. You can put a static _absolute_ path in the config file if that works for you, or a dynamic one (we needed a dynamic path for various reasons) in code.
```
process.env.extensions_fsStore_dataDirectory = process.cwd()+"/templates/";
```
That should get your templates loading again. If that fixes everything then stop reading.

Unfortunately we hit the next issue, jsreports asset references rootDirectory again (instead of "something else" configurable) so your assets won't be found. Since rootDirectory is important for extension detection you can't just change it. Fortunately it allows absolute paths.
We had relative paths in our templates so that was broken.
```
src: url({{asset "relative/path/to/asset.file" "dataURI"}}
```
If you replace that with:
```
src: url({{wrappedAsset "relative/path/to/asset.file" "dataURI"}}
```
Then you create a handlerbars helper:
```
function wrappedAsset(path, option) {
  const fullPath = process.env.extensions_fsStore_dataDirectory + path;
  return Handlebars.helpers.asset(fullPath,option);
}
```
This dynamically rewrites the paths to absolute paths which actually exist. This is all handy for having it work on developer machines and in containers.

We are only using jsreports for pdf generation but this now works with pnpm on 4.6.0.
