### ISSUE TITLE
Error in version 4.4.0 when using pdf-utils

### ISSUE THREAD

**Issue by pier-M** [jsreport/jsreport#1140]
When we use the script below with version 4.4.0, we are getting an error.
It was not a is still not the case with version 4.3.1

script : 

const jsreport = require('jsreport-proxy')

async function afterRender(req, res) {

    if (req.data.isVad) {
        const pdf = await jsreport.documentStore.collection('assets').findOne({
            name: 'CGV_VAD.pdf',
        });
        res.content = pdf.content
    } else {
        const pdf = await jsreport.documentStore.collection('assets').findOne({
            name: 'CGV.pdf',
        });
        res.content = pdf.content
    }
}

error : 

`Error while executing pdf-utils operations
(because) cannot read properties of undefined (reading 'content')
TypeError: Cannot read properties of undefined (reading 'content')
  at processText (/app/node_modules/@jsreport/pdfjs/lib/mixins/processText.js:19:70)
  at async Document.asBuffer (/app/node_modules/@jsreport/pdfjs/lib/document.js:68:7)
  at async Object.postprocess (/app/node_modules/@jsreport/jsreport-pdf-utils/lib/pdfManipulator.js:206:25)
  at async module.exports (/app/node_modules/@jsreport/jsreport-pdf-utils/lib/pdfProcessing.js:133:3)
  at async AsyncFunction. (/app/node_modules/@jsreport/jsreport-pdf-utils/lib/worker.js:204:22)
  at async ListenerCollection.fire (/app/node_modules/@jsreport/jsreport-core/lib/shared/listenerCollection.js:157:21)
  at async afterRender (/app/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:102:5)
  at async WorkerReporter._render (/app/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:149:7)
  at async /app/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js:227:24
  at async processAndResponse (/app/node_modules/@jsreport/advanced-workers/lib/workerHandler.js:41:17)
wrapped by:
Error: Error while executing pdf-utils operations
(because) cannot read properties of undefined (reading 'content')
  at module.exports (/app/node_modules/@jsreport/jsreport-core/lib/shared/createError.js:10:13)
  at WorkerReporter.createError (/app/node_modules/@jsreport/jsreport-core/lib/shared/reporter.js:53:12)
  at AsyncFunction. (/app/node_modules/@jsreport/jsreport-pdf-utils/lib/worker.js:223:22)
  at async ListenerCollection.fire (/app/node_modules/@jsreport/jsreport-core/lib/shared/listenerCollection.js:157:21)
  at async afterRender (/app/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:102:5)
  at async WorkerReporter._render (/app/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:149:7)
  at async /app/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js:227:24
  at async processAndResponse (/app/node_modules/@jsreport/advanced-workers/lib/workerHandler.js:41:17)`

**Comment by pofider** [comment]
Thank you for reporting the issue. 
Can you share those external PDFs?

**Comment by pier-M** [comment]
Hello,

I asked our customer for authorization to share pdf with you, I will come back to you when I have the answer.


De : Jan Blaha ***@***.***>
Envoyé : mardi 28 mai 2024 17:54
À : jsreport/jsreport ***@***.***>
Cc : Pierre Michel ***@***.***>; Author ***@***.***>
Objet : Re: [jsreport/jsreport] Error in version 4.4.0 when using pdf-utils (Issue #1140)


Thank you for reporting the issue.
Can you share those external PDFs?

**Comment by pofider** [comment]
You can also confidentially email it to me jan.blaha@jsreport.net

**Comment by pofider** [comment]
Any update on this? We will be releasing the next week, so the fix could be there.

**Comment by pier-M** [comment]
Hello,

Sorry for the big delay to have permission to transmit the file.



De : Jan Blaha ***@***.***>
Envoyé : vendredi 14 juin 2024 19:04
À : jsreport/jsreport ***@***.***>
Cc : Pierre Michel ***@***.***>; Author ***@***.***>
Objet : Re: [jsreport/jsreport] Error in version 4.4.0 when using pdf-utils (Issue #1140)


Any update on this? We will be releasing the next week, so the fix could be there.

**Comment by pofider** [comment]
I am closing as there is no response here.
However, feel free to reopen or email me the problematic pdfs.

**Comment by pier-M** [comment]
Hello,

I did email you the problematic pdf, the 24/06.

Would you like me to send it again?


De : Jan Blaha ***@***.***>
Envoyé : mardi 24 septembre 2024 22:35
À : jsreport/jsreport ***@***.***>
Cc : Pierre Michel ***@***.***>; Author ***@***.***>
Objet : Re: [jsreport/jsreport] Error in version 4.4.0 when using pdf-utils (Issue #1140)


I am closing as there is no response here.
However, feel free to reopen or email me the problematic pdfs.

**Comment by pofider** [comment]
Yes please, I can't find it.

**Comment by pier-M** [comment]
Here it is.

De : Jan Blaha ***@***.***>
Envoyé : mercredi 25 septembre 2024 14:37
À : jsreport/jsreport ***@***.***>
Cc : Pierre Michel ***@***.***>; Author ***@***.***>
Objet : Re: [jsreport/jsreport] Error in version 4.4.0 when using pdf-utils (Issue #1140)


Yes please, I can't find it.

**Comment by pofider** [comment]
It looks like the attachment gets lost if you reply to the github notification email...

Please upload it directly to this github issue or email it to me directly.

**Comment by pofider** [comment]
Thank you for sharing the pdf. I've pushed to fix it to the master. It will be part of the next release 4.7.0, which we likely release at the end of next week.

**Comment by pier-M** [comment]
Thanks for the update. I will test it when I have the time and will get back to you.



De : Jan Blaha ***@***.***>
Envoyé : jeudi 3 octobre 2024 08:42
À : jsreport/jsreport ***@***.***>
Cc : Pierre Michel ***@***.***>; Author ***@***.***>
Objet : Re: [jsreport/jsreport] Error in version 4.4.0 when using pdf-utils (Issue #1140)


Thank you for sharing the pdf. I've pushed to fix it to the master. It will be part of the next release 4.7.0, which we likely release at the end of next week.
