### ISSUE TITLE
html-to-xlsx with cheerio and htmlToXlsxEachRows errors

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#1147]
https://playground.jsreport.net/w/anon/B4Oy6SiD

```
Error while executing html-to-xlsx recipe
(because) $ is not a function
TypeError: $ is not a function
  at extractRowInformation (C:\work\jsreport\temp\node_modules\cheerio-page-eval\lib\eval.js:157:16)
  at C:\work\jsreport\temp\node_modules\cheerio-page-eval\lib\eval.js:138:23
```

**Comment by bjrmatos** [comment]
fixed in https://github.com/jsreport/cheerio-page-eval/commit/baa55fbf75f49d12b21fb905299cb6560c5d0205
