### ISSUE TITLE
html-to-xlsx hangs using docker environment

### ISSUE THREAD

**Issue by mm3141** [jsreport/jsreport#1157]
1. start environment using `docker run -p 5488:5488 --rm -it jsreport/jsreport:4.6.0`
2. open jsReport studio: `http://localhost:5488`
3. create a new html-to-xlsx tempate, throw in simple content like ```<table><tr><td>text</td></tr></table>```
4. run it

The report generation times out after one minute:
```
2024-08-15 13:37:29 2024-08-15T11:37:29.392Z - info: Rendering template { name: test, recipe: html-to-xlsx, engine: handlebars, preview: true } rootId=616ih3m0kfj6g6q, id=616ih3m0kfj6g6q
2024-08-15 13:37:29 2024-08-15T11:37:29.392Z - debug: Data item not defined for this template. rootId=616ih3m0kfj6g6q, id=616ih3m0kfj6g6q
2024-08-15 13:37:29 2024-08-15T11:37:29.393Z - debug: Base url not specified, skipping its injection. rootId=616ih3m0kfj6g6q, id=616ih3m0kfj6g6q
2024-08-15 13:37:29 2024-08-15T11:37:29.394Z - debug: Rendering engine handlebars rootId=616ih3m0kfj6g6q, id=616ih3m0kfj6g6q
2024-08-15 13:37:29 2024-08-15T11:37:29.768Z - debug: Executing recipe html-to-xlsx rootId=616ih3m0kfj6g6q, id=616ih3m0kfj6g6q
2024-08-15 13:37:29 2024-08-15T11:37:29.940Z - info: html-to-xlsx generation is starting rootId=616ih3m0kfj6g6q, id=616ih3m0kfj6g6q
2024-08-15 13:37:35 2024-08-15T11:37:35.083Z - debug: OData insert into templates
2024-08-15 13:38:29 2024-08-15T11:38:29.366Z - warn: Error when processing render request 1
2024-08-15 13:38:29 (because) error while executing html-to-xlsx recipe
2024-08-15 13:38:29 (because) timeout Error: script evaluation not completed after 59424ms
2024-08-15 13:38:29 Error: Timeout Error: script evaluation not completed after 59424ms
2024-08-15 13:38:29   at Timeout._onTimeout (/app/node_modules/chrome-page-eval/lib/eval.js:19:19)
2024-08-15 13:38:29   at listOnTimeout (node:internal/timers:569:17)
2024-08-15 13:38:29   at process.processTimers (node:internal/timers:512:7)
2024-08-15 13:38:29 wrapped by:
2024-08-15 13:38:29 Error: Error while executing html-to-xlsx recipe
2024-08-15 13:38:29 (because) timeout Error: script evaluation not completed after 59424ms
2024-08-15 13:38:29   at module.exports (/app/node_modules/@jsreport/jsreport-core/lib/shared/createError.js:10:13)
2024-08-15 13:38:29   at WorkerReporter.createError (/app/node_modules/@jsreport/jsreport-core/lib/shared/reporter.js:53:12)
2024-08-15 13:38:29   at module.exports (/app/node_modules/@jsreport/jsreport-html-to-xlsx/lib/recipe.js:162:20)
2024-08-15 13:38:29   at async invokeRender (/app/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:93:5)
2024-08-15 13:38:29   at async WorkerReporter._render (/app/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:148:7)
2024-08-15 13:38:29   at async /app/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js:232:24
2024-08-15 13:38:29   at async processAndResponse (/app/node_modules/@jsreport/advanced-workers/lib/workerHandler.js:41:17) rootId=616ih3m0kfj6g6q, id=616ih3m0kfj6g6q
```

Some chromium processes are hanging around, consuming 1 CPU each
```
Mem: 7463972K used, 8918876K free, 65432K shrd, 410116K buff, 5217848K cached
CPU: 100% usr   0% sys   0% nic   0% idle   0% io   0% irq   0% sirq
Load average: 3.99 3.22 2.43 6/516 267
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   81    36 jsreport R    1155g6935%   1  25% /usr/lib/chromium/chromium --type=renderer --crashpad-handler-pid=0 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-EbOoaP --change-sta
  199   148 jsreport R    1155g6935%   2  25% /usr/lib/chromium/chromium --type=renderer --crashpad-handler-pid=0 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-HpBiGh --change-sta
  200   148 jsreport R    1155g6935%   0  25% /usr/lib/chromium/chromium --type=renderer --crashpad-handler-pid=0 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-HpBiGh --change-sta
   83    36 jsreport R    1155g6935%   3  25% /usr/lib/chromium/chromium --type=renderer --crashpad-handler-pid=0 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-EbOoaP --change-sta
  115    36 jsreport S    1155g6935%   0   0% /usr/lib/chromium/chromium --type=renderer --crashpad-handler-pid=0 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-EbOoaP --change-sta
  229   148 jsreport S    1155g6935%   2   0% /usr/lib/chromium/chromium --type=renderer --crashpad-handler-pid=0 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-HpBiGh --change-sta
  141     1 jsreport S    32.4g 195%   3   0% {chromium} /usr/lib/chromium/chrome --allow-pre-commit-input --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disa
   28     1 jsreport S    32.4g 195%   1   0% {chromium} /usr/lib/chromium/chrome --allow-pre-commit-input --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disa
  135    35 jsreport S    32.3g 194%   0   0% /usr/lib/chromium/chromium --type=gpu-process --no-sandbox --disable-dev-shm-usage --disable-breakpad --headless=new --ozone-platform=headless --use-angle=swiftshader-webgl --cra
   63    28 jsreport S    32.3g 194%   0   0% /usr/lib/chromium/chromium --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --disable-dev-shm-usage --use-angl
  171   141 jsreport S    32.3g 194%   2   0% /usr/lib/chromium/chromium --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --disable-dev-shm-usage --use-angl
  255   147 jsreport S    32.3g 194%   2   0% /usr/lib/chromium/chromium --type=gpu-process --no-sandbox --disable-dev-shm-usage --disable-breakpad --headless=new --ozone-platform=headless --use-angle=swiftshader-webgl --cra
```

**Comment by pofider** [comment]
I can't replicate this.  Please try to isolate the problem. 
Try it on another machine. Try to render multiple times. Try it without interactive mode `-it`.

**Comment by mm3141** [comment]
This happens on all of:
- my Windows machine running Docker Desktop
- our Linux build machines
- Kubernetes cluster (AWS EKS)

I have exported some example:
[1157.jsrexport.zip](https://github.com/user-attachments/files/16633487/1157.jsrexport.zip)

Can you share some hints for diagnosing what chromium is doing there in this situation?

**Comment by pofider** [comment]
Thank you.
While we see no issues on Windows/Mac with Docker desktop, I can replicate this on fresh Linux now. 
We will analyze it and come back here.

**Comment by pofider** [comment]
This should make it work, we add it to docs for now and decide with the next release if we put `--disable-gpu` to the image default.
```
docker run -p 5488:5488 -e "chrome_launchOptions_args=--no-sandbox, --disable-dev-shm-usage, --disable-gpu" jsreport/jsreport:4.6.0
```

**Comment by mm3141** [comment]
@pofider is this the same as putting it under `extensions.chrome-pdf.launchOptions.args` in the jsreport.config.json? We already have that in there in our image, and it does not work.

**Comment by pofider** [comment]
I think dockerfile overwrites it with env
https://github.com/jsreport/jsreport/blob/master/packages/jsreport/docker/default/Dockerfile#L109

Try to use the env variable which has higher priority

**Comment by mm3141** [comment]
Interestingly, it seems to take the `--ignore-certificate-errors-spki-list` from there for PDF reports, otherwise our tests would complain. Anyway, I am going to move the chrome options from the config to the environment variable, to have them take effect everywhere.
