### ISSUE TITLE
Error log in non admin user

### ISSUE THREAD

**Issue by jorisdebock** [jsreport/jsreport#1185]
After upgrading to jsreport 4.x.x the following error happens when logging in with a user which does not have the isAdmin flag set to true. There are also no groups defined in our database.

```
Error during processing request at http://127.0.0.1:5489/api/settings, details: TypeError: Cannot read properties of undefined (reading 'complexType')
at eq (node_modules\\@jsreport\\odata-to-sql\\lib\\filter.js:40:22)\n    
at filterObject (node_modules\\@jsreport\\odata-to-sql\\lib\\filter.js:115:44)\n    
at module.exports (node_modules\\@jsreport\\odata-to-sql\\lib\\filter.js:127:22)\n    
at module.exports (node_modules\\@jsreport\\odata-to-sql\\lib\\query.js:66:11)\n    
at Object.query (node_modules\\@jsreport\\odata-to-sql\\lib\\transformer.js:46:14)\n    
at Cursor.toArray (node_modules\\@jsreport\\sql-store\\lib\\sqlProvider.js:22:29)\n    
at replay (node_modules\\@jsreport\\jsreport-core\\lib\\main\\store\\collection.js:53:21)\n    
at node_modules\\@jsreport\\jsreport-core\\lib\\main\\store\\collection.js:60:18\n    
at async resolveIsAdmin (node_modules\\@jsreport\\jsreport-authentication\\lib\\main.js:652:38)\n    
at async Authentication.isUserAdmin (node_modules\\@jsreport\\jsreport-authentication\\lib\\main.js:597:40)
```

it is caused by this query
```
const adminGroupsForUser = await groupCol.find({
            isAdmin: true,
            'users.shortid': userInStore.shortid
          }, { name: 1 })
```

versions used:
```
    "@jsreport/jsreport-assets": "4.1.1",
    "@jsreport/jsreport-authentication": "4.2.1",
    "@jsreport/jsreport-authorization": "4.0.0",
    "@jsreport/jsreport-base": "4.0.0",
    "@jsreport/jsreport-child-templates": "4.1.0",
    "@jsreport/jsreport-chrome-pdf": "4.1.0",
    "@jsreport/jsreport-cli": "4.0.4",
    "@jsreport/jsreport-core": "4.4.1",
    "@jsreport/jsreport-data": "4.1.0",
    "@jsreport/jsreport-express": "4.1.2",
    "@jsreport/jsreport-freeze": "4.0.0",
    "@jsreport/jsreport-import-export": "4.0.4",
    "@jsreport/jsreport-jsrender": "4.0.0",
    "@jsreport/jsreport-licensing": "4.0.2",
    "@jsreport/jsreport-localization": "4.0.1",
    "@jsreport/jsreport-oracle-store": "4.0.0",
    "@jsreport/jsreport-pdf-utils": "4.2.1",
    "@jsreport/jsreport-public-templates": "4.0.0",
    "@jsreport/jsreport-scripts": "4.1.0",
    "@jsreport/jsreport-studio": "4.1.1",
    "@jsreport/jsreport-studio-theme-dark": "4.0.0",
    "@jsreport/jsreport-tags": "4.0.1",
    "@jsreport/jsreport-text": "4.0.2",
    "@jsreport/jsreport-version-control": "4.0.0",
```

**Comment by bjrmatos** [comment]
hi! 

at first glance i am not sure if you are using jsreport (the package with the extensions in it), or jsreport core + extensions.

when this happens? do you mean after login in studio?

**Comment by jorisdebock** [comment]
@bjrmatos as you can see from the packages, we are using core + extensions and the oracle-store as database

It does happen when I try to login with a user in the studio, it keeps showing the loading screen with this error in the logs

**Comment by bjrmatos** [comment]
@jorisdebock does this happen if you start with an empty database? i mean no prior data, if it starts fine and then you create a non admin user, are you able to login normally? if yes, then it means it is some kind of migration issue between versions.

**Comment by jorisdebock** [comment]
@bjrmatos it is the same result. 

This filter can not be found 'users.shortid' in the entityType

**Comment by jorisdebock** [comment]
@bjrmatos @pofider could I provide more info or do another test? 

I am not sure how this query should work, it seems the filter can not be found in de definition defined e.g.

'users.shortid' can not be resolved with these types registered
```
  reporter.documentStore.registerComplexType('UserRefType', {
    shortid: { type: 'Edm.String', referenceTo: 'users' }
  })

  reporter.documentStore.registerEntityType('UsersGroupType', {
    name: { type: 'Edm.String' },
    users: { type: 'Collection(jsreport.UserRefType)' },
    isAdmin: { type: 'Edm.Boolean' }
  })
```

**Comment by bjrmatos** [comment]
@jorisdebock thanks, no more info is needed, i started checking this yesterday, it should be fixed. it will be part of next release, for which we don't have an exact date yet.
