### ISSUE TITLE
chrome-pdf with copy tags enabled causes an error

### ISSUE THREAD

**Issue by jorisdebock** [jsreport/jsreport#1189]
After upgrading to jsreport 4.x.x the following error happens when rendering a pdf with chrome-pdf and pdf accessibility "copy tags" is enabled

```
Error while executing pdf-utils operations
(because) cannot read properties of undefined (reading 'object')
TypeError: Cannot read properties of undefined (reading 'object')
    at mergeStructTree (node_modules/@jsreport/pdfjs/lib/mixins/utils/unionGlobalObjects.js:125:63)
    at module.exports (node_modules/@jsreport/pdfjs/lib/mixins/utils/unionGlobalObjects.js:28:5)
    at merge (node_modules/@jsreport/pdfjs/lib/mixins/merge.js:143:3)
    at node_modules/@jsreport/pdfjs/lib/mixins/merge.js:7:64
    at Document.asBuffer (node_modules/@jsreport/pdfjs/lib/document.js:68:13)
    at async Object.merge (node_modules/@jsreport/jsreport-pdf-utils/lib/pdfManipulator.js:53:23)
    at async module.exports (node_modules/@jsreport/jsreport-pdf-utils/lib/pdfProcessing.js:93:9)
    at async AsyncFunction.<anonymous> (node_modules/@jsreport/jsreport-pdf-utils/lib/worker.js:204:22)
    at async ListenerCollection.fire (node_modules/@jsreport/jsreport-core/lib/shared/listenerCollection.js:157:21)
    at async afterRender (node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:102:5)
```

I am not sure how it suppose to work but "docStructTreeRoot.properties.get('IDTree')" seems to be undefined.

node_modules/@jsreport/pdfjs/lib/mixins/utils/unionGlobalObjects.js:125:63
```
  const docIDTree = docStructTreeRoot.properties.get('IDTree').object.properties.get('Kids')[0].object
```

versions used:

```
    "@jsreport/jsreport-assets": "4.1.1",
    "@jsreport/jsreport-authentication": "4.2.1",
    "@jsreport/jsreport-authorization": "4.0.0",
    "@jsreport/jsreport-base": "4.0.0",
    "@jsreport/jsreport-child-templates": "4.1.0",
    "@jsreport/jsreport-chrome-pdf": "4.1.0",
    "@jsreport/jsreport-cli": "4.0.4",
    "@jsreport/jsreport-core": "4.4.1",
    "@jsreport/jsreport-data": "4.1.0",
    "@jsreport/jsreport-express": "4.1.2",
    "@jsreport/jsreport-freeze": "4.0.0",
    "@jsreport/jsreport-import-export": "4.0.4",
    "@jsreport/jsreport-jsrender": "4.0.0",
    "@jsreport/jsreport-licensing": "4.0.2",
    "@jsreport/jsreport-localization": "4.0.1",
    "@jsreport/jsreport-oracle-store": "4.0.0",
    "@jsreport/jsreport-pdf-utils": "4.2.1",
    "@jsreport/jsreport-public-templates": "4.0.0",
    "@jsreport/jsreport-scripts": "4.1.0",
    "@jsreport/jsreport-studio": "4.1.1",
    "@jsreport/jsreport-studio-theme-dark": "4.0.0",
    "@jsreport/jsreport-tags": "4.0.1",
    "@jsreport/jsreport-text": "4.0.2",
    "@jsreport/jsreport-version-control": "4.0.0",
```

**Comment by pofider** [comment]
Are you merging external pdfs or the one produced by jsreport?
Would you be able to share the pdfs you are merging? 
If you don't want to share it publicly, you can email it to me confidentially.

**Comment by jorisdebock** [comment]
main.pdf (does not matter what I put in here)

```
test body
```

header-footer.pdf (without the text "test" it works without issues, but when I put any data in the "body" block it fails on this error)
```
<html>
<html>
    <head>
    </head>
    <body>
          test
    </body>
</html>
</html>
```

I configured in the main.pdf with pdf utils to merge the header-footer.pdf 
and
enabled pdf accessibility with copy tags

I have not been able to reproduce it in the jsreport playground

**Comment by pofider** [comment]
I cannot replicate this. I've tried the following which works fine
```js
jsreport.render({
      template: {
        content: 'test body',
        helpers: '',
        engine: 'none',
        recipe: 'chrome-pdf',
        pdfAccessibility: {
          enabled: true
        },
        pdfUtilsOperations: [{
          type: 'merge',        
          template: {
            content: `<html>
<html>
    <head>
    </head>
    <body>
          test
    </body>
</html>
</html>`,
            recipe: 'chrome-pdf',
            engine: 'handlebars'
          }
        }]
      }
    })
```

Please try to provide a minimal replicating repository.

**Comment by jorisdebock** [comment]
When I execute your example it does work without this error, but in the studio profiler I do not see pdf utils merge getting called.

code used: 
```
    jsreport.render({
      template: {
        content: 'test body',
        helpers: '',
        engine: 'none',
        recipe: 'chrome-pdf',
        pdfAccessibility: {
          enabled: true
        },
        pdfOperations: [{
          type: 'merge',   
          mergeWholeDocument: true,
          template: {
            content: `<html>
  <html>
    <head>
    </head>
    <body>
          test
    </body>
  </html>
  </html>`,
            recipe: 'chrome-pdf',
            engine: 'jsrender'
          }
        }]
      }
    })
    ```
    
    logs from studio:
```
info
+0
Render request 1 queued for execution and waiting for available worker
info
+12
Starting rendering request 1
info
+1
Rendering anonymous template { recipe: chrome-pdf, engine: none }
debug
+0
Data item not defined for this template.
debug
+10
Base url not specified, skipping its injection.
debug
+2
Rendering engine none
debug
+435
Executing recipe chrome-pdf
debug
+482
Converting with chrome Chrome/131.0.6778.69 using chrome-pool strategy
debug
+54
Page request: GET (document) file:///tmp/jsreport/autocleanup/b0a6a267-c018-449c-9f94-253239523bfb-chrome-pdf.html
debug
+16
Page request finished: GET (document) 200 file:///tmp/jsreport/autocleanup/b0a6a267-c018-449c-9f94-253239523bfb-chrome-pdf.html
debug
+6
Running chrome with params {"timeout":19297,"margin":{},"printBackground":true}
info
+49
pdf-utils is starting pdf processing
debug
+77
pdf-utils detected 0 pdf operation(s) to process
debug
+0
pdf-utils postprocess start
debug
+21
pdf-utils postprocess end
info
+1
pdf-utils pdf processing was finished
info
+0
Rendering request 1 finished in 1170 ms
```

When I execute the template in the studio I get these logs
```
info
+0
Render request 3 queued for execution and waiting for available worker
info
+28
Starting rendering request 3 (user: xx)
info
+1
Rendering template { name: test.pdf, recipe: chrome-pdf, engine: none, preview: true }
debug
+23
Data item not defined for this template.
debug
+56
Base url not specified, skipping its injection.
debug
+3
Rendering engine none
debug
+523
Executing recipe chrome-pdf
debug
+583
Converting with chrome Chrome/131.0.6778.69 using chrome-pool strategy
debug
+86
Page request: GET (document) file:///tmp/jsreport/autocleanup/92e00993-f3c9-4d1d-9348-864f3f4622ff-chrome-pdf.html
debug
+24
Page request finished: GET (document) 200 file:///tmp/jsreport/autocleanup/92e00993-f3c9-4d1d-9348-864f3f4622ff-chrome-pdf.html
debug
+4
Running chrome with params {"displayHeaderFooter":false,"printBackground":false,"format":"A4","timeout":19067,"margin":{}}
info
+67
pdf-utils is starting pdf processing
debug
+82
pdf-utils detected 1 pdf operation(s) to process
debug
+7
pdf-utils running pdf operation merge
info
+10
Starting rendering (child) request (user: xx)
info
+1
Rendering template { name: header-footer.pdf, recipe: chrome-pdf, engine: jsrender, preview: true }
debug
+21
Inline data specified.
debug
+31
Base url not specified, skipping its injection.
debug
+1
Rendering engine jsrender
debug
+80
Executing recipe chrome-pdf
debug
+264
Converting with chrome Chrome/131.0.6778.69 using chrome-pool strategy
debug
+61
Page request: GET (document) file:///tmp/jsreport/autocleanup/bf9fc695-844d-4ca1-acde-19b422ec2073-chrome-pdf.html
debug
+49
Page request finished: GET (document) 200 file:///tmp/jsreport/autocleanup/bf9fc695-844d-4ca1-acde-19b422ec2073-chrome-pdf.html
debug
+8
Running chrome with params {"printBackground":false,"format":"A4","marginRight":"0","marginBottom":"0","marginLeft":"0","timeout":18366,"margin":{"right":"0","bottom":"0","left":"0"}}
info
+72
pdf-utils is starting pdf processing
debug
+1
pdf-utils detected 0 pdf operation(s) to process
debug
+0
pdf-utils postprocess start
debug
+13
pdf-utils postprocess end
info
+2
pdf-utils pdf processing was finished
info
+0
Rendering (child) request finished in 2103 ms
warn
+4
Error when processing render request 3
(because) error while executing pdf-utils operations
(because) cannot read properties of undefined (reading 'object')
TypeError: Cannot read properties of undefined (reading 'object')
```

@pofider As you can see there are 0 operations detected, I am not sure what I missing from the code example to trigger the merge
```
pdf-utils detected 0 pdf operation(s) to process
```

**Comment by pofider** [comment]
Hm, not for me, I get it right with
```
info +45 pdf-utils is starting pdf processing
debug +70 pdf-utils detected 1 pdf operation(s) to process
debug +5 pdf-utils running pdf operation merge
info +0 Starting rendering (child) request
```

Please try to create a repo where you do this so we are the same.

**Comment by jorisdebock** [comment]
@pofider ok apparently it is caused by the new chrome version 131 (on linux)

I made a repo with dockerfile to reproduce the issue 
https://github.com/jorisdebock/jsreport-issue-1189

I am not sure if it is a bug in the new version of chrome or something has changed. I will pin my chrome version to 130 for now.

**Comment by pofider** [comment]
Thank you, yes I can replicate it with the new chrome.
Unfortunately, they have changed the tagging approach which we will need to adapt to.
We will be working on it...

**Comment by pofider** [comment]
I've pushed the fix for working with Chrome 131 tagging approach.
It will be part of the next jsreport release...

Thank you for revealing this.
