### ISSUE TITLE
Unsupported provider mongoDB

### ISSUE THREAD

**Issue by masalinas** [jsreport/jsreport#134]
1) I installed jsreport OnPremise
2) I created a prod.config.json file and configure to use mongodb:
{
    "certificate": {
        "key": "certificates/jsreport.net.key",    
        "cert": "certificates/jsreport.net.cert"
    },
    "connectionString": { "name": "mongoDB", "address": "localhost", "port": 27017, "databaseName" : "tachoexplorer"},
    "extensions": ["excel-parser", "express", "templates", "html", "phantom-pdf", "scripts", "data", "images", "statistics", "reports", "childTemplates", "sample-template"],    
    "httpsPort": 443,
    "blobStorage": "fileSystem",
    "cluster": {
      "numberOfWorkers": 2,
      "enabled":  false
    },
    "phantom": {
        "numberOfWorkers" : 2,
        "timeout": 180000
    },
    "tasks": {
        "numberOfWorkers" : 2,
        "timeout": 10000
    }
}

3) When start jsreport from npm start I obttain this error:

2015-10-19T14:48:54.468Z - info: Extensions loaded.
2015-10-19T14:48:54.470Z - error: Error occured during reporter init Error: Unsupported provider mongoDB
    at DocumentStore.init (/opt/jsreport/lib/store/documentStore.js:44:15)
    at /opt/jsreport/lib/reporter.js:102:35
From previous event:
    at Reporter._init (/opt/jsreport/lib/reporter.js:105:8)
    at Reporter.init (/opt/jsreport/lib/reporter.js:80:17)
    at Bootstrapper._createReporter (/opt/jsreport/lib/bootstrapper.js:167:26)
    at /opt/jsreport/lib/bootstrapper.js:110:23

What is wrong??

Regards.

**Comment by pofider** [comment]
I guess you did install jsreport from the github master, right? There are some changes which were not documented and finalized yet. You should rather use the latest release tag or npm.

However to make it running you need to do
`npm install jsreport-mongodb-store`
and add 
`mongodb-store` to the list of extensions in `prod.config.json`

**Comment by masalinas** [comment]
thanks for the response but know I obtain this:

2015-10-19T15:42:28.080Z - info: connecting to mongo mongodb://localhost:27017/undefined
2015-10-19T15:42:28.400Z - info: Creating default express app.
2015-10-19T15:42:28.991Z - error: Error when starting http server on port 443 Error: listen EACCES
...

I configured the database name with 
"connectionString": { "name": "mongoDB", "address": "localhost", "port": 27017, "databaseName" : "tachoexplorer"},

but that you see the system tell me: 
2015-10-19T15:42:28.080Z - info: connecting to mongo mongodb://localhost:27017/undefined

What is the problem ??

Regards

**Comment by masalinas** [comment]
Is resolved the problem is that I started expressJs without sudo user and I can not access port under1024 so I started under 2000 port for example, but the log that is conecting to mongodb://localhost:27017/undefined maybe is not correct, why this log is I configured the database in the prod.config.json???

**Comment by pofider** [comment]
Ignore the message in the log for this. It is a bug which needs to be fixed.

Or you can extend the connection string with `connectionString: { "authDb": "tachoexplorer", .... }` and you should be fine.

**Comment by masalinas** [comment]
Do you have any correct settings example (prod.config.json) for mongod, because I don't see any document where explain that, also I don't know how many extensions I must to configure, so I dont know how configure jsreport for mongodb ...

The system start correctly:
2015-10-19T16:00:07.912Z - info: jsreport server successfully started on https port: 2000

But when try to connect to exist any web ... without prod.config.json the system starts of
course.


Regards

**Comment by pofider** [comment]
> But when try to connect to exist any web ...
What do you mean?

You should be able to reach jsreport on `https://localhost:2000` then, is it working?

You can also remove the `extensions` entry from the config file to apply all found extensions.

I would suggest following the [official download instruction](http://jsreport.net/downloads/) and [configuration documentation](http://jsreport.net/learn/configuration).

**Comment by masalinas** [comment]
Already start jsreport with the mongodb string, now how can i create a query data against my mongo collections??

**Comment by pofider** [comment]
Oh, you want to use the mongodb as the data source for the reports?

In this case check this one
[jsreport-contrib-mongodb](https://github.com/jsreport/jsreport-contrib-mongodb)

**Comment by masalinas** [comment]
Ok thanks, I'll try it ...
