### ISSUE TITLE
jsreport-mongodb-store  in  jsreport  0.11.0

### ISSUE THREAD

**Issue by iu3564** [jsreport/jsreport#163]
I got error in this version : 
```
 Error occured - Error during rendering report: Unsupported module mongodb
Stak - Error: Unsupported module mongodb
```
But on 0.10.1 all normally
Need fix
10x for help

**Comment by pofider** [comment]
Thanks. We will check that. Here is the full stack for the reference

```
Error occured - Error during rendering report: Unsupported module mongodb
Stak - Error: Unsupported module mongodb
    at ChildProcess.<anonymous> (C:\temp11\node_modules\script-manager\lib\manager-processes.js:38:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
From previous event:
    at toCb (C:\temp11\node_modules\jsreport-core\lib\reporter.js:120:21)
    at null.<anonymous> (C:\temp11\node_modules\jsreport-core\lib\reporter.js:133:5)
    at C:\temp11\node_modules\toner\lib\listeners.js:42:12
    at Array.forEach (native)
    at collection.fire (C:\temp11\node_modules\toner\lib\listeners.js:28:9)
    at Toner.render (C:\temp11\node_modules\toner\lib\toner.js:107:24)
```

**Comment by bjrmatos** [comment]
if i'm not wrong is because `mongodb` is not listed in [this line](https://github.com/jsreport/jsreport-scripts/blob/master/lib/scripts.js#L24)

**Comment by pofider** [comment]
@iu3564 Do you have a custom script which is doing `require(mongodb)` ? This should intentionally throw the mentioned error when the `mongodb` module is not listed in the config `scripts.allowedModules: [ 'mongodb'... ]`. I was not able to find a change in 0.11 release which would change this behavior, so we need to take it from the other way.

@bjrmatos It is intentionally not there for a long time.

**Comment by pofider** [comment]
Closing due to inactivity.
