### ISSUE TITLE
static-resources errors out when running scheduled report

### ISSUE THREAD

**Issue by jcfergus** [jsreport/jsreport#167]
It looks like the static-resources module attempts to use req.url, and so errors out when a report is being run through the scheduler.  (Regardless of whether that report actually -uses- static-resources.)

```
2016-01-17T02:46:55.357Z - info: Starting rendering request 1 (user: undefined)
2016-01-17T02:46:55.370Z - debug: Data item not defined for this template.
2016-01-17T02:46:55.370Z - info: Rendering template {shortid:E1tHW80We, recipe:xlsx,engine:jsrender}
2016-01-17T02:46:55.375Z - debug: Executing script 4JEdQokZg
2016-01-17T02:46:57.748Z - error: Error when processing render request Error during rendering report: Cannot read property 'replace' of undefined TypeError: Cannot read property 'replace' of undefined
    at resolveStaticResourcesPath (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport-static-resources/lib/staticResources.js:25:29)
    at Function.<anonymous> (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport-static-resources/lib/staticResources.js:33:36)
    at /Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/listener-collection/lib/listenerCollection.js:172:41
    at /Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/listener-collection/lib/listenerCollection.js:151:24
From previous event:
    at /Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/listener-collection/lib/listenerCollection.js:149:53
    at Array.map (native)
    at mapSeries (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/listener-collection/lib/listenerCollection.js:148:28)
    at ListenerCollection.fire (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/listener-collection/lib/listenerCollection.js:167:16)
    at null.<anonymous> (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/lib/reporter.js:129:43)
    at /Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/toner/lib/listeners.js:42:12
    at Array.forEach (native)
    at collection.fire (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/toner/lib/listeners.js:28:9)
    at Toner.render (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/toner/lib/toner.js:107:24)
2016-01-17T02:46:57.749Z - debug: Processing schedule user-report-test failed with :TypeError: Cannot read property 'replace' of undefined
    at resolveStaticResourcesPath (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport-static-resources/lib/staticResources.js:25:29)
    at Function.<anonymous> (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport-static-resources/lib/staticResources.js:33:36)
    at /Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/listener-collection/lib/listenerCollection.js:172:41
    at /Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/listener-collection/lib/listenerCollection.js:151:24
From previous event:
    at /Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/listener-collection/lib/listenerCollection.js:149:53
    at Array.map (native)
    at mapSeries (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/listener-collection/lib/listenerCollection.js:148:28)
    at ListenerCollection.fire (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/listener-collection/lib/listenerCollection.js:167:16)
    at null.<anonymous> (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/lib/reporter.js:129:43)
    at /Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/toner/lib/listeners.js:42:12
    at Array.forEach (native)
    at collection.fire (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/toner/lib/listeners.js:28:9)
    at Toner.render (/Users/justinferguson/IdeaProjects/CSTools-JS/node_modules/jsreport/node_modules/jsreport-core/node_modules/toner/lib/toner.js:107:24)
```

**Comment by pofider** [comment]
[jsreport-static-resources](https://github.com/jsreport/jsreport-static-resources/) are resolving the resources path based on the running request host headers. This is not available in the scheduled job and that is why it crashes.

We need to resolve that static resource path upfront.

Solution
I changed it now to just log warning when the static resources path is not resolved. 
Published in jsreport-static-resources@0.2.2
