### ISSUE TITLE
JS Report timing out with scripts. 

### ISSUE THREAD

**Issue by carlskii** [jsreport/jsreport#205]
Hi,

I'm using a script to read a JSON file like this: 

```javascript
fs = require('fs');
path = require('path');

function beforeRender(done) {
    var data = fs.readFileSync(path.join('/Users/cbourne/Development/jsreport-new', 'scratch2.json').toString(), 'utf8');
    json = JSON.parse(data);
        console.log(json);
       request.data = json;
   done();
}


Based on this sample data: 

```json
{
  "endpoints": [
    {
      "alpn": false,
      "certificates": [
        {
          "certificate": "gtutututtuityiutiutiutiut",
          "fingerprint": "f57330aa25f5354c7720da219e64b2fd4335ade1"
        },
        {
          "certificate": "gjgjkgkjgjkghjghkggkgkjgkjgkjgkjgkjgkjg",
          "fingerprint": "ed9389ea4f4171711f476828437caea93d38a6ce"
        }
      ],
      "clientRenegotiation": false,
      "heartbleed": false,
      "host": "5757657",
      "hsts": false,
      "ip": "445454",
      "npm": false,
      "poodle": false,
      "poodleTls": false,
      "port": 443,
      "protocols": [
        {
          "certificates": [
            "f57330aa25f5354c7720da219e64b2fd4335ade1",
            "ed9389ea4f4171711f476828437caea93d38a6ce"
          ],
          "ciphers": [
            "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
            "TLS_RSA_WITH_AES_128_CBC_SHA",
            "TLS_RSA_WITH_AES_256_CBC_SHA"
          ],
          "protocol": "TLSv1"
        }
      ],
      "secureRenegotiation": false
    },
    {
      "alpn": false,
      "certificates": [
        {
          "certificate": "ghghghgh"
        },
        {
          "certificate": "nbnbnbnbnbnbnb"
        },
        {
          "certificate": "ghgh"
        }
      ],
      "clientRenegotiation": false,
      "heartbleed": false,
      "host": "yyyy",
      "hsts": false,
      "ip": "1234",
      "npm": false,
      "poodle": false,
      "poodleTls": false,
      "port": 443,
      "protocols": [
        {
          "certificates": [
            "3a3f2558983937a53e728a1398d37c1f48731ecf",
            "9cd5ec79ab611a1b69cdc00ab59f92324736708f",
            "1a8a9158e3fdc3227614332304611ef70cefad55"
          ],
          "ciphers": [
            "TLS_RSA_WITH_AES_128_CBC_SHA",
            "TLS_RSA_WITH_AES_256_CBC_SHA"
          ],
          "protocol": "TLSv1"
        }
      ],
      "secureRenegotiation": false
    }
  ]
}
```
and this template:

```html
{{#endpoints}}
		<li>{{alpn}}
			<ul>
				{{#certificates}}
					<li>{{fingerprint}}</li>
					<li>{{certificate}}</li>
				{{/certificates}}
			</ul>
			<ul>
			
			</ul>
		</li>
	{{/endpoints}}
</ul>
``` 

JSreport times out with this message: 

```bash
Error occured - Error during rendering report: Timeout error during executing script
Stak - Error: Timeout error during executing script
    at Timeout._onTimeout (/Development/jsreport-new/node_modules/script-manager/lib/manager-processes.js:67:12)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
From previous event:
From previous event:
    at /Development/jsreport-new/node_modules/jsreport-core/lib/render/render.js:141:54
    at _fulfilled (/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/Users/cbourne/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:756:13)
    at /Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:564:44
    at flush (/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:110:17)
```

Interestingly if I remove the `<li>{{certificate}}</li>` from the template it seems to work. OK

I tested my template outside of reportjs and the output looks like this si I don't think its a Handlebars related issue.

```html
		<li>false
			<ul>
					<li>f57330aa25f5354c7720da219e64b2fd4335ade1</li>
					<li>gtutututtuityiutiutiutiut</li>
					<li>ed9389ea4f4171711f476828437caea93d38a6ce</li>
					<li>gjgjkgkjgjkghjghkggkgkjgkjgkjgkjgkjgkjg</li>
			</ul>
			<ul>
			
			</ul>
		</li>
		<li>false
			<ul>
					<li></li>
					<li>ghghghgh</li>
					<li></li>
					<li>nbnbnbnbnbnbnb</li>
					<li></li>
					<li>ghgh</li>
			</ul>
			<ul>
			
			</ul>
		</li>
</ul>
```

**Comment by pofider** [comment]
I've tried this and it works fine for me. Do you run this in the jsreport studio?

Does the console.log from the script actually prints something?

**Comment by carlskii** [comment]
Yes, this is running it in studio. 

Console output:

```bash
2016-04-09T11:02:50.630Z - error: Error when processing render request Error during rendering report: Timeout error during executing script Error: Timeout error during executing script
    at Timeout._onTimeout (/Users/cbourne/Development/jsreport-new/node_modules/script-manager/lib/manager-processes.js:67:12)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
From previous event:
From previous event:
    at /Users/cbourne/Development/jsreport-new/node_modules/jsreport-core/lib/render/render.js:141:54
    at _fulfilled (/Users/cbourne/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/Users/cbourne/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/Users/cbourne/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:756:13)
    at /Users/cbourne/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:564:44
    at flush (/Users/cbourne/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:110:17) requestId=46
2016-04-09T11:02:50.633Z - error: Error during processing request: https://localhost:8443/api/report?studio=normal details: Error during rendering report: Timeout error during executing script Error: Timeout error during executing script
    at Timeout._onTimeout (/Users/cbourne/Development/jsreport-new/node_modules/script-manager/lib/manager-processes.js:67:12)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
From previous event:
From previous event:
    at /Users/cbourne/Development/jsreport-new/node_modules/jsreport-core/lib/render/render.js:141:54
    at _fulfilled (/Users/cbourne/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/Users/cbourne/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/Users/cbourne/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:756:13)
    at /Users/cbourne/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:564:44
    at flush (/Users/cbourne/Development/jsreport-new/node_modules/listener-collection/node_modules/q/q.js:110:17)
```

**Comment by carlskii** [comment]
OK so I did a bit more investigation here and it seems to be because my data file is fairly large and contains dome very long strings. If I use jsreport-core to create the report it works OK, although it does take a little while to run. JSReport studio is timing out based on the volume of data.

**Comment by pofider** [comment]
Thanks for investigation.

So maybe the solution for you is to increase timeout for scripts in the configuration ?

```js
scripts: {
  timeout: 30000
  allowedModules: "*"
}
```

**Comment by carlskii** [comment]
Thanks - I just tried that bit unfortunately it made no difference.

**Comment by pofider** [comment]
And did it took 30 seconds before timing out? Maybe you need to put there higher timeout.

**Comment by carlskii** [comment]
Its actually timing out after approx 70 second.

**Comment by pofider** [comment]
Current status here is that a script which runs fine (but takes 25s) to finish is timing out in jsreport studio?

Do you have same `tasks.strategy` setting on both environments? Maybe you can try new `in-memory` strategy for highest speed for data transfers

```js
"tasks": {
        "strategy": "in-process",      
    },
```

Some info about it is here http://jsreport.net/blog/running-scripts-and-helpers-in-main-process

**Comment by pofider** [comment]
Closing due to inactivity. Please reopen if you have additional inputs to this.
