### ISSUE TITLE
Error during processing request: /api/report details: Unexpected identifier SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by CuReSoft** [jsreport/jsreport#208]
Hi there, im getting an error during report render.

Error during processing request: /api/report details: Unexpected identifier SyntaxError: Unexpected identifier

```
at Object.exports.runInNewContext (vm.js:48:16)
    at module.exports (/root/node_modules/jsreport-scripts/lib/scriptEvalChild.js:116:6)
    at process.<anonymous> (/root/node_modules/script-manager/lib/worker-processes.js:30:38)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
```

I invoke the render process trough remote client like so:
```js
var da = {

                "template": {
                    "shortid": "71gKkMMQl",
                    "phantom": {
                        "margin": '1 cm',
                        "header": settings['header'],
                        "footer": settings.footer,
                        "headerHeight": '2 cm',
                        "footerHeight": '3 cm',
                        "format": "A4",
                        "orientation": "landscape",
                    }
                },
			  "data": {
				"dataJson": rdata
			  },
            }

reportclient.render(da,function(err, response){

                if (err) {
                    return console.error('upload failed:', err);
                }

			response.pipe(fs.createWriteStream('/var/www/reports/'+newReport.file))
```

**Comment by pofider** [comment]
I guess you should set data directly to `data` property instead of using `data.dataJson`

http://jsreport.net/learn/nodejs-client
> ```js
client.render({
    template: { content: "hello {{:someText}}", recipe: "html",
                engine: "jsrender" },
    data: { someText: "world!!" }
}, function(err, response) {
    response.body(function(body) {
        //prints hello world!!
        console.log(body.toString());
    });
});
```
