### ISSUE TITLE
Error occured - Engine 'handlebars' not found

### ISSUE THREAD

**Issue by jamiros** [jsreport/jsreport#210]
Hello!
I have been trying to install the jsreport server for awhile now and I think I already have some progress. The only problem I'm seeing is when I try to preview the report I get the following error:

```
Error occured - Engine 'handlebars' not found
Stak - Error: Engine 'handlebars' not found
    at invokeRender (/var/www/html/reporting/node_modules/jsreport-core/lib/render/render.js:74:11)
    at /var/www/html/reporting/node_modules/jsreport-core/lib/render/render.js:141:12
    at _fulfilled (/var/www/html/reporting/node_modules/listener-collection/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/var/www/html/reporting/node_modules/listener-collection/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/var/www/html/reporting/node_modules/listener-collection/node_modules/q/q.js:756:13)
    at /var/www/html/reporting/node_modules/listener-collection/node_modules/q/q.js:564:44
    at flush (/var/www/html/reporting/node_modules/listener-collection/node_modules/q/q.js:110:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Is this a bug? or still lack of configuration?

Thanks!

**Comment by pofider** [comment]
Hi,

do you use full `jsreport` package or kind of a custom installation using `jsreport-core`?
can you find `jsreport-handlebars` in the `node_moduels`?
Can you share your jsreport startup code and config file?

**Comment by jamiros** [comment]
Hello pofider,

I'm using the ```jsreport``` package and following the instructions on the page to install. The ones under UNIX and also doing the extra steps for Ubuntu.
I can see the ```jsreport-handlebars``` in the folder: http://prntscr.com/aunsm3
**Here's the startup script: **http://prntscr.com/aunto4
```
/var/www/html/reporting$ sudo npm start --production

> jsreport-server@ start /var/www/html/reporting
> node server.js

2016-04-20T16:25:14.203Z - info: Initializing jsreport in production mode using configuration file prod.config.json
2016-04-20T16:25:15.767Z - info: Searching for available extensions in /var/www/html/reporting/
2016-04-20T16:25:16.193Z - info: Found 30 extensions
2016-04-20T16:25:16.276Z - info: Using extension express
2016-04-20T16:25:17.141Z - info: Using extension templates
2016-04-20T16:25:17.211Z - info: Using extension phantom-pdf
2016-04-20T16:25:17.461Z - info: Using extension scripts
2016-04-20T16:25:17.472Z - info: Using extension data
2016-04-20T16:25:17.483Z - info: Using extension images
2016-04-20T16:25:17.513Z - info: Using extension statistics
2016-04-20T16:25:17.522Z - info: Using extension reports
2016-04-20T16:25:17.532Z - info: Using extension sample-template
2016-04-20T16:25:17.542Z - info: Extensions loaded.
2016-04-20T16:25:17.684Z - info: Creating memory store
2016-04-20T16:25:17.832Z - info: Creating default express app.
2016-04-20T16:25:18.276Z - info: jsreport server successfully started on https port: 8080
2016-04-20T16:25:18.316Z - info: reporter initialized
```

**And here's the config file:**
_prod.config.json_
```
{
    "certificate": {
        "key": "certificates/jsreport.net.key",
        "cert": "certificates/jsreport.net.cert"
    },
    "connectionString": { "name": "fs" },
    "extensions": ["express", "templates", "phantom-pdf", "scripts", "data", "images", "statistics", "rep$
    "httpsPort": 8080,
    "appPath": "/reporting",
    "blobStorage": "fileSystem",
    "phantom": {
        "numberOfWorkers" : 2,
        "timeout": 180000
    },
    "tasks": {
        "numberOfWorkers" : 2,
        "timeout": 10000,
        "strategy": "http-server"
    }
}
```

**Comment by pofider** [comment]
Hi,

this line in the config is likely the problem

```
 "extensions": ["express", "templates", "phantom-pdf", "scripts", "data", "images", "statistics", "rep$
```

This tells jsreport to include only the particular named extensions. And I see there is no `handlebars` mentioned. You need to remove this line from the config or include `handlebars` in.

**Comment by jamiros** [comment]
Hello!

The error is gone and now the following is shown:
```
npm ERR! Linux 3.19.0-49-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--production"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! jsreport-server@ start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsreport-server@ start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jsreport-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jsreport-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jsreport-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/reporting/npm-debug.log
```

**Here's the npm-debug.log:**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--production' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle jsreport-server@~prestart: jsreport-server@
6 silly lifecycle jsreport-server@~prestart: no script for prestart, continuing
7 info lifecycle jsreport-server@~start: jsreport-server@
8 verbose lifecycle jsreport-server@~start: unsafe-perm in lifecycle true
9 verbose lifecycle jsreport-server@~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/var/www/html/reporting/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle jsreport-server@~start: CWD: /var/www/html/reporting
11 silly lifecycle jsreport-server@~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle jsreport-server@~start: Returned: code: 1  signal: null
13 info lifecycle jsreport-server@~start: Failed to exec start script
14 verbose stack Error: jsreport-server@ start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid jsreport-server@
16 verbose cwd /var/www/html/reporting
17 error Linux 3.19.0-49-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--production"
19 error node v5.10.1
20 error npm  v3.8.3
21 error code ELIFECYCLE
22 error jsreport-server@ start: `node server.js`
22 error Exit status 1
23 error Failed at the jsreport-server@ start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the jsreport-server package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs jsreport-server
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls jsreport-server
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Any help or pointing to the right direction will help. Thank you!

**Comment by pofider** [comment]
The look output looks ok, don't know why the output is not displayed in the browser. 

Please check what is happening with the request in chrome developer tools -> network
Also you may try to run without https. (Change the httpsPort: 8080 in your config to httpPort: 8080)

**Comment by jamiros** [comment]
Hey ther pofider!

Just went and checked with ```https``` and this is the network error that I'm getting:
```
POST https://testsite.com:8080/api/report?studio=normal net::ERR_CONNECTION_REFUSED(anonymous function)
main.js?bust=1456080632283&studio=normal:357 @ main.js?
bust=1456080632283&studio=normal:357(anonymous function) @ app_built.js
bust=1456080632283&studio=normal:486ViewBase.extend.onReportRender @ main.js
bust=1456080632283&studio=normal:181(anonymous function) @ app_built.js
bust=1456080632283&studio=normal:486s @ app_built.js
bust=1456080632283&studio=normal:486e.eachSeries @ app_built.js
bust=1456080632283&studio=normal:486n.fire @ app_built.js
bust=1456080632283&studio=normal:486fn @ main.js
bust=1456080632283&studio=normal:310LayoutBase.extend._preview @ main.js
bust=1456080632283&studio=normal:466LayoutBase.extend.preview @ main.js
bust=1456080632283&studio=normal:462(anonymous function) @ main.js
bust=1456080632283&studio=normal:392c @ app_built.js
bust=1456080632283&studio=normal:486o.Events.trigger @ app_built.js
bust=1456080632283&studio=normal:486LayoutBase.extend.triggerPreview @ main.js
bust=1456080632283&studio=normal:235w.event.dispatch @ app_built.js
bust=1456080632283&studio=normal:486y.handle @ app_built.js
bust=1456080632283&studio=normal:486
```

Removed ```https``` and used ```http``` in the ```prod.config.json``` file and I got this:

```
POST http://testsite.com:8080/api/report?studio=normal net::ERR_CONNECTION_REFUSED(anonymous function)
main.js?bust=1456080632283&studio=normal:357 @ main.js
bust=1456080632283&studio=normal:357(anonymous function) @ app_built.js
bust=1456080632283&studio=normal:486ViewBase.extend.onReportRender @ main.js
bust=1456080632283&studio=normal:181(anonymous function) @ app_built.js
bust=1456080632283&studio=normal:486s @ app_built.js
bust=1456080632283&studio=normal:486e.eachSeries @ app_built.js
bust=1456080632283&studio=normal:486n.fire @ app_built.js
bust=1456080632283&studio=normal:486fn @ main.js
bust=1456080632283&studio=normal:310LayoutBase.extend._preview @ main.js
bust=1456080632283&studio=normal:466LayoutBase.extend.preview @ main.js
bust=1456080632283&studio=normal:462(anonymous function) @ main.js
bust=1456080632283&studio=normal:392c @ app_built.js
bust=1456080632283&studio=normal:486o.Events.trigger @ app_built.js
bust=1456080632283&studio=normal:486LayoutBase.extend.triggerPreview @ main.js
bust=1456080632283&studio=normal:235w.event.dispatch @ app_built.js
bust=1456080632283&studio=normal:486y.handle @ app_built.js
bust=1456080632283&studio=normal:486
```

Is ```report``` coming from somewhere that I need to give access to that is not under the ```/reporting``` folder where I installed everything? Is this s server config/permissions thing?

I ran all the commands under this folder ```/var/www/html/reporting``` and here's where I run the server.

Thank you for all your help! 

**Side note....** : I downloaded the windows version and ran it on my machine and it's working properly. Just to make sure. So there might be something on the Ubuntu side that might be breaking the installation.

**Comment by pofider** [comment]
Is there a reason why you have `  "appPath": "/reporting",` in the config?

**Comment by jamiros** [comment]
The folder ```/reporting``` is where I have these files and the install:

```
data             jsreport-temp  node_modules   package.json      server.js
dev.config.json  logs           npm-debug.log  prod.config.json
```

The studio and everything is under this url: ```http://testsite.com/reporting```

And i read this in the configuration details in the page:

appPath (string) - optionally set application path, if you run application on http://appdomain.com/reporting then set /reporting to appPath

I will remove it and see what happens.

**Comment by pofider** [comment]
Strange that the POST goes to `https://testsite.com:8080/api/report` and not to `https://testsite.com:8080/reporting/api/report`

You have some kind of a web server in-front of jsreport?

**Comment by jamiros** [comment]
Not that I know of but this is how it's configured:

```/var/www/html/``` is where the main page is. php site with some info.
```/var/www/html/<anything>``` there are other sites or tools
```/var/www/html/reporting``` is where I'm installing jsreport

I have CNAMEs that point to those folders in some cases like test.sitename.com and the folder can also be accessed through sitename.com/test.

All of this is running in a single web-server though...

Is there a place specifically where I should add the ```appPath``` configuration?

**Comment by pofider** [comment]
I've tried again the similar case and it works for me well.

To summary your issue:
1. you open jsreport in browser on `https://testsite.com:8080/reporting` and it opens studio well
2. when you run the report preview in studio, it tries to do POST on `https://testsite.com:8080/api/report` which won't reach jsreport server, because it your CName is directing only requests on `/reporting` to jsreport server.

The question is why the post runs to `https://testsite.com:8080/api/report` when jsreport is doing 
POST `api/report` (note missing / at the beginning) which should just append `api/report` to the current url, which is `https://testsite.com:8080/reporting`

**Comment by jamiros** [comment]
Is it taking the ```appPath``` configuration item? I'm going to install directly to the main folder and see what it does.

**Comment by pofider** [comment]
`appPath` is used in the login authentication screen only. The rest of the application works relatively and it doesn't need `appPath`.

**Comment by jamiros** [comment]
I added jsreport to the main folder and it still has the same problem. I'm going to create another VM and see if I can solve this. The problem is the configuration that we're using on the web server.

**Comment by pofider** [comment]
Closing due to inactivity.
