### ISSUE TITLE
Error Ocurred - Error during rendering report

### ISSUE THREAD

**Issue by AlexSayHello** [jsreport/jsreport#216]
Hello, I am using JsReport Node.js on Ubuntu Server.
When I try to create a report on JsReport Studio, the platform returns me the following error.

```
Error occured - Error during rendering report: Command failed: /home/alejandro/prueba/node_modules/jsreport/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /home/alejandro/prueba/node_modules/jsreport/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /home/alejandro/prueba/jsreport-temp/b24d2620-1cce-11e6-9bea-310cb0287f25settings.html
/home/alejandro/prueba/node_modules/jsreport/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/node_modules/phantomjs/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

Stak - Error: Command failed: /home/alejandro/prueba/node_modules/jsreport/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /home/alejandro/prueba/node_modules/jsreport/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /home/alejandro/prueba/jsreport-temp/b24d2620-1cce-11e6-9bea-310cb0287f25settings.html
/home/alejandro/prueba/node_modules/jsreport/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/node_modules/phantomjs/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at /home/alejandro/prueba/node_modules/jsreport/node_modules/jsreport-core/lib/render/render.js:141:54
```

**Comment by pofider** [comment]
This is what I usually run on ubuntu to make phantomjs working:

```sh
sudo apt-get install build-essential chrpath git-core libssl-dev libfontconfig1-dev
```

It is mentioned in the download instructions.

**Comment by AlexSayHello** [comment]
Ok thanks, solved. Sorry, I'm new.

**Comment by JulioLopezN** [comment]
I have the same problem but I'm running on windows 10 with electron

```
Error during rendering report: Command failed: E:\Proyectos\Electron\UTEFI\dist\win-unpacked\resources\app.asar.unpacked\node_modules\phantomjs\lib\phantom\phantomjs.exe --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any E:\Proyectos\Electron\UTEFI\dist\win-unpacked\resources\app.asar\node_modules\jsreport-phantom-pdf\node_modules\phantom-html-to-pdf\lib\scripts\standaloneScript.js C:\Users\JULIOL~1\AppData\Local\Temp\jsreport-temp\b473bdd0-791f-11e6-a1e2-25cfb98b782esettings.html
Can't open 'E:\Proyectos\Electron\UTEFI\dist\win-unpacked\resources\app.asar\node_modules\jsreport-phantom-pdf\node_modules\phantom-html-to-pdf\lib\scripts\standaloneScript.js'
```

**Comment by mohameds-ismail** [comment]
Im getting this error also?

**Comment by mguachimboza** [comment]
Help please I'm new to this
Hello, I am using JsReport Node.js on Centos 7 Server.

When I try to create a report on JsReport Studio, the platform also returns me the same error.

Error occured - Error during rendering report: spawn /var/www/html/jsReport/node_modules/phantomjs/lib/phantom\phantomjs.exe ENOENT
Stak - Error: spawn /var/www/html/jsReport/node_modules/phantomjs/lib/phantom\phantomjs.exe ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
