### ISSUE TITLE
Supplying dataDirectory to config file causes jsreport not to start as service

### ISSUE THREAD

**Issue by jmorrisIII** [jsreport/jsreport#224]
I am trying to run  jsreport as a server in ubuntu. This works until I supply a dataDirectory in my config file. When I restart my server jsreport is not running at all. If I start jsrepot manually with "sudo npm start --production" it starts and uses the location I provide in the config file.

jsreport.conf file
```
start on startup
chdir /srv/jsReport
exec sudo npm start --production
```
prod.config.json file
```
{
    "certificate": {
        "key": "certificates/jsreport.net.key",    
        "cert": "certificates/jsreport.net.cert"
    },
    "connectionString": { "name": "fs" },
    "httpPort": 5000,
    "blobStorage": "fileSystem",
    "dataDirectory":"/inv/winshare/H/Inv-DOCS/jsreport",
    "phantom": {
        "numberOfWorkers" : 2,
        "timeout": 180000
    },
    "tasks": {
        "numberOfWorkers" : 2,
        "timeout": 10000
    }
}

**Comment by pofider** [comment]
Can you check the logs?

The jsreport log should be in /srv/jsReport/logs
also ubuntu should log the startup script output somewhere like `/var/log/upstart/`

**Comment by jmorrisIII** [comment]
Here is the /var/log/upstart/jsreport.log file contents.

```
sudo: unable to resolve host (none)

> jsreport-server@ start /srv/jsReport
> node server.js

2016-06-21T16:10:40.409Z - [32minfo[39m: Initializing jsreport in production mode using configuration file prod.config.json
2016-06-21T16:10:40.412Z - [32minfo[39m: Setting process based strategy for rendering. Please visit http://jsreport.net/learn/configuration for information how to get more performance.
2016-06-21T16:10:40.417Z - [31merror[39m: Error occured during reporter init Error: EROFS: read-only file system, mkdir '/inv/winshare/H/Inv-DOCS'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at sync (/srv/jsReport/node_modules/jsreport/node_modules/jsreport-core/node_modules/mkdirp/index.js:70:13)
    at sync (/srv/jsReport/node_modules/jsreport/node_modules/jsreport-core/node_modules/mkdirp/index.js:76:24)
    at Function.sync (/srv/jsReport/node_modules/jsreport/node_modules/jsreport-core/node_modules/mkdirp/index.js:76:24)
    at new module.exports (/srv/jsReport/node_modules/jsreport/node_modules/jsreport-core/lib/blobStorage/fileSystemBlobStorage.js:14:12)
    at /srv/jsReport/node_modules/jsreport/node_modules/jsreport-core/lib/reporter.js:68:28
From previous event:
    at /srv/jsReport/node_modules/jsreport/node_modules/jsreport-core/lib/reporter.js:78:8
From previous event:
    at Reporter.init (/srv/jsReport/node_modules/jsreport/node_modules/jsreport-core/lib/reporter.js:57:30)
    at Reporter.reporter.init (/srv/jsReport/node_modules/jsreport/lib/extendInit.js:8:21)
    at Object.<anonymous> (/srv/jsReport/server.js:1:85)

**Comment by pofider** [comment]
It looks like a permission issue, `sudo npm start` seems to doesn't have a desired effect.

I'm not very good in linux stuff, however you likely need to create a user, give him owner permission to the data directory and run the npm start with it. 

I'm gonna try this later, if you won't come with a solution for this. If you make it working, please share your solution.

**Comment by jmorrisIII** [comment]
I'm not good at linux stuff either. I think you are correct about it being a permissions issue. I am not sure why it works if I "sudo npm start --production". The log reports "initializing fs storage at /inv/winshare/H/Inv-DOCS/jsreport". But when I try as a service it fails.

**Comment by pofider** [comment]
I tried myself on the freshly installed ubuntu VM. I didn't encounter the mentioned problem and I was able to start service with dataDirectory in the server root.

Please consult your issue with a linux guy, this is likely not related to jsreport.
