### ISSUE TITLE
500 Internal server error 

### ISSUE THREAD

**Issue by samir-kamble** [jsreport/jsreport#278]
Hello, 

I am getting 500 internal server error when calling API from Postman. Following is the response I am getting.

`{"message":"Unexpected token -","stack":"SyntaxError: Unexpected token -\n    at parse (C:\\Program Files\\nodejs\\node_modules\\jsreport\\node_modules\\body-parser\\lib\\types\\json.js:83:15)\n    at C:\\Program Files\\nodejs\\node_modules\\jsreport\\node_modules\\body-parser\\lib\\read.js:116:18\n    at invokeCallback (C:\\Program Files\\nodejs\\node_modules\\jsreport\\node_modules\\raw-body\\index.js:262:16)\n    at done (C:\\Program Files\\nodejs\\node_modules\\jsreport\\node_modules\\raw-body\\index.js:251:7)\n    at IncomingMessage.onEnd (C:\\Program Files\\nodejs\\node_modules\\jsreport\\node_modules\\raw-body\\index.js:307:7)\n    at emitNone (events.js:86:13)\n    at IncomingMessage.emit (events.js:186:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)"}`

Following is my input JSON for report generation.

` //Template id Excel or PDF depends on this id [To be made Dynamic]
          "template": { "shortid" : "SkbquQk7Fl"  },
         
          //=======Report data JSON to be passed here============//
          "data" : { 
                "books": [
                  {"name": "A Tale of Three Cities", "author": "Samir Kamble", "sales": 351}
                ]
           },
           //=========Timeout option================//
          "options": { 
            "timeout": 60000,
            "Content-Disposition": "attachment; filename=myreport.pdf"
           }`

However, I get the PDF working properly when I hit the same via AJAX call in browser.

Please help!!

Regards,
Samir.

**Comment by samir-kamble** [comment]
got it resolved :)
