### ISSUE TITLE
Possible engine cache problem

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#288]
I noticed the following error in playground today

```
Error occured - Error during rendering report: Cannot read property 'call' of undefined
Stak - TypeError: Cannot read property 'call' of undefined
    at Object.eval (eval at createFunctionContext (C:\jsreport\playground-service2\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:24:30)
    at main (C:\jsreport\playground-service2\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\jsreport\playground-service2\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\jsreport\playground-service2\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at C:\jsreport\playground-service2\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.runInNewContext (vm.js:93:38)
    at module.exports (C:\jsreport\playground-service2\node_modules\jsreport-core\lib\render\engineScript.js:185:8)
```

This was returned during rendering the invoice template
https://playground.jsreport.net/studio/workspace/SyUrRILTg/198

After the service restart the problem went away. I've suspicion that this could be engine cache problem, but I didn't found a bug there.

@bjrmatos Could you please review the engine cache code? Note that I've never seen this error message or have problems with cache yet
https://github.com/jsreport/jsreport-core/blob/master/lib/render/engineScript.js

**Comment by pofider** [comment]
This error occurred again and paralyzed playground. 
It turned out that I've really implemented the engine cache wrongly. I've now removed the problematic code (hashing) which is anyway implemented intervaly in es6 Map used by the lru-cache.
The playground is now updated so lets see if it will help...

**Comment by pofider** [comment]
The problem is not occurring now. I will wait another week and close this afterwards if everything is ok.

**Comment by bjrmatos** [comment]
i just made a self note to include this in jsreportonline too 👍

**Comment by pofider** [comment]
The playground seems to work now well. Closing this.
