### ISSUE TITLE
Failed to load collection reports / JSReport does not starts

### ISSUE THREAD

**Issue by samir-kamble** [jsreport/jsreport#291]
Hello,

I have this problem where i was having running JSreport on server. Suddenly server got restarted and I started getting following error while starting JSreports.

```
2017-05-11T13:57:32.498Z - info: Initializing fs storage at C:\Program Files\nod
ejs\data
2017-05-11T13:57:32.920Z - error: Failed to load collection reports Error: EPERM
: operation not permitted, open 'C:\Program Files\nodejs\data\reports'
2017-05-11T13:57:32.920Z - error: Failed to load collection schedules Error: EPE
RM: operation not permitted, open 'C:\Program Files\nodejs\data\schedules'
2017-05-11T13:57:32.935Z - error: Failed to load collection tasks Error: EPERM:
operation not permitted, open 'C:\Program Files\nodejs\data\tasks'
2017-05-11T13:57:32.935Z - error: Error occured during reporter init Error: EPER
M: operation not permitted, open 'C:\Program Files\nodejs\data\reports'
Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\data\report
s'
```
Any suggestions what would be the reason for the same?

Regards,
Samir

**Comment by pofider** [comment]
Is there a reason why you have jsreport running inside program files?
There are special windows permissions required for this folder.
I would recommend to move your app outside.

**Comment by samir-kamble** [comment]
How do we move it outside? Also i want to upgrade it from 1.4 to 1.7 is it possible?

**Comment by pofider** [comment]
The best is probably to do fresh install of the latest version somewhere in dedicated folder and move there `data` folder from original app. If you have changed the config files, you should move them as well.

**Comment by samir-kamble** [comment]
Getting this error when did "npm init" in new fresh installation.

```
Sorry, license should be a valid SPDX license expression (without "LicenseRef"),
 "UNLICENSED", or "SEE LICENSE IN <filename>" and license is similar to the vali
d expression "LGPL-3.0".
```

**Comment by pofider** [comment]
Isn't this actually just warning? What node/npm version you have?

**Comment by samir-kamble** [comment]
Node 4.2.2
npm 2.14.7

I typed UNLICENSED in there and it installed. But when I try to run it using "npm start" or "node start" It gives me error.
```
 C:\Users\c-samirka\Desktop\jsreport>npm start

> jsreport@1.7.0 start C:\Users\c-samirka\Desktop\jsreport
> node server.js

module.js:339
    throw err;
    ^

Error: Cannot find module 'node.extend'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\c-samirka\Desktop\jsreport\index.js:5:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! jsreport@1.7.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsreport@1.7.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the jsreport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls jsreport
npm ERR! There is likely additional logging output above.
```

**Comment by pofider** [comment]
I'll try with this version. In the meantime, would you consider to update node.js/npm? The latest 6.10.3 should work fine - https://nodejs.org

**Comment by samir-kamble** [comment]
Tried this now, on Node Version 7.5 but again gave error.
```
C:\WT\jsreport>npm start
> jsreport@1.7.0 start C:\WT\jsreport
> node server.js
module.js:472
    throw err;
    ^
Error: Cannot find module 'node.extend'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\WT\jsreport\index.js:5:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! jsreport@1.7.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsreport@1.7.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jsreport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jsreport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jsreport
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?
npm ERR! Please include the following file with any support request:
npm ERR!     C:\WT\jsreport\npm-debug.log
```

**Comment by samir-kamble** [comment]
I am trying to install it in an offline server. Am I following right steps?

**Comment by pofider** [comment]
Ah. You should do clean install on your server and then copy paste the application to the server which has the same architecture and same node version preferably.
https://jsreport.net/learn/faq#deploy-to-production

**Comment by pofider** [comment]
I cannot replicate such issues you mentioned locally ...

**Comment by pofider** [comment]
Closing as I cannot replicate it locally. Feel free to reopen and give us more info in time.
