### ISSUE TITLE
error in pdf generation

### ISSUE THREAD

**Issue by mmajidali40** [jsreport/jsreport#306]
when POST request has large data jsreport crashes with error

details: too many parameters PayloadTooLargeError: too many parameters
    at queryparse (/usr/local/arpreport/node_modules/jsreport/node_modules/jsreport-express/node_modules/body-parser/lib/types/urlencoded.js:144:13)
    at parse (/usr/local/arpreport/node_modules/jsreport/node_modules/jsreport-express/node_modules/body-parser/lib/types/urlencoded.js:75:9)
    at /usr/local/arpreport/node_modules/jsreport/node_modules/jsreport-express/node_modules/body-parser/lib/read.js:116:18
    at invokeCallback (/usr/local/arpreport/node_modules/jsreport/node_modules/jsreport-express/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/usr/local/arpreport/node_modules/jsreport/node_modules/jsreport-express/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/usr/local/arpreport/node_modules/jsreport/node_modules/jsreport-express/node_modules/body-parser/node_modules/raw-body/index.js:307:7)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

**Comment by bjrmatos** [comment]
we have a limit of `20mb` of allowed data, if you are using more data in your request use the following in your config file:

```js
"express": {
  "inputRequestLimit": "50mb"
}
```

or more if you are using more data.
