### ISSUE TITLE
phantom-pdf times out when waiting for print trigger

### ISSUE THREAD

**Issue by cesartl** [jsreport/jsreport#317]
I'm doing almost the same as the example as https://playground.jsreport.net/studio/workspace/SkDFywLpe/193

I have a `chart.js` graph which I want to print as pdf.

It works well for html and as described in your example I set the `wait for printing trigger option` of phantom-js and then I use the animation callback to trigger the print:

```
new Chart(canva.getContext("2d"), {
                            type: 'bar',
                            data: {
                                labels: grouped.map(x => x.gender),
                                datasets: [{
                                    fillColor: 'blue',
                                    label: "Gender",
                                    backgroundColor: "rgba(27,161,226,0.2)",
                                    borderColor: "rgba(27,161,226,1)",
                                    borderWidth: 1,
                                    hoverBackgroundColor: "rgba(27,161,226,0.4)",
                                    hoverBorderColor: "rgba(27,161,226,1)",
                                    data: grouped.map(x => x.value)
                                }]
                                
                            },
                            options: {
                              animation: {
                                    onComplete: function () {
                                        $('#status').text('DONE')
                                        // set the PDF printing trigger when the animation is done
                                        // to have this working, the phantom-pdf menu in the left must
                                        // have the wait for printing trigger option selected
                                        window.JSREPORT_READY_TO_START = true
                                    }
                                }
                            }
                        });
```

However when I run the template it hangs for some time and then eventually times out:

```
Error occured - Error during rendering report: Timeout
Stak - Error: Timeout
    at /usr/src/app/node_modules/phantom-html-to-pdf/node_modules/phantom-workers/lib/phantomManager.js:112:29
    at /usr/src/app/node_modules/phantom-html-to-pdf/node_modules/phantom-workers/lib/phantomWorker.js:111:20
    at Socket.<anonymous> (/usr/src/app/node_modules/phantom-html-to-pdf/node_modules/phantom-workers/lib/checkPortStatus.js:45:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12)
```

I'm using Docker `jsreport:1.7.0-full`. Is that a known bug in this version or I'm missing something really obvious?

**Comment by pofider** [comment]
1. Try to run the template without the trigger enabled and in debug. You may see some javascript errors in the output.

2. You can try to replicate the full issue in a new playground workspace so we can take a look

**Comment by cesartl** [comment]
hi @pofider,

you are right, there is indeed an error in the debug mode.

```
+0      Starting rendering request 79
+80     Rendering template {shortid:Sysy_1BUW, recipe:phantom-pdf,engine:handlebars}
+81     Data item not defined for this template.
+314    Resources not defined for this template.
+316    Rendering engine handlebars
+330    Taking compiled template from engine cache
+334    Replaced images []
+335    Executing recipe phantom-pdf
+342    Converting in http server based phantomjs 1.9.8
+343    Request file:///%2Ftmp%2Fjsreport-temp%2F1501f630-7172-11e7-ac43-69809e70d7d8html.html
+344    Request https://code.jquery.com/jquery-2.2.4.min.js
+344    Request https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.13.0/pivot.min.css
+344    Request https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.13.0/pivot.min.js
+345    Request https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.13.0/tips_data.min.js
+345    Request https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.min.js
+494    SyntaxError: Parse error
+514    phantom-pdf recipe finished with 1 pages generated
+514    Skipping storing report.
+698    Rendering request finished 79
```

I recreated the problem in the playground: https://playground.jsreport.net/studio/workspace/SyVplmrL-/2

Is phantom-js failling to parse `https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.min.js`? It works well in html

**Comment by bjrmatos** [comment]
> Is phantom-js failling to parse https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.min.js? It works well in html

not really, the issue is in your code, you are using ES6 (`const`, arrow functions, etc) but phantom only understands plain old ES5 😃

**Comment by cesartl** [comment]
haaa,

sorry I'm too used to ES6 I didn't even notice....

sorry about that
