### ISSUE TITLE
Cant Compile to Exe on Windows

### ISSUE THREAD

**Issue by tofilagman** [jsreport/jsreport#355]
Hi, 

why i cant compile to exe?
thanks
---
jsreport Compiling jsreport bootstrapped through server.js into jsreport.exe +0ms
  jsreport Temporary starting jsreport instance to collect configuration +5ms
E:\Projects\JSReport\test\node_modules\jsreport-compile\lib\compile\compile.js:86
  return reporter.init().then(function () {
                  ^

TypeError: reporter.init is not a function
    at collectConfig (E:\Projects\JSReport\test\node_modules\jsreport-compile\lib\compile\compile.js:86:19)
    at prepareJsreport (E:\Projects\JSReport\test\node_modules\jsreport-compile\lib\compile\compile.js:211:10)
    at module.exports (E:\Projects\JSReport\test\node_modules\jsreport-compile\lib\compile\compile.js:338:10)
    at Object.<anonymous> (E:\Projects\JSReport\test\node_modules\jsreport-compile\bin\compile.js:35:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

**Comment by bjrmatos** [comment]
hi! check that the entry point (`jsreport-compile -i entryPoint.js`) is exporting your jsreport instance, probably your entry point is not exporting anything or just an empty object by default. here is an [example of the expected entry point](https://github.com/bjrmatos/jsreport-with-authorization-server-sample/blob/master/jsreport-server/server.js)

**Comment by pofider** [comment]
Closing because of inactivity.
