### ISSUE TITLE
Latest JSreport 1.8.2 Installation Problem with specific Port Num

### ISSUE THREAD

**Issue by yellareddy-allcloud** [jsreport/jsreport#357]
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd/

C:\>cd jsreport-win

C:\jsreport-win>jsreport configure
? For which environment would you like to generate configuration? dev
? Do you want to enable web server? Yes
? Which protocol should web server use? http
? Specify the http port for web server: 3002
? Do you want to enable authentication in web server? No
? Do you want to persist jsreport objects in disk? No, memory connection will be used
? Do you want jsreport to enable local file access? No
config saved in: C:\jsreport-win\dev.config.json

C:\jsreport-win>jsreport win-install
Platform is win32
Installing windows service "jsreport-server-exe" for app..
Service "jsreport-server-exe" is running.

C:\jsreport-win>jsreport start
2017-11-01T17:43:02.076Z - info: Initializing jsreport@1.8.2 in development mode using configuration file dev.config.json
2017-11-01T17:43:02.079Z - info: Using extension import-export
2017-11-01T17:43:02.079Z - info: Using extension templates
2017-11-01T17:43:02.079Z - info: Using extension jsrender
2017-11-01T17:43:02.079Z - debug: Extension authentication is disabled, skipping
2017-11-01T17:43:02.079Z - info: Using extension cli
2017-11-01T17:43:02.079Z - info: Using extension handlebars
2017-11-01T17:43:02.079Z - info: Using extension debug
2017-11-01T17:43:02.079Z - info: Using extension express
2017-11-01T17:43:02.110Z - info: Using extension fop-pdf
2017-11-01T17:43:02.110Z - info: Using extension tags
2017-11-01T17:43:02.110Z - info: Using extension phantom-pdf
2017-11-01T17:43:02.110Z - info: Using extension fs-store
2017-11-01T17:43:02.126Z - debug: Extension fs-store was disabled
2017-11-01T17:43:02.126Z - info: Using extension authorization
2017-11-01T17:43:02.126Z - debug: Extension authorization was disabled
2017-11-01T17:43:02.126Z - info: Using extension images
2017-11-01T17:43:02.126Z - info: Using extension child-templates
2017-11-01T17:43:02.126Z - info: Using extension browser-client
2017-11-01T17:43:02.126Z - info: Using extension licensing
2017-11-01T17:43:02.126Z - info: Using extension data
2017-11-01T17:43:02.126Z - info: Using extension text
2017-11-01T17:43:02.126Z - info: Using extension reports
2017-11-01T17:43:02.142Z - info: Using extension resources
2017-11-01T17:43:02.142Z - info: Using extension base
2017-11-01T17:43:02.142Z - info: Using extension studio
2017-11-01T17:43:02.142Z - info: Using extension html-to-xlsx
2017-11-01T17:43:02.157Z - info: Using extension scripts
2017-11-01T17:43:02.157Z - info: Using extension assets
2017-11-01T17:43:02.157Z - info: Using extension scheduling
2017-11-01T17:43:02.157Z - info: Using extension xlsx
2017-11-01T17:43:02.157Z - info: Using extension sample-template
2017-11-01T17:43:02.157Z - debug: Creating samples is disabled
2017-11-01T17:43:02.157Z - info: Using extension public-templates
2017-11-01T17:43:02.157Z - debug: Extension public-templates was disabled
2017-11-01T17:43:02.195Z - info: Creating memory store
2017-11-01T17:43:02.257Z - info: Creating default express app.
2017-11-01T17:43:02.358Z - error: Error when starting http server on port 3002 Error: listen EADDRINUSE :::3002
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at jsreportRuntime.js:142086:12
    at Promise._execute (jsreportRuntime.js:42873:9)
    at Promise._resolveFromExecutor (jsreportRuntime.js:45151:18)
    at new Promise (jsreportRuntime.js:44747:10)
    at startAsync (jsreportRuntime.js:142078:10)
    at startExpressApp (jsreportRuntime.js:142112:12)
    at null.<anonymous> (jsreportRuntime.js:142247:12)
    at jsreportRuntime.js:186821:33
    at jsreportRuntime.js:186801:16
    at tryCatcher (jsreportRuntime.js:47158:23)
    at Promise._settlePromiseFromHandler (jsreportRuntime.js:129469:31)
    at Promise._settlePromise (jsreportRuntime.js:129526:18)
    at Promise._settlePromise0 (jsreportRuntime.js:129571:10)
    at Promise._settlePromises (jsreportRuntime.js:129650:18)
    at Async._drainQueue (jsreportRuntime.js:42090:16)
    at Async._drainQueues (jsreportRuntime.js:42100:10)
    at Immediate.Async.drainQueues [as _onImmediate] (jsreportRuntime.js:41974:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
2017-11-01T17:43:02.358Z - error: Error occured during reporter init Error: listen EADDRINUSE :::3002
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at jsreportRuntime.js:142086:12
    at Promise._execute (jsreportRuntime.js:42873:9)
    at Promise._resolveFromExecutor (jsreportRuntime.js:45151:18)
    at new Promise (jsreportRuntime.js:44747:10)
    at startAsync (jsreportRuntime.js:142078:10)
    at startExpressApp (jsreportRuntime.js:142112:12)
    at null.<anonymous> (jsreportRuntime.js:142247:12)
    at jsreportRuntime.js:186821:33
    at jsreportRuntime.js:186801:16
    at tryCatcher (jsreportRuntime.js:47158:23)
    at Promise._settlePromiseFromHandler (jsreportRuntime.js:129469:31)
    at Promise._settlePromise (jsreportRuntime.js:129526:18)
    at Promise._settlePromise0 (jsreportRuntime.js:129571:10)
    at Promise._settlePromises (jsreportRuntime.js:129650:18)
    at Async._drainQueue (jsreportRuntime.js:42090:16)
    at Async._drainQueues (jsreportRuntime.js:42100:10)
    at Immediate.Async.drainQueues [as _onImmediate] (jsreportRuntime.js:41974:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
An error has occurred when trying to initialize jsreport.. seems like there is already a server running in port: 3002
{ [Error: listen EADDRINUSE :::3002]
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3002 }

**Comment by bjrmatos** [comment]
when you run `jsreport win-install` a windows service will be created and started, after this command has finished your port 3002 is already used so it is normal that if you try to run `jsreport start` after the previous command your app fail with that message because port 3002 is being used by the windows service. either stop the windows service (to free the 3002 port) and run `jsreport start`, or run `jsreport start --httpPort 3003` to use another port

**Comment by yellareddy-allcloud** [comment]
yes sir absolutely  you are correcting, i have given another port number, it was installed successfully. Thank you very much sir, for your reply.
