### ISSUE TITLE
Error running docker image with tag latest-full

### ISSUE THREAD

**Issue by ealves-pt** [jsreport/jsreport#391]
Attempting to run the docker image `jsreport/jsreport:latest-full` throws an error (it works with `jsreport/jsreport:1.9.2-full`).

```
18:06 $ docker run -p 5488:5488 jsreport/jsreport:latest-full
Trying to remove the lock on display 99
Running display 99
Starting node.js
module.js:124
    throw e;
    ^

SyntaxError: Error parsing /usr/src/app/node_modules/async/package.json: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at readPackage (module.js:120:52)
    at tryPackage (module.js:130:13)
    at Function.Module._findPath (module.js:212:20)
    at Function.Module._resolveFilename (module.js:536:25)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/node_modules/nconf/lib/nconf/common.js:9:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
```

**Comment by bjrmatos** [comment]
hi! hmm not sure what is happening, it works for me (OSX) when using the `latest-full` tag. have you tried with `1.10.0-full`? maybe you can try to copy the `/usr/src/app/node_modules/async/package.json` file from the container to your machine and check what it has, maybe for some reason the file contains invalid characters during npm install

**Comment by pofider** [comment]
I would recommend to always use explicit version.

Closing to inactivity. However feel free to comment.

**Comment by barankaynak** [comment]
Running full image on centos with docker runs without any problem. But running on rancheros with kubernetes gives the error below. I tried to modify docker file but not succeeded. After creating folders with root user owner should be changed to the jsreport user. But I couldnt solve this problem for volume folder.
Error: EACCES: permission denied, mkdir '/app/logs'

**Comment by barankaynak** [comment]
Mounting a volume to /app/logs folder helps but run.sh still not working.
