### ISSUE TITLE
Expecting 'EOF', got 'OPEN_ENDBLOCK' Stak - Error: Parse error on line 85:

### ISSUE THREAD

**Issue by luis-leon** [jsreport/jsreport#395]
I am developing an application in which I need to obtain mongo db reports, however, when using this extension and using the described script I am presented with this error when trying to run the script, could someone guide me to explain this problem

Error occured - Error during rendering report: Parse error on line 85:
...e}}</h1>
    
    {{/for}}
      

---------------------^
Expecting 'EOF', got 'OPEN_ENDBLOCK'
Stak - Error: Parse error on line 85:
...e}}</h1>
    
    {{/for}}
      

---------------------^
Expecting 'EOF', got 'OPEN_ENDBLOCK'
    at Object.parseError (C:\Bitnami\meanstack-3.2.8-2\apps\jsreport\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Object.parse (C:\Bitnami\meanstack-3.2.8-2\apps\jsreport\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30)
    at HandlebarsEnvironment.parse (C:\Bitnami\meanstack-3.2.8-2\apps\jsreport\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (C:\Bitnami\meanstack-3.2.8-2\apps\jsreport\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:514:19)
    at ret (C:\Bitnami\meanstack-3.2.8-2\apps\jsreport\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18)
    at C:\Bitnami\meanstack-3.2.8-2\apps\jsreport\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)

![sin titulo](https://user-images.githubusercontent.com/37821419/37943574-585d8b82-3135-11e8-97bd-7858d684d8cc.png)

**Comment by pofider** [comment]
Multiple issues here.

1. You use jsrender syntax, but I see on image you have handlebars selected.
https://jsreport.net/learn/templating-engines

2. You put the jsreport custom sever side script to the place where the templating engines are expected.
https://jsreport.net/learn/scripts

**Comment by Emtiaz2000** [comment]
thanks its's help me to debug
