### ISSUE TITLE
ensure node 10 support

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#407]
somehow there are some errors while starting jsreport v2 in node 10

**Comment by bjrmatos** [comment]
the error that was occurring in node 10 when i was testing was something like this:

```
2018-05-16T20:55:05.605Z - error: Error when loading extension html-to-xlsx
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.module.exports (/node_modules/jsreport-html-to-xlsx/lib/htmlToXlsx.js:72:43)
    at Object._useOne (/node_modules/jsreport-core/lib/extensions/extensionsManager.js:154:75)
    at Object._useMany (/node_modules/jsreport-core/lib/extensions/extensionsManager.js:73:20)
2018-05-16T20:55:05.606Z - error: Error occured during reporter init Error: Error when loading extension html-to-xlsx
```

but turns out that this was just [a bug with jsreport-html-to-xlsx when it was used with phantomjs-prebuilt installed](https://github.com/jsreport/jsreport/issues/410), this is solved now in `jsreport-html-to-xlsx@2.0.1` and it will be part of next jsreport v2 minor/patch release.

after that, fixing a bug in jsreport-wkhtmltopdf and doing some test rendering reports i don't see something breaking in node 10, it is running good and smooth
