### ISSUE TITLE
Error when loading extension phantom-pdf aspnet core

### ISSUE THREAD

**Issue by irowbin** [jsreport/jsreport#409]
I am getting this error:
`Error when loading extension phantom-pdf
Error: ENOENT: no such file or directory, scandir 'C:\Users\Robin\AppData\Local\Temp\node_modules'
    at crawlAvailiblePhantomVersions (D:\Projects\App\node_modules\jsreport-phantom-pdf\lib\phantom.js:69:12)
    at Phantom.init (D:\Projects\App\node_modules\jsreport-phantom-pdf\lib\phantom.js:81:10)
    at Object.module.exports (D:\Projects\App\node_modules\jsreport-phantom-pdf\lib\phantom.js:244:36)
    at Object._useOne (D:\Projects\App\node_modules\jsreport-core\lib\extensions\extensionsManager.js:154:75)
    at Object._useMany (D:\Projects\App\node_modules\jsreport-core\lib\extensions\extensionsManager.js:73:20)
    at <anonymous>
Error: Error when loading extension phantom-pdf
Error: ENOENT: no such file or directory, scandir 'C:\Users\Robin\AppData\Local\Temp\node_modules'
    at crawlAvailiblePhantomVersions (D:\Projects\App\node_modules\jsreport-phantom-pdf\lib\phantom.js:69:12)
    at Phantom.init (D:\Projects\App\node_modules\jsreport-phantom-pdf\lib\phantom.js:81:10)
    at Object.module.exports (D:\Projects\App\node_modules\jsreport-phantom-pdf\lib\phantom.js:244:36)
    at Object._useOne (D:\Projects\App\node_modules\jsreport-core\lib\extensions\extensionsManager.js:154:75)
    at Object._useMany (D:\Projects\App\node_modules\jsreport-core\lib\extensions\extensionsManager.js:73:20)
    at <anonymous>
    at Object._useOne (D:\Projects\App\node_modules\jsreport-core\lib\extensions\extensionsManager.js:163:15)
    at <anonymous>`

project structure 
![capture](https://user-images.githubusercontent.com/13050078/40278075-119937d8-5c4a-11e8-8fcf-38ec8947bc30.JPG)

package.json
```json
{
  "dependencies": {
    "jsreport-core": "^2.0.1",
    "jsreport-jsrender": "^2.0.0",
    "jsreport-phantom-pdf": "^2.0.1",
    "phantom-pdf": "^0.4.1",
    "phantomjs-prebuilt": "^2.1.16"
  }
}
```

htmlToPdf.js file

```javascript
module.exports = function (callback, html) {
    var jsreport = require('jsreport-core')();

    jsreport.init().then(function () {
        return jsreport.render({
            template: {
                content: html,
                engine: 'jsrender',
                recipe: 'phantom-pdf'
            }
        }).then(function (resp) {
            callback(/* error */ null, resp.content);
        });
    }).catch(function (e) {
        callback(/* error */ e, null);
    })
};
```

startup.cs
```c#
 services.AddNodeServices( o =>
 {
    o.InvocationTimeoutMilliseconds = 300000;
    o.LaunchWithDebugging           = true;

 } );
```

controller

```c#
private readonly INodeServices   _nodeServices;

public HomeController(INodeServices  nodeServices  ){
         nodeServices  = _nodeServices;
}

public async Task<IActionResult> Export(){
      var htmlContent = "<div class='alert alert-danger'> hello from jsreport </div>"
      var result = await _nodeServices.InvokeAsync<byte[]>("./htmlToPdf", htmlContent);
}
```

I am unable to track down the error whether it is coming from this ` var jsreport = require('jsreport-core')();` or  from `INodeServices`🤔

**Comment by pofider** [comment]
It looks that for some reason your node/jsreport starts from the temp directory. Try to set up the app directory explicitelly.

```js
jsreport.init({
 appDirectory: 'dir where is your package.json'
})
```

**Comment by anaszgh** [comment]
@pofider i have tried this method like this 
```
jsreport.init({
        appDirectory: './'
    })
```
but still i got the same error, do i need to specify the full path??

**Comment by pofider** [comment]
Yes try the absolute path.

If it won't help please try to create for me a minimal repository replicating the problem so I can try to figure out what is wrong.

**Comment by anaszgh** [comment]
@pofider It didn't work either, and as i'm debugging it i found that the init method accepts no parameters

``` 
interface Reporter {
		afterRenderListeners: ListenerCollection;
		afterTemplatingEnginesExecutedListeners: ListenerCollection;
		beforeRenderListeners: ListenerCollection;
		documentStore: DocumentStore;
		initializeListeners: ListenerCollection;
		// it would be nice to add winston.LoggerInstance here
		// however adding import winston = require('winston') breaks exported enums
		logger: any;
		validateRenderListeners: ListenerCollection;
		version: string;
		init(): Promise<Reporter>;
		render(options: Partial<Request>): Promise<Response>;
		discover(): Reporter;
		createListenerCollection(): ListenerCollection;
	}
```
However you can specify the rootDirectory in the constructor of jsreport-core like this:
```
var jsreport = require('jsreport-core')({
        rootDirectory:'{path to the directory}'
    })
```

However that didn't fix it, PahntomJs still trying to load something from the Temp folder
here is the error
```
Error when loading extension phantom-pdf
Error: ENOENT: no such file or directory, scandir 'C:\\Users\\AnasZgh\\AppData\\Local\\Temp\\node_modules'
 at crawlAvailiblePhantomVersions (C:\\Eventerest\\Server\\Eventerest.Server\\Eventerest.Server.APIs\\node_modules\\jsreport-phantom-pdf\\lib\\phantom.js:69:12)
    at Phantom.init (C:\\Eventerest\\Server\\Eventerest.Server\\Eventerest.Server.APIs\\node_modules\\jsreport-phantom-pdf\\lib\\phantom.js:81:10)
    at Object.module.exports (C:\\Eventerest\\Server\\Eventerest.Server\\Eventerest.Server.APIs\\node_modules\\jsreport-phantom-pdf\\lib\\phantom.js:244:36)
    at Object._useOne (C:\\Eventerest\\Server\\Eventerest.Server\\Eventerest.Server.APIs\\node_modules\\jsreport-core\\lib\\extensions\\extensionsManager.js:154:75)
    at Object._useMany (C:\\Eventerest\\Server\\Eventerest.Server\\Eventerest.Server.APIs\\node_modules\\jsreport-core\\lib\\extensions\\extensionsManager.js:73:20)
    at <anonymous>
Error: Error when loading extension phantom-pdf
Error: ENOENT: no such file or directory, scandir 'C:\\Users\\AnasZgh\\AppData\\Local\\Temp\\node_modules'
    at crawlAvailiblePhantomVersions (C:\\Eventerest\\Server\\Eventerest.Server\\Eventerest.Server.APIs\\node_modules\\jsreport-phantom-pdf\\lib\\phantom.js:69:12)
    at Phantom.init (C:\\Eventerest\\Server\\Eventerest.Server\\Eventerest.Server.APIs\\node_modules\\jsreport-phantom-pdf\\lib\\phantom.js:81:10)
   at Object.module.exports (C:\\Eventerest\\Server\\Eventerest.Server\\Eventerest.Server.APIs\\node_modules\\jsreport-phantom-pdf\\lib\\phantom.js:244:36)
   at Object._useOne (C:\\Eventerest\\Server\\Eventerest.Server\\Eventerest.Server.APIs\\node_modules\\jsreport-core\\lib\\extensions\\extensionsManager.js:154:75)
   at Object._useMany (C:\\Eventerest\\Server\\Eventerest.Server\\Eventerest.Server.APIs\\node_modules\\jsreport-core\\lib\\extensions\\extensionsManager.js:73:20)
   at <anonymous>
    at Object._useOne (C:\\Eventerest\\Server\\Eventerest.Server\\Eventerest.Server.APIs\\node_modules\\jsreport-core\\lib\\extensions\\extensionsManager.js:163:15)
   at <anonymous>
```

**Comment by anaszgh** [comment]
@irowbin @pofider I managed to fix this issue, i have found that in the configuration of jsreport-core you pass a property called rootDirectory, but in the jsreport-phantom-pdf it uses appDirectory

**From jsreport-phantom-pdf Line:65**
```
var npm = path.join(this.reporter.options.appDirectory, 'node_modules')
```

so in the constructor of the jsreport-core i have passed these values in the constructor

```
var jsreport = require('jsreport-core')({
        rootDirectory:__dirname,
        tempDirectory:__dirname,
        appDirectory:__dirname
    })
```
and that fixed it 😄

**Comment by pofider** [comment]
Ups. Sorry, the config really needs to be passed to the the factory function and not to the `init` as you found out.

I've now changed the `jsreport-phantom-pdf` to also take the directory from `rootDirectory` option. So you will only need `rootDirectory` when you update the package.
