### ISSUE TITLE
ReferenceError: request is not defined. JsReport 1.3.1 > JsReport 2.0.0 upgrade

### ISSUE THREAD

**Issue by hemstreet** [jsreport/jsreport#411]
**A quick overview:**
* Migration 1.3.1 > 2.0.0
* node version v9.2.1
* MongoDb to S3 storage

I've been upgrading JsReport form version 1 to version 2. I've followed the guide to upgrade from your blog. I pulled over the existing reports from mongodb to S3 in V2. When trying to run the report for some PDF reports I get the following error:

```
ReferenceError: request is not defined
    at Object.beforeRender (vm.js:2:19)
    at Object.__runBefore (/Users/xyz/jsReport/node_modules/jsreport-scripts/lib/scriptEvalChild.js:76:42)
    at Object.apply (/Users/xyz/jsReport/node_modules/vm2/lib/contextify.js:288:34)
    at vm.js:27:1
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (/Users/xyz/jsReport/node_modules/vm2/lib/main.js:212:72)
    at module.exports (/Users/xyz/jsReport/node_modules/jsreport-scripts/lib/scriptEvalChild.js:125:3)
    at IncomingMessage.<anonymous> (/Users/xyz/jsReport/node_modules/script-manager/lib/worker-servers.js:239:47)
    at IncomingMessage.emit (events.js:159:13)
    at endReadableNT (_stream_readable.js:1054:12)
```

## V1 ##
dev.config.json
```
{
  "connectionString": {
    "name": "mongoDB",
    "authDb": "jsreport",
    "address": "abc@123.com",
    "port": 27017,
    "databaseName": "jsreport"
  },
  "blobStorage": "gridFS",
  "cluster": {
    "numberOfWorkers": 2,
    "enabled": true
  },
  "phantom": {
    "numberOfWorkers": 2,
    "timeout": 180000
  },
  "tasks": {
    "numberOfWorkers": 2,
    "timeout": 10000,
    "allowedModules": [
      "dateformat"
    ]
  },
  "scripts": {
    "allowedModules": "*"
  },
  "express": {
    "inputRequestLimit": "40mb"
  }
}
```
Package.json
```
{
  "name": "jsreport-server",
  "scripts": {
      "start": "node start.js"
    },
  "dependencies": {
	"jsreport": "1.3.1",
	"mongodb": "*",
	"jsreport-mongodb-store": "*",
	"request":"*",
  "dateformat":"*"
  },
  "main": "server.js"
}

```

start.js
```
require('jsreport')().init();
```

## V2 ##
dev.config.json
```
{
  "licenseKey": "AAAAAAAA-BBBBBBBB-CCCCCCCCC-DDDDDDDD",
  "allowLocalFilesAccess": true,
  "store": {
    "provider": "fs"
  },
  "blobStorage": {
    "provider": "fs"
  },
  "cluster": {
    "numberOfWorkers": 2,
    "enabled": true
  },
  "phantom": {
    "numberOfWorkers": 2,
    "timeout": 180000
  },
  "templatingEngines": {
    "numberOfWorkers": 2,
    "timeout": 10000,
    "allowedModules": [
      "dateformat"
    ]
  },
  "extensions": {
    "scripts": {
      "timeout": 50000,
      "strategy": "dedicated-process",
      "allowedModules": "*"
    },
    "html-to-xlsx": {
      "enabled": false
    },
    "fs-store": {
      "persistence": {
        "provider": "aws-s3"
      }
    },
    "fs-store-aws-s3-persistence": {
      "accessKeyId": "1231231234123",
      "secretAccessKey": "xyzabc123xyzabc123xyzabc123",
      "bucket": "jsreport",
      "lock": {
        "enabled": false
      }
    }
  }
}
```

package.json
```
{
  "name": "jsreport-server",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "dateformat": "*",
    "jsreport": "2.0.0",
    "jsreport-fop-pdf": "^2.0.0",
    "jsreport-phantom-pdf": "^2.0.1",
    "phantomjs-prebuilt": "^2.1.16",
    "request": "*"
  },
  "main": "server.js"
}
```

server.js
```
require('jsreport')().init();
```

**Comment by pofider** [comment]
The error comes from custom script execution. Can you share its content?
You likely use global `request` variable which was removed in v2.

https://jsreport.net/learn/v2-breaking-changes#script-content

**Comment by hemstreet** [comment]
Thanks for the quick reply! I do see that we are using the request object. I'll update the method signature to `req, res, done`

```
function beforeRender(done) {
    var tickets = request.data.tickets;
    
    var allTickets = tickets.pickups.concat(tickets.dropoffs);
    
    request.data.tickets.all = convertPhotoNames(allTickets);
    
    done();
}

function convertPhotoNames(tickets) {
    return tickets.map(function(ticket) {
        ticket.photoNumber = {};
        if (ticket.photos) {
            ticket.photos = ticket.photos.map(function(photo, index) {
               return {
                   url: photo.url,
                   signedUrl: photo.signedUrl,
                   number: ++index
               };
            });    
        }
        
        return ticket;
    });
}
```

I saw that you mentioned that it was deprecated, but the docs for `tasks` were showing that the request module was being allowed. Maybe thats where I got confused
`{ templatingEngines: { timeout: 1000, allowedModules: ['request'] } }`

**Comment by pofider** [comment]
Ok, this code:
```js
{ templatingEngines: { timeout: 1000, allowedModules: ['request'] } }
```
However in v2 you can just set ` "allowLocalFilesAccess": true,` and it will automatically let you to `require` anything or even read local file system with assets.
Means you can call `require('request')` in your code.

**Comment by hemstreet** [comment]
That would make sense, looking at the error, i assumed request was the module and not the custom script. Works perfectly now. thanks!
