### ISSUE TITLE
Templating engine error line identification

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#413]
Old error
```
Error occured - Error during rendering report: b is not defined
Stak - evalmachine.<anonymous>:3
    a = b
    ^

ReferenceError: b is not defined
    at Object.foo (evalmachine.<anonymous>:3:5)
    at Object.eval [as main] (eval at createFunctionContext (C:\jsreport\playground-service2\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:5:194)
```

new error
```
Error: b is not defined
    at module.exports (c:\work\jsreport\jsreport\node_modules\jsreport-core\lib\util\createError.js:4:17)
    at Reporter.createError (c:\work\jsreport\jsreport\node_modules\jsreport-core\lib\reporter.js:256:12)
    at Reporter.executeScript (c:\work\jsreport\jsreport\node_modules\jsreport-core\lib\reporter.js:267:18)
    at <anonymous>
caused by: ReferenceError: b is not defined
    at Object.foo (vm.js:3:5)
    at Object.eval [as main] (eval at createFunctionContext (c:\work\jsreport\jsreport\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:5:194)
    at main 
```

The line number is missing in the new error. Also the information is less detailed. We need to at least take the line number from ` at Object.foo (vm.js:3:5)`

**Comment by bjrmatos** [comment]
this is done now (also with other improvements), new error looks like this:

```
Error while executing templating engine. b is not defined. Error on line 2:5.

  1 | function foo() {
> 2 |     a = b
    |     ^
  3 | }
  4 | function toJSON (data) {
  5 |   return JSON.stringify(data);


ReferenceError: b is not defined
    at Object.foo (evaluate-template-engine-helpers.js:2:5)
    at Object.eval [as main] (eval at createFunctionContext (/Volumes/DATA/workspace/jsreport2-test/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:194)
    at main (/Volumes/DATA/workspace/jsreport2-test/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at ret (/Volumes/DATA/workspace/jsreport2-test/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at ret (/Volumes/DATA/workspace/jsreport2-test/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at /Volumes/DATA/workspace/jsreport2-test/node_modules/jsreport-handlebars/lib/handlebarsEngine.js:25:14
    at Object.apply (/Volumes/DATA/workspace/jsreport2-test/node_modules/vm2/lib/contextify.js:288:34)
    at evaluate-template-engine.js:1:41
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (/Volumes/DATA/workspace/jsreport2-test/node_modules/vm2/lib/main.js:212:72)
```
