### ISSUE TITLE
jsReport is unable to render the template

### ISSUE THREAD

**Issue by vajnorcan** [jsreport/jsreport#420]
I've just installed jsreport cli and configured the server and I cannot make it to run as it ends with the error:
`TypeError: Cannot read property 'forEach' of undefined
    at invokeRender (c:\DevelopmentProjects\jsReport\node_modules\jsreport-core\lib\render\render.js:72:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

FYI:
NODEJS: 8.11.1
NPM: 5.6.0

**Comment by bjrmatos** [comment]
hi! can you show the template content that is making this error to occur? do you have just jsreport v2 installed? or are you using some other extensions installed in your project? can you add here the full logs that you get in your console when you try to render this report?

**Comment by vajnorcan** [comment]
there is not much to show, it won't even render the basic text so it must be at the core level. Regarding the installation, I went through the simplest setup as outlined [here](https://jsreport.net/on-prem). 
so whatever version was there yesterday that's the one, jsreport-cli 2.0.3

**Comment by pofider** [comment]
How do you run the report rendering? From the studio, using cli or through an API call?
Please share the logs.

**Comment by vajnorcan** [comment]
it's from the CLI and the log from the debug is

> Cannot read property 'forEach' of undefined
> logs:
> +0      Starting rendering request 2 (user: null)
> +4      Rendering template { name: WAIO-RIDR, recipe: chrome-pdf, engine: jsrender, preview: true }
> +4      Data item not defined for this template.
> +5      Resources not defined for this template.
> +9      Replaced assets ["waio-ridr.css","bhp_orange_logo.svg"]
> +10     Base url not specified, skipping its injection.
> +12     Rendering engine jsrender
> TypeError: Cannot read property 'forEach' of undefined
>     at invokeRender (c:\DevelopmentProjects\jsReport\node_modules\jsreport-core\lib\render\render.js:72:18)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by pofider** [comment]
Is this specific to the particular template?
If true, can you create an export through studio and send it to me?

I've tried cli just now like this and it works fine for me
```
npm i jsreport-cli -g
jsreport init
echo "Hello" > test.html
jsreport render --template.engine=none --template.recipe=chrome-pdf --template.content=test.html --out=out.pdf --verbose
```

How you call it exactly?
Thank you. We would really like to help with it.

**Comment by vajnorcan** [comment]
My apologies, it wasn't the CLI, but reporter (the server on :5488) ... will get back to you once I have a little more time to muck around this again.

**Comment by pofider** [comment]
Closing as there is no response for month. However we still monitor this so please feel free to add comments.

**Comment by shresthasan** [comment]
Hi, i have installed jsreport in my linux server, jsreport/jsreport-postgres-store v3 , after installing jsreport/jsreport-postgres-store throws error 
error: Error when processing OData GET: /odata/assets?$select=isSharedHelper,scope,name,shortid,tags,folder&$orderby=name TypeError: Cannot read properties of undefined (reading 'forEach')
    at module.exports (/home/devops/jsreport02/node_modules/@jsreport/odata-to-sql/lib/query.js:54:28)
    at Object.query (/home/devops/jsreport02/node_modules/@jsreport/odata-to-sql/lib/transformer.js:46:14)
    at Cursor.toArray (/home/devops/jsreport02/node_modules/@jsreport/sql-store/lib/sqlProvider.js:22:29)
    at replay (/home/devops/jsreport02/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:51:21)
    at /home/devops/jsreport02/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:58:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-19T11:06:56.666Z - debug: OData query on scripts
2022-01-19T11:06:56.669Z - debug: OData query on schedules
2022-01-19T11:06:56.672Z - debug: OData query on settings

**Comment by shresthasan** [comment]
my jsreport setting are 
[devops@localhost jsreport02]$ node server.js 
2022-01-19T11:06:50.901Z - info: Initializing jsreport (version: 3.3.0, configuration file: jsreport.config.json, nodejs: 16.13.0)
2022-01-19T11:06:50.903Z - info: Searching for available extensions in /home/devops/jsreport02/
2022-01-19T11:06:50.916Z - info: Extensions location cache contains up to date information, skipping crawling in /home/devops/jsreport02/
2022-01-19T11:06:50.923Z - info: Found 36 extension(s)
2022-01-19T11:06:50.945Z - debug: Writing extension locations cache to /tmp/jsreport/core/locations.json
2022-01-19T11:06:50.946Z - debug: Discovered 36 extensions
2022-01-19T11:06:51.006Z - debug: Extension authentication@3.2.0 is disabled, skipping
2022-01-19T11:06:51.007Z - info: Using extension base@3.0.0
2022-01-19T11:06:51.012Z - info: Using extension child-templates@3.0.1
2022-01-19T11:06:51.015Z - info: Using extension cli@3.0.0
2022-01-19T11:06:51.017Z - info: Using extension components@3.2.0
2022-01-19T11:06:51.018Z - info: Using extension data@3.0.1
2022-01-19T11:06:51.019Z - info: Using extension express@3.2.1
2022-01-19T11:06:51.192Z - info: Using extension freeze@3.0.1
2022-01-19T11:06:51.194Z - info: Using extension fs-store@3.0.0
2022-01-19T11:06:51.243Z - info: Using extension handlebars@3.0.0
2022-01-19T11:06:51.245Z - info: Using extension import-export@3.0.2
2022-01-19T11:06:51.253Z - info: Using extension jsrender@3.0.0
2022-01-19T11:06:51.253Z - info: Using extension licensing@3.0.1
2022-01-19T11:06:51.270Z - info: Using extension localization@3.1.1
2022-01-19T11:06:51.270Z - info: Using extension npm@3.1.0
2022-01-19T11:06:51.273Z - info: Using extension pdf-utils@3.2.0
2022-01-19T11:06:51.274Z - info: Using extension postgres-store@3.0.0
2022-01-19T11:06:51.361Z - info: Using extension reports@3.0.1
2022-01-19T11:06:51.363Z - info: Using extension tags@3.1.0
2022-01-19T11:06:51.364Z - info: Using extension text@3.0.0
2022-01-19T11:06:51.365Z - info: Using extension version-control@3.0.1
2022-01-19T11:06:51.373Z - info: Using extension assets@3.2.0
2022-01-19T11:06:51.380Z - info: Using extension authorization@3.2.0
2022-01-19T11:06:51.382Z - debug: Extension authorization@3.2.0 was disabled
2022-01-19T11:06:51.382Z - info: Using extension browser-client@3.1.0
2022-01-19T11:06:51.383Z - info: Using extension chrome-pdf@3.1.0
2022-01-19T11:06:51.386Z - debug: Chrome strategy is chrome-pool, numberOfWorkers: 1
2022-01-19T11:06:51.386Z - debug: Chrome custom launch options are args=--no-sandbox, executablePath=/opt/google/chrome-unstable/chrome
2022-01-19T11:06:51.386Z - info: Using extension docx@3.1.0
2022-01-19T11:06:51.388Z - info: Using extension html-to-xlsx@3.1.0
2022-01-19T11:06:51.438Z - info: html-to-xlsx detected chrome as available html engine
2022-01-19T11:06:51.438Z - info: Using extension pptx@3.1.0
2022-01-19T11:06:51.440Z - info: Using extension scheduling@3.0.1
2022-01-19T11:06:51.472Z - info: Using extension scripts@3.2.0
2022-01-19T11:06:51.472Z - info: Using extension static-pdf@3.0.0
2022-01-19T11:06:51.473Z - info: Using extension studio@3.3.0
2022-01-19T11:06:51.527Z - info: Using extension xlsx@3.1.0
2022-01-19T11:06:51.547Z - info: Using extension public-templates@3.0.0
2022-01-19T11:06:51.548Z - debug: Extension public-templates@3.0.0 was disabled
2022-01-19T11:06:51.548Z - info: Using extension sample-template@3.1.0
2022-01-19T11:06:51.550Z - info: Using extension studio-theme-dark@3.0.1
2022-01-19T11:06:51.551Z - info: Using general timeout for rendering (reportTimeout: 60000)
2022-01-19T11:06:51.551Z - info: Using postgres provider for template store.
2022-01-19T11:06:51.604Z - debug: studio default theme is: light
2022-01-19T11:06:51.616Z - info: Creating default express app.
2022-01-19T11:06:51.629Z - info: jsreport server successfully started on http port: 5488
2022-01-19T11:06:51.631Z - info: Verifying license key free
2022-01-19T11:06:51.633Z - info: Using free license
2022-01-19T11:06:51.641Z - debug: Creating samples is disabled
2022-01-19T11:06:51.642Z - info: Initializing worker threads
2022-01-19T11:06:51.642Z - debug: Extensions in workers: base, child-templates, components, data, express, handlebars, jsrender, localization, npm, pdf-utils, reports, text, version-control, assets, browser-client, chrome-pdf, docx, html-to-xlsx, pptx, scripts, static-pdf, studio, xlsx
2022-01-19T11:06:51.818Z - info: 2 worker threads initialized in 176ms
2022-01-19T11:06:51.819Z - info: Starting temp files cleanup with 180000ms threshold
2022-01-19T11:06:51.819Z - info: reporter initialized
2022-01-19T11:06:56.642Z - debug: OData query on templates
2022-01-19T11:06:56.655Z - debug: OData query on tags
2022-01-19T11:06:56.658Z - debug: OData query on folders
2022-01-19T11:06:56.660Z - debug: OData query on components
2022-01-19T11:06:56.661Z - debug: OData query on data
2022-01-19T11:06:56.662Z - debug: OData query on assets
2022-01-19T11:06:56.663Z - error: Error when processing OData GET: /odata/assets?$select=isSharedHelper,scope,name,shortid,tags,folder&$orderby=name TypeError: Cannot read properties of undefined (reading 'forEach')
    at module.exports (/home/devops/jsreport02/node_modules/@jsreport/odata-to-sql/lib/query.js:54:28)
    at Object.query (/home/devops/jsreport02/node_modules/@jsreport/odata-to-sql/lib/transformer.js:46:14)
    at Cursor.toArray (/home/devops/jsreport02/node_modules/@jsreport/sql-store/lib/sqlProvider.js:22:29)
    at replay (/home/devops/jsreport02/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:51:21)
    at /home/devops/jsreport02/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:58:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-19T11:06:56.666Z - debug: OData query on scripts
2022-01-19T11:06:56.669Z - debug: OData query on schedules
2022-01-19T11:06:56.672Z - debug: OData query on settings

**Comment by pofider** [comment]
@shresthasan Please refere [here](https://forum.jsreport.net/topic/2272/jsreport-3-3-error-with-postgres-store/3)
