### ISSUE TITLE
An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by RLondhe82** [jsreport/jsreport#460]
I am getting following error whenever try to, either from ASP.NET MVC core or console application.
Please help to resolve the issue.

I need immediate solution as I stuck here.

JsReportBinaryException: Error rendering report: instance has been daemonized and initialized successfully (pid: 21824)A critical error occurred while trying to execute the render command: spawn EPERMlogs:+0 Starting rendering request 1 (user: null)+1 Rendering anonymous template { recipe: chrome-pdf, engine: none }+1 Data item not defined for this template.+2 Resources not defined for this template.+5 Base url injected: http://localhost:54700+5 Rendering engine none+37 Compiled template not found in the cache, compiling+39 Executing recipe chrome-pdf (1). caused by error (1) -> meta = {"remoteStack":"Error: spawn EPERM\n at _errnoException (util.js:1022:11)\n at ChildProcess.spawn (internal/child_process.js:323:11)\n at Object.exports.spawn (child_process.js:503:9)\n at Function.launch (jsreportRuntime.js:315048:40)\n at <anonymous>"}, stack = Error: at responseToBuffer ([eval]:45649:29) at concat ([eval]:45702:40) at ConcatStream.<anonymous> ([eval]:14359:43) at emitNone (events.js:111:20) at ConcatStream.emit (events.js:208:7) at finishMaybe ([eval]:92007:14) at afterWrite ([eval]:91869:3) at _combinedTickCallback (internal/process/next_tick.js:144:20) at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by pofider** [comment]
What platform/os do you use?

It seems it fails to start chrome process. Can you try to run it manually?
you should be able to find it here, when running windows.
c:\Users\xxx\AppData\Local\Temp\jsreport\

**Comment by pofider** [comment]
Closing because of inactivity. However feel free to add your comments.
