### ISSUE TITLE
The header content contains invalid characters. (File Name Problem)

### ISSUE THREAD

**Issue by umutc** [jsreport/jsreport#481]
Hello

This issue happens in this month while downloading the report via API.

When i remove the "Content-Type: application/json" in the headers everything works well. If this is not a problem that why is this is working previous versions and not working now?

**ERROR:**
```
{"message":"The header content contains invalid characters","stack":"TypeError: The header content contains invalid characters\n    at validateHeader (_http_outgoing.js:494:11)\n    at ServerResponse.setHeader (_http_outgoing.js:498:3)\n    at reporter.render.then (/usr/src/app/node_modules/jsreport-express/lib/routes.js:57:13)\n    at <anonymous>"}
```

**REQUEST:**
```
POST /api/report HTTP/1.1
Host: magistum.jsreportonline.net
Origin: https://app.magistum.com
Authorization: [Base64String]
Content-Type: application/json
Access-Control-Allow-Origin: *
accept: *.*
Referer: https://app.magistum.com/mae/exam/148/result
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Token: [MyAppToken]
cache-control: no-cache
{"template":{"shortid":"Hk0DywUK7"},"data": { "items": "data is too large to put here :)" }, "options":{"Content-Disposition":"attachment; filename=KDS 3  11 EŞİT AĞIR..pdf"}}------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

**Comment by umutc** [comment]
`"options": { "Content-Disposition": "attachment; filename=KAZANIM DEĞERLENDİRME 3A.pdf" }"` replaced with `"options": { "Content-Disposition": "attachment; filename=kazanimDegerlendirme3A.pdf" }"` and problem fixed at client side.
