### ISSUE TITLE
jsreport Error: Unable to find module

### ISSUE THREAD

**Issue by DanielAlonsoPardo** [jsreport/jsreport#487]
My problem is that I'm getting the 'unable to find module' error on a module that is installed right there.

```
Error while executing user script. Unable to find module survey-jquery
Searched paths: 
survey-jquery
survey-jquery
C:\Users\dalonsop\workdir\jsreport\survey-jquery
C:\Users\dalonsop\workdir\jsreport\survey-jquery
C:\Users\dalonsop\workdir\jsreport\node_modules\jsreport-cli\lib\survey-jquery
. 

> 1 | require("survey-jquery");
    | ^
  2 | 
  3 | __runBefore()
  4 | 


logs:
+0      Starting rendering request 1 (user: null)
+4      Rendering template { name: blank, recipe: chrome-pdf, engine: handlebars, preview: true }
+6      Data item not defined for this template.
+7      Resources not defined for this template.
+11     Executing script problem
Error: Unable to find module survey-jquery
Searched paths: 
survey-jquery
survey-jquery
C:\Users\dalonsop\workdir\jsreport\survey-jquery
C:\Users\dalonsop\workdir\jsreport\survey-jquery
C:\Users\dalonsop\workdir\jsreport\node_modules\jsreport-cli\lib\survey-jquery

    at doRequire (C:\Users\dalonsop\workdir\jsreport\node_modules\jsreport-core\lib\render\safeSandbox.js:213:11)
    at _require (C:\Users\dalonsop\workdir\jsreport\node_modules\jsreport-core\lib\render\safeSandbox.js:54:14)
    at Object.apply (C:\Users\dalonsop\workdir\jsreport\node_modules\vm2\lib/contextify.js:288:34)
    at evaluate-user-script.js:1:1
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (C:\Users\dalonsop\workdir\jsreport\node_modules\vm2\lib\main.js:212:72)
    at run (C:\Users\dalonsop\workdir\jsreport\node_modules\jsreport-core\lib\render\safeSandbox.js:171:19)
    at module.exports (C:\Users\dalonsop\workdir\jsreport\node_modules\jsreport-scripts\lib\scriptEvalChild.js:166:5)
    at IncomingMessage.<anonymous> (C:\Users\dalonsop\workdir\jsreport\node_modules\script-manager\lib\worker-servers.js:253:47)
    at emitNone (events.js:106:13)
```

I'm using a fresh install of jsreport. Running this:

```
nvm use 8.9.0   //minimum recommended on https://jsreport.net/on-prem
npm install jsreport-cli -g
jsreport init
jsreport configure //yes, http, 5488, no, yes everything saved on disk, yes, yes, no
npm install survey-jquery
npm i webpack@^3.0.0   // to resolve npm complaints about requiring peers
npm i  //for good measure
jsreport start //after configuring jsreport.config.json
```
Line added to jsreport.config.json (under extensions -> scripts):
`
      "allowedModules": "*",`
Then I create a blank template that uses the problem script containing just this line:
`require("survey-jquery");`

And I get that darn error. I have no idea what it can be, as the package 'survey-jquery' works on my other node projects. Making a copy of `node_modules/survey-jquery` doesn't work, either. According to some thread somewhere else[citation needed], any error in a required module causes jsreports to complain about not finding it at all. But since it works on other fresh node projects for me, and since I can't figure out how to get a more detailed error report that might shed more light on what is going on, I'm stumped big time.

Any fixes or workarounds I can try?

**Comment by pofider** [comment]
It seems survey-jquery needs to run in the browser. Not in the server based node.js

Try adding `const test = require('survey-jquery')` into server.js and start jsreport. 
You get this error:

```
PS C:\work\jsreport\jsreport> node server.js
C:\work\jsreport\jsreport\node_modules\survey-jquery\survey.jquery.js:28085
        for (var i = 0; i < document.styleSheets.length; i++) {
                            ^

ReferenceError: document is not defined
    at Function.StylesManager.findSheet (C:\work\jsreport\jsreport\node_modules\survey-jquery\survey.jquery.js:28085:29)
    at new StylesManager (C:\work\jsreport\jsreport\node_modules\survey-jquery\survey.jquery.js:28078:36)
    at C:\work\jsreport\jsreport\node_modules\survey-jquery\survey.jquery.js:17314:33
    at Object.<anonymous> (C:\work\jsreport\jsreport\node_modules\survey-jquery\survey.jquery.js:17317:2)
    at __webpack_require__ (C:\work\jsreport\jsreport\node_modules\survey-jquery\survey.jquery.js:35:30)
    at Object.<anonymous> (C:\work\jsreport\jsreport\node_modules\survey-jquery\survey.jquery.js:29639:67)
    at __webpack_require__ (C:\work\jsreport\jsreport\node_modules\survey-jquery\survey.jquery.js:35:30)
    at Object.<anonymous> (C:\work\jsreport\jsreport\node_modules\survey-jquery\survey.jquery.js:28692:72)
    at __webpack_require__ (C:\work\jsreport\jsreport\node_modules\survey-jquery\survey.jquery.js:35:30)
    at Object.<anonymous> (C:\work\jsreport\jsreport\node_modules\survey-query\survey.jquery.js:32606:68)
```

**Comment by DanielAlonsoPardo** [comment]
Thank you for the quick reply. This surprises me... it makes sense though. I wanted to leverage the 'survey-jquery' library to have it generate html for the chrome-pdf recipe to render. I'll have to come up with something, I'd appreciate any tips though.

I guess that closes this issue. How can one troubleshoot "unable to find module" errors though, does it have to be by executing the offending script on node? Is there any reason the real errors can't be shown on jsreport's errlog?

**Comment by bjrmatos** [comment]
>I wanted to leverage the 'survey-jquery' library to have it generate html for the chrome-pdf recipe to render. I'll have to come up with something, I'd appreciate any tips though.

i think you can still use the library but not inside an script, you can import it directly to your html page, you can do that with an [asset](https://jsreport.net/learn/assets) or with a link to some CDN, then use that library insice an html script tag of the template. if the library does something async then you should enable the [printing triggers](https://jsreport.net/learn/chrome-pdf#printing-triggers) in chrome so it can wait until your page is ready

> How can one troubleshoot "unable to find module" errors though, does it have to be by executing the offending script on node? Is there any reason the real errors can't be shown on jsreport's errlog?

we will fix that in this [issue](https://github.com/jsreport/jsreport/issues/488)

**Comment by DanielAlonsoPardo** [comment]
Fantastic, thank you very much.
