### ISSUE TITLE
(Recipe 'chrome-pdf' not found) error, when upload the website to IIS

### ISSUE THREAD

**Issue by khaledsale7** [jsreport/jsreport#508]
JSreport is working well in my local asp mvc application, but when i move it to IIS server it show an error message that chrome-pdf not found

Log:

10/03/2019 14:45:50 ==> Error rendering report: instance has been daemonized and initialized successfully (pid: 8416)rendering has finished with errors:Error: An error occurred while trying to execute the command:    at onCriticalError ([eval]:36086:25)    at [eval]:36041:13    at tryCatcher ([eval]:9718:23)    at Promise._settlePromiseFromHandler ([eval]:38221:31)    at Promise._settlePromise ([eval]:38278:18)    at Promise._settlePromise0 ([eval]:38323:10)    at Promise._settlePromises ([eval]:38398:18)    at Async._drainQueue ([eval]:4650:16)    at Async._drainQueues ([eval]:4660:10)    at Immediate.Async.drainQueues [as _onImmediate] ([eval]:4534:14)    at processImmediate [as _immediateCallback] (timers.js:396:17) {"originalError":{"remoteStack":"Error: Recipe 'chrome-pdf' not found\n    at jsreportRuntime.js:124986:13\n    at tryCatcher (jsreportRuntime.js:127974:23)\n    at Promise._settlePromiseFromHandler (jsreportRuntime.js:127667:31)\n    at Promise._settlePromise (jsreportRuntime.js:127724:18)\n    at Promise._settlePromise0 (jsreportRuntime.js:127769:10)\n    at Promise._settlePromises (jsreportRuntime.js:127848:18)\n    at Async._drainQueue (jsreportRuntime.js:41399:16)\n    at Async._drainQueues (jsreportRuntime.js:41409:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (jsreportRuntime.js:41283:14)\n    at processImmediate [as _immediateCallback] (timers.js:396:17)"}}(Original) **Error: Error during rendering report: Recipe 'chrome-pdf' not found**    at [eval]:39083:23    at ConcatStream.<anonymous> ([eval]:44805:43)    at emitNone (events.js:72:20)    at ConcatStream.emit (events.js:166:7)    at finishMaybe ([eval]:4229:14)    at afterWrite ([eval]:4115:3)    at nextTickCallbackWithManyArgs (node.js:486:18)    at process._tickCallback (node.js:384:17) {"remoteStack":"Error: Recipe 'chrome-pdf' not found\n    at jsreportRuntime.js:124986:13\n    at tryCatcher (jsreportRuntime.js:127974:23)\n    at Promise._settlePromiseFromHandler (jsreportRuntime.js:127667:31)\n    at Promise._settlePromise (jsreportRuntime.js:127724:18)\n    at Promise._settlePromise0 (jsreportRuntime.js:127769:10)\n    at Promise._settlePromises (jsreportRuntime.js:127848:18)\n    at Async._drainQueue (jsreportRuntime.js:41399:16)\n    at Async._drainQueues (jsreportRuntime.js:41409:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (jsreportRuntime.js:41283:14)\n    at processImmediate [as _immediateCallback] (timers.js:396:17)"}
10/03/2019 14:45:51 ==> Controller: Error Action: ErrorA potentially dangerous Request.QueryString value was detected from the client (message="...catStream.<anonymous> ([eval]:..."). && A potentially dangerous Request.QueryString value was detected from the client (message="...catStream.<anonymous> ([eval]:...").

**Comment by pofider** [comment]
What is the jsreport version you use? Do you use jsreport.exe binary with your wrapper? Or you use `jsreport.Local` nuget package?
