### ISSUE TITLE
Export from JSReport 1.7 and import to 2.4.0 causing error

### ISSUE THREAD

**Issue by samir-kamble** [jsreport/jsreport#549]
Facing this error while importing templates and their assets to JSReport latest from 1.7.0.

```
Error: Unable to read import.zip key from multipart stream
    at multer.array (jsreportRuntime.js:179363:17)
    at Array.<anonymous> (jsreportRuntime.js:291635:37)
    at listener (jsreportRuntime.js:307403:15)
    at onFinish (jsreportRuntime.js:307334:5)
    at callback (jsreportRuntime.js:85158:10)
    at IncomingMessage.onevent (jsreportRuntime.js:85196:5)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)... Error: Error: Unable to read import.zip key from multipart stream
    at multer.array (jsreportRuntime.js:179363:17)
    at Array.<anonymous> (jsreportRuntime.js:291635:37)
    at listener (jsreportRuntime.js:307403:15)
    at onFinish (jsreportRuntime.js:307334:5)
    at callback (jsreportRuntime.js:85158:10)
    at IncomingMessage.onevent (jsreportRuntime.js:85196:5)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)... 
```

**Comment by pofider** [comment]
Do you use import action from studio or you do it using your custom client?
Can you share that zip?

**Comment by samir-kamble** [comment]
Due to confidential terms Could not be able to share zip. still will check with authorities and revert back.

I am using import action from studio itself.

**Comment by pofider** [comment]
Maybe you can try to replicate it with some dummy templates and share it here....

**Comment by fmmich** [comment]
I ran into the same problem today trying to import _any_ zip file on an install of Jsreport 2.4 that I did last week.  I reran "npm install" to update the node modules, and that appeared resolved the problem.  I think one of jsreport's third-party module dependencies had a bad release that has since been fixed.

**Comment by samir-kamble** [comment]
I was able to do so by exporting every sections one by one. Like templates, data, scripts and assets.

**Comment by pofider** [comment]
Closing this as outdated.
Hopefully, it was fixed in an update in the dep as mentioned.
