### ISSUE TITLE
socket hang up during rendering 

### ISSUE THREAD

**Issue by afshin2003** [jsreport/jsreport#57]
Hi Guys,
In a new deployment I get "socket hang up" error whenever I run the Sample report template. It takes several minutes before throwing this error!

Error occured - Error during rendering report: socket hang up
Stack - Error: socket hang up
    at createHangUpError (http.js:1473:15)
    at Socket.socketOnEnd [as onend] (http.js:1569:23)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
From previous event:
    at Reporter.render (/opt/jsreport/node_modules/jsreport/lib/reporter.js:146:8)
    at /opt/jsreport/node_modules/jsreport/extension/express/lib/routes.js:139:18
    at Layer.handle [as handle_request] (/opt/jsreport/node_modules/jsreport/node_modules/express/lib/router/layer.js:82:5)
    at next (/opt/jsreport/node_modules/jsreport/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/opt/jsreport/node_modules/jsreport/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/opt/jsreport/node_modules/jsreport/node_modules/express/lib/router/layer.js:82:5)
    at /opt/jsreport/node_modules/jsreport/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/opt/jsreport/node_modules/jsreport/node_modules/express/lib/router/index.js:321:12)
    at next (/opt/jsreport/node_modules/jsreport/node_modules/express/lib/router/index.js:261:10)
    at /opt/jsreport/node_modules/jsreport/extension/authentication/lib/authentication.js:165:20
    at Layer.handle [as handle_request] (/opt/jsreport/node_modules/jsreport/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/opt/jsreport/node_modules/jsreport/node_modules/express/lib/router/index.js:302:13)
    at /opt/jsreport/node_modules/jsreport/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/opt/jsreport/node_modules/jsreport/node_modules/express/lib/router/index.js:321:12)

**Comment by pofider** [comment]
Hi,

what is your OS? What is the version of jsreport, the latest 0.4? Is the error occurring just for the first rendering or also for the second one?

I tried now windows and ubuntu 12 with the latest jsreport 0.4 and don't see this error.

**Comment by afshin2003** [comment]
Hi Pofider,
Thanks for your quick reply. It's an openvz container, debian 7.8 x86_64, Nodejs 0.10.34 and latest jsreport! The error is permanent!

**Comment by pofider** [comment]
Uh, somehow not able to run openvz...

Can you verify if it is running in some other environment for you?e

**Comment by afshin2003** [comment]
Right now I'm using it in my lab on an openvz container, ubuntu 12.04 amd64, Nodejs 0.12.2 !

**Comment by afshin2003** [comment]
For people who might get this error. This could happen if you miss the loop back network address (localhost / 127.0.0.1) on your machine!

**Comment by lazy-bug** [comment]
I am still getting this?

Error occured - Error during rendering report: socket hang up
Stack - Error: socket hang up
    at createHangUpError (http.js:1477:15)
    at Socket.socketOnEnd [as onend] (http.js:1573:23)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
From previous event:
    at Scripts.handleAfterRender (/root/jsreport/node_modules/jsreport/extension/scripts/lib/scripts.js:57:8)
    at /root/jsreport/node_modules/jsreport/lib/util/listenerCollection.js:121:41
    at /root/jsreport/node_modules/jsreport/lib/util/listenerCollection.js:100:24

**Comment by lazy-bug** [comment]
Note that if i generate pdf it works fine but when i generate html i get the above error!

**Comment by pofider** [comment]
Strange... And the html template is the same as the phantom pdf one? Don't you have a [script](http://jsreport.net/learn/scripts) associated with the template? Is this happening with the particular template or even with the blank report?
