### ISSUE TITLE
ensure node 10, 12 support

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport#578]
we should do a quick test, checking that we don't have problems when running on node 10, 12.

references jsreport/jsreport-phantom-pdf#32, jsreport/jsreport-phantom-pdf#35

**Comment by pofider** [comment]
I confirm the phantom-pdf can't be installed on node 12 (on win)

**Comment by taoqf** [comment]
Nor Linux.

> I confirm the phantom-pdf can't be installed on node 12 (on win)

**Comment by bjrmatos** [comment]
i fixed some problems with `jsreport-phantom-pdf` and now it should work in both node 10 and 12. it does for me on OSX. so installing new version of `jsreport-phantom-pdf@2.3.0` should work fine.

**Comment by taoqf** [comment]
I got this:

```log
warning Error running install script for optional dependency: "/home/taoqf/myproj/node_modules/phantomjs: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/taoqf/myproj/node_modules/phantomjs
Output:
Considering PhantomJS found at /usr/bin/phantomjs
Found PhantomJS at /usr/bin/phantomjs ...verifying
PhantomJS detected, but wrong version 2.1.1 @ /usr/bin/phantomjs.
Phantom installation failed TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:1037:7)
    at findSuitableTempDirectory (/home/taoqf/myproj/node_modules/phantomjs/install.js:127:30)
    at /home/taoqf/myproj/node_modules/phantomjs/install.js:476:19
    at nextTickCallback (/home/taoqf/myproj/node_modules/kew/kew.js:47:28)
    at processTicksAndRejections (internal/process/task_queues.js:75:11) TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:1037:7)
    at findSuitableTempDirectory (/home/taoqf/myproj/node_modules/phantomjs/install.js:127:30)
    at /home/taoqf/myproj/node_modules/phantomjs/install.js:476:19
    at nextTickCallback (/home/taoqf/myproj/node_modules/kew/kew.js:47:28)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)"
info This module is OPTIONAL, you can safely ignore this error
Done in 55.95s.
```

And I had phantomjs@2.1.1 installed on my machine

After I removed phantomjs, I got this Error:

```log
warning Error running install script for optional dependency: "/home/taoqf/myproj/node_modules/phantomjs: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/taoqf/myproj/node_modules/phantomjs
Output:
PhantomJS not found on PATH
Phantom installation failed TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:1037:7)
    at findSuitableTempDirectory (/home/taoqf/myproj/node_modules/phantomjs/install.js:127:30)
    at /home/taoqf/myproj/node_modules/phantomjs/install.js:476:19
    at nextTickCallback (/home/taoqf/myproj/node_modules/kew/kew.js:47:28)
    at processTicksAndRejections (internal/process/task_queues.js:75:11) TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:1037:7)
    at findSuitableTempDirectory (/home/taoqf/myproj/node_modules/phantomjs/install.js:127:30)
    at /home/taoqf/myproj/node_modules/phantomjs/install.js:476:19
    at nextTickCallback (/home/taoqf/myproj/node_modules/kew/kew.js:47:28)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)"
info This module is OPTIONAL, you can safely ignore this error
Done in 4.58s.
```

Is this the correct behavior?

**Comment by taoqf** [comment]
Is it possible use [phantom](https://www.npmjs.com/package/phantom)?

**Comment by bjrmatos** [comment]
weird, those errors are common when phantomjs were not installed properly, maybe there was an issue during installation and the phantom binary got corrupted or maybe it is not even there. maybe you can delete your node_modules and everything from scratch.

**Comment by taoqf** [comment]
@bjrmatos try install using `yarn`.

**Comment by taoqf** [comment]
@bjrmatos Are you still on this?

**Comment by bjrmatos** [comment]
yes, but i did not have the chance to test an install with yarn.. so i will try to do it when i finish some other tasks, i will post here the results

**Comment by taoqf** [comment]
I just come by, leave this message to let you know I am still keeping my eye on this.

**Comment by taoqf** [comment]
lalala

**Comment by bjrmatos** [comment]
@taoqf 	no time yet to check with yarn.. we are too busy preparing new release of jsreport. i will re-open the issue until that.

**Comment by pofider** [comment]
Works for me with node 12 and both yarn and npm.

**Comment by taoqf** [comment]
I've changed to use chrome long time ago. and have no time to test this recently.

**Comment by pofider** [comment]
I am closing this.
Please reopen if anyone still has this issue.
