### ISSUE TITLE
Custom logger and jsreport standalone executable 2.6.0

### ISSUE THREAD

**Issue by jakubin** [jsreport/jsreport#637]
In our setup we use jsreport standalone executable with config file. There we use "winston-daily-rotate-file" logger. The interesting part of config file is:
```
  "logger": {
    "file": {
      "module": "winston-daily-rotate-file",
      "transport": "DailyRotateFile",
      "level": "info",
      "filename": "reports-%DATE%.log",
      "datePattern": "YYYY-MM-DD",
      "maxFiles": "30d"
    }
```

This has worked correctly with 2.5.0. After upgrade to 2.6.0 I get failure on the `jsreport.exe start`:
```
2019-09-24T13:27:55.087Z - error: Error occured during reporter init Error: invalid option for transport object "file",
module "winston-daily-rotate-file" in "module" option could not be found. are you sure that you have installed it?. chec
k your "logger" config
    at module.exports._configureWinstonTransports.Object.keys.forEach (C:\snapshot\jsreport\node_modules\jsreport-core\l
ib\reporter.js:734:19)
    at Array.forEach (<anonymous>)
    at Reporter._configureWinstonTransports (C:\snapshot\jsreport\node_modules\jsreport-core\lib\reporter.js:669:29)
    at Reporter._initOptions (C:\snapshot\jsreport\node_modules\jsreport-core\lib\reporter.js:385:10)
An error has occurred when trying to initialize jsreport (2). invalid option for transport object "file", module "winsto
n-daily-rotate-file" in "module" option could not be found. are you sure that you have installed it?. check your "logger
" config (1).
caused by error (2) -> meta = {"disableExit":true}, stack = Error:
    at exports.initialize.instance.init.then.catch (C:\snapshot\jsreport\node_modules\jsreport-cli\lib\instanceHandler.j
s:31:29)
caused by error (1) -> stack = Error:
    at module.exports._configureWinstonTransports.Object.keys.forEach (C:\snapshot\jsreport\node_modules\jsreport-core\l
ib\reporter.js:734:19)
    at Array.forEach (<anonymous>)
    at Reporter._configureWinstonTransports (C:\snapshot\jsreport\node_modules\jsreport-core\lib\reporter.js:669:29)
    at Reporter._initOptions (C:\snapshot\jsreport\node_modules\jsreport-core\lib\reporter.js:385:10)
```

Any help is much appreciated.

**Comment by bjrmatos** [comment]
thanks for the issue report, you are right, our new exe (2.6.0) was having a problem with the require of modules that are part of local filesystem. this should be fixed in `2.6.1`, please download the executable for that version and try again. 

NOTE: be aware that we use winston 2.x.x so technically the last version of `winston-daily-rotate-file` (4.2.1) is not compatible with our logger, you have to install the 3.10.0 version of `winston-daily-rotate-file` which is the last version which supports winston 2.x.x instances
