### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by msageryd** [jsreport/jsreport#641]
This is not a big issue. Happened to me when I woke up my laptop with jsreport running in local Docker. Stuff tends to happen with Docker sometimes in this scenario.

But you should probably look into the error handling. Never good with unhandled rejections.

```
jsreport_1    | 2019-09-30T05:57:39.426Z - error: unable to load planned schedules Error: Timeout during waiting for file system, try it again later.
jsreport_1    |     at Object.rejectItemsWithTimeout (/app/node_modules/jsreport-fs-store/lib/queue.js:53:23)
jsreport_1    |     at Timeout._onTimeout (/app/node_modules/jsreport-fs-store/lib/provider.js:322:73)
jsreport_1    |     at listOnTimeout (internal/timers.js:531:17)
jsreport_1    |     at processTimers (internal/timers.js:475:7)
jsreport_1    | (node:15) UnhandledPromiseRejectionWarning: Error: Timeout during waiting for file system, try it again later.
jsreport_1    |     at Object.rejectItemsWithTimeout (/app/node_modules/jsreport-fs-store/lib/queue.js:53:23)
jsreport_1    |     at Timeout._onTimeout (/app/node_modules/jsreport-fs-store/lib/provider.js:322:73)
jsreport_1    |     at listOnTimeout (internal/timers.js:531:17)
jsreport_1    |     at processTimers (internal/timers.js:475:7)
jsreport_1    | (node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1524)
```

**Comment by pofider** [comment]
Thank you. Fixed.

**Comment by sahedribeiro** [comment]
On-Promise still not working and return the same error

**Comment by pofider** [comment]
@sahedribeiro Do you use the latest jsreport version? This should have been fixed.
