### ISSUE TITLE
Object <worksheet>...</worksheet> has no method 'indexOf'

### ISSUE THREAD

**Issue by havrlant** [jsreport/jsreport#65]
Hi,
I am trying to build a XLSX and I always get an error "Object <worksheet>...</worksheet> has no method 'indexOf'". I looked into it and I think the problem is with this code: `response.result.indexOf("<worksheet")` because `response.result` is a Buffer, not a String. I changed it to `var responseResult = response.result.toString();` and `responseResult.indexOf("<worksheet")` and it works perfectly. 

I tried the code from [the example](https://playground.jsreport.net/#/playground/YBjmBsPFa), engine: jsrender, recipe: xslt. Everything works fine on your playground but not on my localhost. I tried it on node 0.10 and 0.12. 

The error: 

```
Error occured - Error during rendering report: Object <worksheet
xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
    <dimension ref="A1"/>
    <sheetViews>
        <sheetView workbookViewId="0"/>
    </sheetViews>
    <sheetFormatPr defaultRowHeight="13.5"/>
    <cols>
        <col min="1" max="1" width="56" />
        <col min="2" max="2" width="18" />
    </cols>
    <sheetData>
        <row r="1">
            <c r="A1" t="inlineStr"><is><t>column 1</t></is></c>
            <c r="B1" t="inlineStr"><is><t>column 2</t></is></c>
        </row>
    </sheetData>
    <phoneticPr fontId="1" type="noConversion"/>
    <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>
    <pageSetup paperSize="9" orientation="portrait" horizontalDpi="200" verticalDpi="200"/>
</worksheet> has no method 'indexOf'
Stack - TypeError: Object <worksheet
xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
    <dimension ref="A1"/>
    <sheetViews>
        <sheetView workbookViewId="0"/>
    </sheetViews>
    <sheetFormatPr defaultRowHeight="13.5"/>
    <cols>
        <col min="1" max="1" width="56" />
        <col min="2" max="2" width="18" />
    </cols>
    <sheetData>
        <row r="1">
            <c r="A1" t="inlineStr"><is><t>column 1</t></is></c>
            <c r="B1" t="inlineStr"><is><t>column 2</t></is></c>
        </row>
    </sheetData>
    <phoneticPr fontId="1" type="noConversion"/>
    <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>
    <pageSetup paperSize="9" orientation="portrait" horizontalDpi="200" verticalDpi="200"/>
</worksheet> has no method 'indexOf'
    at /home/lukas/Desktop/reports/node_modules/jsreport/extension/xlsx/lib/xlsx.js:75:41
From previous event:
    at Reporter.render (/home/lukas/Desktop/reports/node_modules/jsreport/lib/reporter.js:146:8)
    at /home/lukas/Desktop/reports/node_modules/jsreport/extension/express/lib/routes.js:139:18
    at Layer.handle [as handle_request] (/home/lukas/Desktop/reports/node_modules/jsreport/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/lukas/Desktop/reports/node_modules/jsreport/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/home/lukas/Desktop/reports/node_modules/jsreport/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/home/lukas/Desktop/reports/node_modules/jsreport/node_modules/express/lib/router/layer.js:82:5)
    at /home/lukas/Desktop/reports/node_modules/jsreport/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/home/lukas/Desktop/reports/node_modules/jsreport/node_modules/express/lib/router/index.js:321:12)
    at next (/home/lukas/Desktop/reports/node_modules/jsreport/node_modules/express/lib/router/index.js:261:10)
    at serveStatic (/home/lukas/Desktop/reports/node_modules/jsreport/node_modules/serve-static/index.js:59:14)
    at Layer.handle [as handle_request] (/home/lukas/Desktop/reports/node_modules/jsreport/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/home/lukas/Desktop/reports/node_modules/jsreport/node_modules/express/lib/router/index.js:302:13)
    at /home/lukas/Desktop/reports/node_modules/jsreport/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/home/lukas/Desktop/reports/node_modules/jsreport/node_modules/express/lib/router/index.js:321:12)
```

**Comment by pofider** [comment]
Thanks Lukáši :)

You are absolutely correct. I fixed it as you proposed. 
I will publish it into npm with the next patch, If you depend on it let me know and I will push it ASAP.

**Comment by havrlant** [comment]
Thank you. It's OK, no rush, I can change it locally for the time being.
