### ISSUE TITLE
Optimize docx

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#652]
https://forum.jsreport.net/topic/1340/generate-large-docx-document-more-than-1000-pages

This export takes like 2minutes to render word doc with just 40pages and 30kb.
[export (29).zip](https://github.com/jsreport/jsreport/files/3832075/export.29.zip)

**Comment by bjrmatos** [comment]
we found the problem of the performance issue, turns out we were executing a regexp for every text node (`<w:t>`) in the document, and in this particular case the xml document produced after report rendering was having more than 8000 text nodes. for the record after the fix we have reduced the performance from `70s` -> `2s/3s` (on my local machine) that is like a 95% performance improvement for this case 😄

**Comment by meetvishalt** [comment]
https://playground.jsreport.net/w/meetvishalt/aQGUr9g8

Above playground sample generates maximum 700 page document when JsReport is started with 32GB RAM as below:
NODE_OPTIONS=--max-old-space-size=32768

I tried to spin up on 32GB linux centOS server and installed JsReport on it. I started Jsreport server with 32 GB memory on it and I could generate 700 pages of sample doc on it. 

For more than 700 pages document, it gives memory exhaust errors on jsreport console.
Above playground link has data for 800,900 and 1000 pages for you to try.

**Comment by pofider** [comment]
Thank you for the shared example.
We take a look if we can further optimize the recipe.

**Comment by meetvishalt** [comment]
Hi,

Below are the logs in console when started with garbage collector verbose logs.  --trace-gc-verbose

[5036:0000012A75D2AC90] Memory allocator,       used: 11022544 KB, available: 22581040 KB
[5036:0000012A75D2AC90] Read-only space,        used:     31 KB, available:    224 KB, committed:    256 KB
[5036:0000012A75D2AC90] New space,              used:     32 KB, available:  16334 KB, committed:  32768 KB
[5036:0000012A75D2AC90] New large object space, used:      0 KB, available:  16367 KB, committed:      0 KB
[5036:0000012A75D2AC90] Old space,              used: 8072171 KB, available:   1271 KB, committed: 8082284 KB
[5036:0000012A75D2AC90] Code space,             used:    999 KB, available:    147 KB, committed:   1440 KB
[5036:0000012A75D2AC90] Map space,              used:   1262 KB, available:    787 KB, committed:   2052 KB
[5036:0000012A75D2AC90] Large object space,     used: 2903034 KB, available:      0 KB, committed: 2903136 KB
[5036:0000012A75D2AC90] Code large object space,     used:    537 KB, available:      0 KB, committed:    608 KB
[5036:0000012A75D2AC90] All spaces,             used: 10978069 KB, available: 22616171 KB, committed: 11022544 KB
[5036:0000012A75D2AC90] Unmapper buffering 0 chunks of committed:      0 KB
[5036:0000012A75D2AC90] External memory reported: 300956 KB
[5036:0000012A75D2AC90] Backing store memory: 302294 KB
[5036:0000012A75D2AC90] External memory global 0 KB
[5036:0000012A75D2AC90] Total time spent in GC  : 112285.6 ms
[5036:0000012A75D2AC90] Fast promotion mode: false survival rate: 0%
[5036:0000012A75D2AC90]   344887 ms: Scavenge 10736.7 (10764.2) -> 10720.7 (10764.2) MB, 22.9 / 0.0 ms  (average mu = 0.361, current mu = 0.958) allocation failure
[5036:0000012A75D2AC90] Memory allocator,       used: 11022544 KB, available: 22581040 KB
[5036:0000012A75D2AC90] Read-only space,        used:     31 KB, available:    224 KB, committed:    256 KB
[5036:0000012A75D2AC90] New space,              used:      0 KB, available:  16366 KB, committed:  32768 KB
[5036:0000012A75D2AC90] New large object space, used:      0 KB, available:  16367 KB, committed:      0 KB
[5036:0000012A75D2AC90] Old space,              used: 8072172 KB, available:   1270 KB, committed: 8082284 KB
[5036:0000012A75D2AC90] Code space,             used:    999 KB, available:    147 KB, committed:   1440 KB
[5036:0000012A75D2AC90] Map space,              used:   1262 KB, available:    787 KB, committed:   2052 KB
[5036:0000012A75D2AC90] Large object space,     used: 2903034 KB, available:      0 KB, committed: 2903136 KB
[5036:0000012A75D2AC90] Code large object space,     used:    537 KB, available:      0 KB, committed:    608 KB
[5036:0000012A75D2AC90] All spaces,             used: 10978038 KB, available: 22616202 KB, committed: 11022544 KB
[5036:0000012A75D2AC90] Unmapper buffering 0 chunks of committed:      0 KB
[5036:0000012A75D2AC90] External memory reported: 300956 KB
[5036:0000012A75D2AC90] Backing store memory: 302294 KB
[5036:0000012A75D2AC90] External memory global 0 KB
[5036:0000012A75D2AC90] Total time spent in GC  : 112308.6 ms
[5036:0000012A75D2AC90] Fast promotion mode: false survival rate: 0%
[5036:0000012A75D2AC90]   344974 ms: Scavenge 10736.7 (10764.2) -> 10720.7 (10764.2) MB, 25.4 / 0.0 ms  (average mu = 0.361, current mu = 0.958) allocation failure
[5036:0000012A75D2AC90] Memory allocator,       used: 11022544 KB, available: 22581040 KB
[5036:0000012A75D2AC90] Read-only space,        used:     31 KB, available:    224 KB, committed:    256 KB
[5036:0000012A75D2AC90] New space,              used:     32 KB, available:  16334 KB, committed:  32768 KB
[5036:0000012A75D2AC90] New large object space, used:      0 KB, available:  16367 KB, committed:      0 KB
[5036:0000012A75D2AC90] Old space,              used: 8072172 KB, available:   1270 KB, committed: 8082284 KB
[5036:0000012A75D2AC90] Code space,             used:    999 KB, available:    147 KB, committed:   1440 KB
[5036:0000012A75D2AC90] Map space,              used:   1262 KB, available:    787 KB, committed:   2052 KB
[5036:0000012A75D2AC90] Large object space,     used: 2903034 KB, available:      0 KB, committed: 2903136 KB
[5036:0000012A75D2AC90] Code large object space,     used:    537 KB, available:      0 KB, committed:    608 KB
[5036:0000012A75D2AC90] All spaces,             used: 10978071 KB, available: 22616169 KB, committed: 11022544 KB
[5036:0000012A75D2AC90] Unmapper buffering 0 chunks of committed:      0 KB
[5036:0000012A75D2AC90] External memory reported: 300956 KB
[5036:0000012A75D2AC90] Backing store memory: 302294 KB
[5036:0000012A75D2AC90] External memory global 0 KB
[5036:0000012A75D2AC90] Total time spent in GC  : 112333.9 ms
[5036:0000012A75D2AC90] Fast promotion mode: false survival rate: 0%
[5036:0000012A75D2AC90]   345061 ms: Scavenge 10736.7 (10764.2) -> 10720.7 (10764.2) MB, 22.6 / 0.0 ms  (average mu = 0.361, current mu = 0.958) allocation failure
[5036:0000012A75D2AC90] Memory allocator,       used: 11022544 KB, available: 22581040 KB
[5036:0000012A75D2AC90] Read-only space,        used:     31 KB, available:    224 KB, committed:    256 KB
[5036:0000012A75D2AC90] New space,              used:     32 KB, available:  16334 KB, committed:  32768 KB
[5036:0000012A75D2AC90] New large object space, used:      0 KB, available:  16367 KB, committed:      0 KB
[5036:0000012A75D2AC90] Old space,              used: 8072173 KB, available:   1269 KB, committed: 8082284 KB
[5036:0000012A75D2AC90] Code space,             used:    999 KB, available:    147 KB, committed:   1440 KB
[5036:0000012A75D2AC90] Map space,              used:   1262 KB, available:    787 KB, committed:   2052 KB
[5036:0000012A75D2AC90] Large object space,     used: 2903034 KB, available:      0 KB, committed: 2903136 KB
[5036:0000012A75D2AC90] Code large object space,     used:    537 KB, available:      0 KB, committed:    608 KB
[5036:0000012A75D2AC90] All spaces,             used: 10978072 KB, available: 22616168 KB, committed: 11022544 KB
[5036:0000012A75D2AC90] Unmapper buffering 0 chunks of committed:      0 KB
[5036:0000012A75D2AC90] External memory reported: 300956 KB
[5036:0000012A75D2AC90] Backing store memory: 302294 KB
[5036:0000012A75D2AC90] External memory global 0 KB
[5036:0000012A75D2AC90] Total time spent in GC  : 112356.5 ms

<--- Last few GCs --->

[5036:0000012A75D2AC90]   344887 ms: Scavenge 10736.7 (10764.2) -> 10720.7 (10764.2) MB, 22.9 / 0.0 ms  (average mu = 0.361, current mu = 0.958) allocation failure
[5036:0000012A75D2AC90]   344974 ms: Scavenge 10736.7 (10764.2) -> 10720.7 (10764.2) MB, 25.4 / 0.0 ms  (average mu = 0.361, current mu = 0.958) allocation failure
[5036:0000012A75D2AC90]   345061 ms: Scavenge 10736.7 (10764.2) -> 10720.7 (10764.2) MB, 22.6 / 0.0 ms  (average mu = 0.361, current mu = 0.958) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF6A099404D]
Security context: 0x02e1572008a1 <JSObject>
    1: push [000002E157211079](this=0x037ccac2f821 <JSArray[96544198]>,0x005985686709 <String[#1]:  >,0x014a9c4c5b19 <String[7]: w:ascii>,0x005985687731 <String[#2]: =">,0x014a9c4c5b59 <String[9]: Helvetica>,0x005985687749 <String[#1]: ">)
    2: serializeToString [0000031A391C9281] [c:\jsreportapp\node_modules\xmldom\dom.js:~967] [pc=0000033CF25043D6](thi...

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 00007FF69FDC124F napi_wrap+124431
 2: 00007FF69FD62A06 v8::base::CPU::has_sse+34502
 3: 00007FF69FD636C6 v8::base::CPU::has_sse+37766
 4: 00007FF6A05682DE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6A0550321 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF6A041DBEC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF6A0433C0D v8::internal::Factory::AllocateRawFixedArray+61
 8: 00007FF6A043AFC4 v8::internal::Factory::NewFixedArrayWithFiller+52
 9: 00007FF6A043AF81 v8::internal::Factory::NewUninitializedFixedArray+65
10: 00007FF6A030BEDF v8::internal::FeedbackNexus::ic_state+57215
11: 00007FF6A031DE39 v8::Object::GetIsolate+15097
12: 00007FF6A03012AE v8::internal::FeedbackNexus::ic_state+13134
13: 00007FF6A02C1C47 v8::internal::JSObject::AddDataElement+999
14: 00007FF6A027FA4F v8::internal::PrototypeUsers::Add+1983
15: 00007FF6A029AC0D v8::internal::Object::SetProperty+237
16: 00007FF6A0193C7F v8::internal::Runtime::SetObjectProperty+303
17: 00007FF6A0193195 v8::internal::Runtime::GetObjectProperty+17637
18: 00007FF6A099404D v8::internal::SetupIsolateDelegate::SetupHeap+567949
19: 00007FF6A0938583 v8::internal::SetupIsolateDelegate::SetupHeap+192451
20: 0000033CF25043D6

**Comment by pofider** [comment]
Thank you, we have enough information already.
During the post-processing of the final xml, we are loading it into the memory DOM and this reaches memory limits. We need to find a better streamy way to do this.

**Comment by meetvishalt** [comment]
Hi Jan,

Thanks for your response.

This large document requirement is becoming one of the most critical requirement of our project. 
I understand you might be working on few other stuff. Can you give me some tentative date by when I can expect a fix.

Appreciate your help !!!
Wish you a merry Christmas and happy holidays !!!
Vishal

**Comment by pofider** [comment]
The work is in progress. Literally at this moment. However, I have no clue when there will be some results. So no promises for a date. Hopefully at the very beginning of January.
Merry Christmas

**Comment by pofider** [comment]
I prototyped the optimization of the docx. It is still very early, though. 
`docxStyle` isn't working, `docxPageBreak` only in the limited form...

I observed 8x speed improvement and also no memory problems with your reports.
I was able to render all of them without modifying the nodejs memory limit.

Note that the output reports hits the size restriction of the office online. Please use the download button in jsreport studio when rendering.
Also, note it takes like 10minutes to open the output in the desktop Microsoft word (windows).
What do you want to do with such a report?

You can try the prototype using
```
npm i jsreport/jsreport-docx#optimization
```

**Comment by Kzhd** [comment]
Hi Jan,

Thanks for all your help, Happy new year and thanks for providing update on Optimixe docx #652 issue.

As recommended on your post I have installed optimized version of docx using npm i jsreport/jsreport-docx#optimization and then I tried to generate a 1000 pages report using default node memory which gave me same Memory heap allocation error.

As per the Jsreport official documentation I have increased the node memory size to 8GB using node --max-old-space-size=8192 server.js and I  was able to  generate a report of up to 1000 pages. However , when I tried for 2000 pages , the jsreport generates an error “Error: socket hang up at Object.callbackRequests.<computed>”. 

What do you want to do with such a report?
We are helping an insurance client to  generate a report using Jsreport and one of the edge conditions is to generate a claim with more than 2000 pages of data. 

For now as a work around we tried changing the templatingEngines - strategy property from  "http-server"   to “in-process” and  we were able to generate a report for 2000 Pages :-) . Is it safe to use  templatingEngines - strategy property as “in-process” for production scenarios ?

Here are the logs : 

JSReport Studio Error:

Error: socket hang up
    at Object.callbackRequests.<computed> (C:\jsreportapp\node_modules\script-manager\lib\worker-servers.js:250:31)
    at process.<anonymous> (C:\jsreportapp\node_modules\script-manager\lib\worker-servers.js:195:30)
    at process.emit (events.js:215:7)
    at process.EventEmitter.emit (domain.js:476:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

Console Logs From JsReport:

2020-01-08T10:19:51.780Z - info: Starting rendering request 1 (user: null)
2020-01-08T10:19:51.792Z - info: Rendering template { name: HCFA, recipe: docx, engine: handlebars, preview: true }
2020-01-08T10:19:51.811Z - debug: Adding sample data Hye6gClQgU
2020-01-08T10:19:52.091Z - debug: Resources not defined for this template.
2020-01-08T10:19:52.158Z - debug: Base url not specified, skipping its injection.
2020-01-08T10:19:52.307Z - debug: Rendering engine handlebars
2020-01-08T10:19:53.785Z - debug: Compiled template not found in the cache, compiling
2020-01-08T10:19:53.796Z - debug: Executing recipe docx
2020-01-08T10:19:53.804Z - info: docx generation is starting
2020-01-08T10:19:57.700Z - debug: Starting child request to render docx dynamic parts
2020-01-08T10:19:57.710Z - info: Starting rendering request 2 (user: null)
2020-01-08T10:19:57.714Z - info: Rendering anonymous template { recipe: html, engine: handlebars }
2020-01-08T10:19:57.719Z - debug: Inline data specified.
2020-01-08T10:19:57.726Z - debug: Resources not defined for this template.
2020-01-08T10:19:57.729Z - debug: Base url not specified, skipping its injection.
2020-01-08T10:19:57.739Z - debug: Rendering engine handlebars
2020-01-08T10:20:22.578Z - warn: Error when processing render request socket hang up Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at Socket.socketOnEnd (_http_client.js:440:23)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2020-01-08T10:20:22.585Z - warn: Error when processing render request socket hang up Error: socket hang up
    at Object.callbackRequests.<computed> (C:\jsreportapp\node_modules\script-manager\lib\worker-servers.js:250:31)
    at process.<anonymous> (C:\jsreportapp\node_modules\script-manager\lib\worker-servers.js:195:30)
    at process.emit (events.js:215:7)
    at process.EventEmitter.emit (domain.js:476:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
2020-01-08T10:20:22.594Z - warn: Error during processing request at http://localhost:5488/api/report/HCFA

**Comment by pofider** [comment]
> and we were able to generate a report for 2000 Pages

How do you even open such a file in word? app :)

> Is it safe to use templatingEngines - strategy property as “in-process” for production scenarios ?

It is used in prod environments quite often. However..

The extra process makes it harder for the eventual attacker to breakthrough. 
However, the jsreport is typically behind some kind of corporate firewall and only developers can edit templates. In this case, it isn't expected an attacker to get in.

The in-process strategy doesn't allow parallelization. This means a single request producing the docx blocks the other requests. 

---
We will continue with investments into optimization.

**Comment by Kzhd** [comment]
Hi Jan,

Thanks for all your help.

**How do you even open such a file in word? app :)**
To answer your question we use Microsoft Word 2019 to view the reports.

Is it recommended to use JsReport as dockerized service or as a standalone server for higher payloads?

**Comment by pofider** [comment]
> To answer your question we use Microsoft Word 2019 to view the reports.

I mean it takes so long, like 20 minutes, to open these giant documents in Microsoft Word 2019 on my desktop.

> Is it recommended to use JsReport as dockerized service or as a standalone server for higher payloads?

No recommendation. There is likely no big difference for performance these options provides.

---
The optimization branch is now merged to the master so you can get it using `npm i jsreport/jsreport-docx`. This will be also part of the upcoming jsreport 2.7.0 release. We will do another optimization afterward. It will be about writing the xml segments into files during loops and do the recipe processing on the isolated segments. This will decrease the memory consumption of the recipe. However, don't expect here further improvements to the processing timespan.

**Comment by pofider** [comment]
The optimized docx recipe is now part of the 2.7.0.
We plan some further improvements but we do it in an extra task.
