### ISSUE TITLE
Error during rendering report: read ECONNRESET

### ISSUE THREAD

**Issue by miquelescolar** [jsreport/jsreport#67]
Hi,

We get the following error in our jsreport on-prem installation when input data size was 600kB or more. We test the same template in the playground environment and it works fine. Any hints? It could be a configuration issue, but we don't know.

thanks in advance

Error occured - Error during rendering report: read ECONNRESET
Stack - Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
From previous event:
    at Reporter.renderContent (/opt/nodejs/jsreport/node_modules/jsreport/lib/reporter.js:188:38)
    at Object.reporter.extensionsManager.recipes.push.execute (/opt/nodejs/jsreport/node_modules/jsreport/extension/html/lib/html.js:17:29)
    at Reporter.executeRecipe (/opt/nodejs/jsreport/node_modules/jsreport/lib/reporter.js:170:19)
    at q.then.then.then.then.then.then.then.response.result.toBuffer (/opt/nodejs/jsreport/node_modules/jsreport/lib/reporter.js:142:21)

**Comment by pofider** [comment]
Hi,

I have a failing test for it now and searching for a way how to fix it.

Thanks.

**Comment by miquelescolar** [comment]
I patched manually worker.js using code of the referenced issue and it works fine.
Thx.

**Comment by pofider** [comment]
Excellent. Thanks for letting me know. There should be official release tomorrow and this will be inside.
