### ISSUE TITLE
Disabled studio extension breaks start.

### ISSUE THREAD

**Issue by eXoSaX** [jsreport/jsreport#678]
When I disable **studio** extension in **jsreport.config.js** jsreport fails to start:

```
2020-01-14T11:33:11.609Z - info: html-to-xlsx detected chrome as available html engine
2020-01-14T11:33:11.610Z - info: Using extension assets@1.5.1
2020-01-14T11:33:11.621Z - info: Using extension studio-theme-dark@0.2.0
2020-01-14T11:33:11.626Z - error: Error when loading extension studio-theme-dark@0.2.0
TypeError: Cannot read property 'registerTheme' of undefined
    at Object.module.exports (C:\Workspaces\jsreport-test\node_modules\jsreport-studio-theme-dark\lib\main.js:4:19)
    at Object._useOne (C:\Workspaces\jsreport-test\node_modules\jsreport-core\lib\extensions\extensionsManager.js:194:75)
    at Object._useMany (C:\Workspaces\jsreport-test\node_modules\jsreport-core\lib\extensions\extensionsManager.js:98:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-01-14T11:33:11.629Z - error: Error occured during reporter init Error: Error when loading extension studio-theme-dark@0.2.0
```

A workaround for this issue is to disable **studio-theme-dark** also.

**Comment by pofider** [comment]
Thank you for the bug report.

This has been already fixed [here](https://github.com/jsreport/jsreport-studio-theme-dark/commit/f525016e4175b6da74439703f5d0f26c81b9ccaa). It will be part of the jsreport 2.7.0.

Keep your workaround or get the git version of the jsreport-studio-theme-dark
