### ISSUE TITLE
Error when processing render request Cannot set property offset of [object Object] which has only a getter

### ISSUE THREAD

**Issue by ChristophWieske** [jsreport/jsreport#703]
Hello there,

I try using the pptx recipe (I know it is experimental, but it works pretty awesome). So my scenario looks like that:

We send a common data package per Post
We also send the template pptx as a base64 encoded string along.

Until here it works as expected. **Pretty cool!**

We now want to add a script to transform data to ease usage in the template. And here it breaks.

That is the error displayed on the console:
```
2020-03-06T09:37:28.234Z - error: Error when processing render request Cannot set property offset of [object Object] which has only a getter TypeError: Cannot set property offset of [object Object] which has only a getter
    at merge (C:\inetpub\wwwroot\jsreportapp\node_modules\jsreport-scripts\lib\scripts.js:141:20)
    at merge (C:\inetpub\wwwroot\jsreportapp\node_modules\jsreport-scripts\lib\scripts.js:143:11)
    at merge (C:\inetpub\wwwroot\jsreportapp\node_modules\jsreport-scripts\lib\scripts.js:143:11)
    at merge (C:\inetpub\wwwroot\jsreportapp\node_modules\jsreport-scripts\lib\scripts.js:143:11)
    at merge (C:\inetpub\wwwroot\jsreportapp\node_modules\jsreport-scripts\lib\scripts.js:143:11)
    at Scripts._executeScript (C:\inetpub\wwwroot\jsreportapp\node_modules\jsreport-scripts\lib\scripts.js:151:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
2020-03-06T09:37:28.238Z - error: Error when processing render request Cannot set property offset of [object Object] which has only a getter TypeError: Cannot set property offset of [object Object] which has only a getter
    at merge (C:\inetpub\wwwroot\jsreportapp\node_modules\jsreport-scripts\lib\scripts.js:141:20)
    at merge (C:\inetpub\wwwroot\jsreportapp\node_modules\jsreport-scripts\lib\scripts.js:143:11)
    at merge (C:\inetpub\wwwroot\jsreportapp\node_modules\jsreport-scripts\lib\scripts.js:143:11)
    at merge (C:\inetpub\wwwroot\jsreportapp\node_modules\jsreport-scripts\lib\scripts.js:143:11)
    at merge (C:\inetpub\wwwroot\jsreportapp\node_modules\jsreport-scripts\lib\scripts.js:143:11)
    at Scripts._executeScript (C:\inetpub\wwwroot\jsreportapp\node_modules\jsreport-scripts\lib\scripts.js:151:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
2020-03-06T09:37:28.240Z - error: Error during processing request at http://rzvbitrep01:3000/api/report
```

The json body I send with the post is attached as a text file.

[json.txt](https://github.com/jsreport/jsreport/files/4297782/json.txt)

My jsReport version is 2.6.1

**Comment by ChristophWieske** [comment]
Oh, and even when I not access `req` at all. The error occurs.

**Comment by ChristophWieske** [comment]
Ok, have seen that there were newer versions of jsreport and jsreport-pptx.

Updated to jsreport@2.7.1 and jsreport-pptx@0.5.0

Now it runs. Nice work!
