### ISSUE TITLE
Templates with same name

### ISSUE THREAD

**Issue by SlavaUtesinov** [jsreport/jsreport#781]
I use jsreport with [jsreport-mssql-store](https://github.com/jsreport/jsreport-mssql-store). When I create templates via odata api concurently I can create several templates with **same** name. After that when I will be generating report specifing template name I will get response like this:

```
{
    "error": {
        "code": "DUPLICATED_ENTITY",
        "message": "Entity with name \"TemplateName\" already exists at the root level.",
        "stack": "Error: Entity with name \"TemplateName\" already exists at the root level.\n    at module.exports (/app/node_modules/jsreport-core/lib/util/createError.js:11:13)\n    at Reporter.createError (/app/node_modules/jsreport-core/lib/reporter.js:332:12)\n    at validateDuplicatedName (/app/node_modules/jsreport-core/lib/folders/validateDuplicatedName.js:87:20)",
        "target": "/templates?$select=name",
        "details": []
    },
    "innererror": {}
}
```

**Comment by pofider** [comment]
Yes, we don't handle concurrency here. We validate and insert in two steps. We will plan to solve this later and keep it in the backlog for now.

Is this for you a critical thing? Now you need to manually delete the duplicated item.
