### ISSUE TITLE
Failed to launch chrome!

### ISSUE THREAD

**Issue by iii-james** [jsreport/jsreport#812]
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```
```
jsreport : 2.11.0
```

After running `sudo apt-get update`  then `sudo  apt-get upgrade` commands on my ubuntu server any templates using the recipe chrome-pdf no longer work. Any Ideas?
```
Error: Failed to launch chrome!
/srv/jsreportapp/node_modules/puppeteer/.local-chromium/linux-706915/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/srv/jsreportapp/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.helper.addEventListener (/srv/jsreportapp/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19
```

**Comment by pofider** [comment]
Please try the following
```
sudo apt-get install -y libxtst6 libxss1
```

**Comment by iii-james** [comment]
Seems to have fixed the issue. Thanks!
