### ISSUE TITLE
@jsreport/jsreport-postgres-store

### ISSUE THREAD

**Issue by shresthasan** [jsreport/jsreport#858]
Hi, installed jsreport/jsreport-postgres-store v3. when running jsreport it throws OData error. before storing any store-extension jsreport works perfectly fine . i used this link for installing extension https://github.com/jsreport/jsreport/tree/master/packages  and used think for installing jsreport https://jsreport.net/learn/centos

Here is ISSUES

[devops@localhost jsreport02]$ node server.js 
2022-01-19T11:06:50.901Z - info: Initializing jsreport (version: 3.3.0, configuration file: jsreport.config.json, nodejs: 16.13.0)
2022-01-19T11:06:50.903Z - info: Searching for available extensions in /home/devops/jsreport02/
2022-01-19T11:06:50.916Z - info: Extensions location cache contains up to date information, skipping crawling in /home/devops/jsreport02/
2022-01-19T11:06:50.923Z - info: Found 36 extension(s)
2022-01-19T11:06:50.945Z - debug: Writing extension locations cache to /tmp/jsreport/core/locations.json
2022-01-19T11:06:50.946Z - debug: Discovered 36 extensions
2022-01-19T11:06:51.006Z - debug: Extension authentication@3.2.0 is disabled, skipping
2022-01-19T11:06:51.007Z - info: Using extension base@3.0.0
2022-01-19T11:06:51.012Z - info: Using extension child-templates@3.0.1
2022-01-19T11:06:51.015Z - info: Using extension cli@3.0.0
2022-01-19T11:06:51.017Z - info: Using extension components@3.2.0
2022-01-19T11:06:51.018Z - info: Using extension data@3.0.1
2022-01-19T11:06:51.019Z - info: Using extension express@3.2.1
2022-01-19T11:06:51.192Z - info: Using extension freeze@3.0.1
2022-01-19T11:06:51.194Z - info: Using extension fs-store@3.0.0
2022-01-19T11:06:51.243Z - info: Using extension handlebars@3.0.0
2022-01-19T11:06:51.245Z - info: Using extension import-export@3.0.2
2022-01-19T11:06:51.253Z - info: Using extension jsrender@3.0.0
2022-01-19T11:06:51.253Z - info: Using extension licensing@3.0.1
2022-01-19T11:06:51.270Z - info: Using extension localization@3.1.1
2022-01-19T11:06:51.270Z - info: Using extension npm@3.1.0
2022-01-19T11:06:51.273Z - info: Using extension pdf-utils@3.2.0
2022-01-19T11:06:51.274Z - info: Using extension postgres-store@3.0.0
2022-01-19T11:06:51.361Z - info: Using extension reports@3.0.1
2022-01-19T11:06:51.363Z - info: Using extension tags@3.1.0
2022-01-19T11:06:51.364Z - info: Using extension text@3.0.0
2022-01-19T11:06:51.365Z - info: Using extension version-control@3.0.1
2022-01-19T11:06:51.373Z - info: Using extension assets@3.2.0
2022-01-19T11:06:51.380Z - info: Using extension authorization@3.2.0
2022-01-19T11:06:51.382Z - debug: Extension authorization@3.2.0 was disabled
2022-01-19T11:06:51.382Z - info: Using extension browser-client@3.1.0
2022-01-19T11:06:51.383Z - info: Using extension chrome-pdf@3.1.0
2022-01-19T11:06:51.386Z - debug: Chrome strategy is chrome-pool, numberOfWorkers: 1
2022-01-19T11:06:51.386Z - debug: Chrome custom launch options are args=--no-sandbox, executablePath=/opt/google/chrome-unstable/chrome
2022-01-19T11:06:51.386Z - info: Using extension docx@3.1.0
2022-01-19T11:06:51.388Z - info: Using extension html-to-xlsx@3.1.0
2022-01-19T11:06:51.438Z - info: html-to-xlsx detected chrome as available html engine
2022-01-19T11:06:51.438Z - info: Using extension pptx@3.1.0
2022-01-19T11:06:51.440Z - info: Using extension scheduling@3.0.1
2022-01-19T11:06:51.472Z - info: Using extension scripts@3.2.0
2022-01-19T11:06:51.472Z - info: Using extension static-pdf@3.0.0
2022-01-19T11:06:51.473Z - info: Using extension studio@3.3.0
2022-01-19T11:06:51.527Z - info: Using extension xlsx@3.1.0
2022-01-19T11:06:51.547Z - info: Using extension public-templates@3.0.0
2022-01-19T11:06:51.548Z - debug: Extension public-templates@3.0.0 was disabled
2022-01-19T11:06:51.548Z - info: Using extension sample-template@3.1.0
2022-01-19T11:06:51.550Z - info: Using extension studio-theme-dark@3.0.1
2022-01-19T11:06:51.551Z - info: Using general timeout for rendering (reportTimeout: 60000)
2022-01-19T11:06:51.551Z - info: Using postgres provider for template store.
2022-01-19T11:06:51.604Z - debug: studio default theme is: light
2022-01-19T11:06:51.616Z - info: Creating default express app.
2022-01-19T11:06:51.629Z - info: jsreport server successfully started on http port: 5488
2022-01-19T11:06:51.631Z - info: Verifying license key free
2022-01-19T11:06:51.633Z - info: Using free license
2022-01-19T11:06:51.641Z - debug: Creating samples is disabled
2022-01-19T11:06:51.642Z - info: Initializing worker threads
2022-01-19T11:06:51.642Z - debug: Extensions in workers: base, child-templates, components, data, express, handlebars, jsrender, localization, npm, pdf-utils, reports, text, version-control, assets, browser-client, chrome-pdf, docx, html-to-xlsx, pptx, scripts, static-pdf, studio, xlsx
2022-01-19T11:06:51.818Z - info: 2 worker threads initialized in 176ms
2022-01-19T11:06:51.819Z - info: Starting temp files cleanup with 180000ms threshold
2022-01-19T11:06:51.819Z - info: reporter initialized
2022-01-19T11:06:56.642Z - debug: OData query on templates
2022-01-19T11:06:56.655Z - debug: OData query on tags
2022-01-19T11:06:56.658Z - debug: OData query on folders
2022-01-19T11:06:56.660Z - debug: OData query on components
2022-01-19T11:06:56.661Z - debug: OData query on data
2022-01-19T11:06:56.662Z - debug: OData query on assets
2022-01-19T11:06:56.663Z - error: Error when processing OData GET: /odata/assets?$select=isSharedHelper,scope,name,shortid,tags,folder&$orderby=name TypeError: Cannot read properties of undefined (reading 'forEach')
    at module.exports (/home/devops/jsreport02/node_modules/@jsreport/odata-to-sql/lib/query.js:54:28)
    at Object.query (/home/devops/jsreport02/node_modules/@jsreport/odata-to-sql/lib/transformer.js:46:14)
    at Cursor.toArray (/home/devops/jsreport02/node_modules/@jsreport/sql-store/lib/sqlProvider.js:22:29)
    at replay (/home/devops/jsreport02/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:51:21)
    at /home/devops/jsreport02/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:58:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-19T11:06:56.666Z - debug: OData query on scripts
2022-01-19T11:06:56.669Z - debug: OData query on schedules
2022-01-19T11:06:56.672Z - debug: OData query on settings

**Comment by pofider** [comment]
Please refer [here](https://forum.jsreport.net/topic/2272/jsreport-3-3-error-with-postgres-store/3)

**Comment by shresthasan** [comment]
i found solution, i dont know how but changing on jsreport.config.json file . instead of storage provide mentioning postgres leave as fs. it works fine.

here is my jsreport.config.json
[devops@localhost jsreport]$ vim jsreport.config.json

{
  "blobStorage": {
    "provider": "fs"
  },
  "logger": {
    "console": {
      "transport": "console",
      "level": "debug"
    },
    "file": {
      "transport": "file",
      "level": "info",
      "filename": "logs/reporter.log"
    },
    "error": {
      "transport": "file",
      "level": "error",
      "filename": "logs/error.log"
    }
  },
  "allowLocalFilesAccess": true,
  "reportTimeout": 60000,
  "templatingEngines": {
    "strategy": "http-server"
  },

  "extensions": {
    "authentication": {
      "cookieSession": {},
      "admin": {
        "username": "admin",
        "password": "password"
      },
      "enabled": false
    },
  "html-to-xlsx": {
   "timeout": 30000
  },
         "chrome-pdf": {
        "timeout":60000,
    "launchOptions": {
      "args": ["--no-sandbox"],
        "executablePath": "/opt/google/chrome-unstable/chrome"
    }
   },
        "wkhtmltopdf": {
            "allowLocalFilesAccess": true
        },
                "postgres-store": {
            "host": "10.5.26.101",
            "port": 5432,
            "database": "jsreport",
            "user": "jsreport",
            "password": "devops*977SS",
            "ssl": true
        },
        "phantom": {
            "numberOfWorkers": 5,
            "timeout": 180000,
            "allowLocalFilesAccess": false,
            "defaultPhantomjsVersion": "1.9.8"
        }
},
    "httpPort": 5488,
    "store": {
        "provider": "fs"
    },
    "sample-template": {
      "createSamples": true
    },
    "scripts": {
      "strategy": "http-server"
    }
}
===============
and these are the packages installed
[devops@localhost jsreport]$ npm ls --depth=0
jsreport-server@ /home/devops/jsreport
├── @jsreport/client@3.0.0-beta.1
├── @jsreport/jsreport-phantom-pdf@3.0.0
├── core-js@3.20.3
├── handlebars-intl@1.1.2
├── handlebars@4.7.7
├── jsreport-core@2.10.1
├── jsreport@3.3.0
├── phantomjs-exact-2-1-1@0.1.0
├── puppeteer@13.1.1
└── uuid@8.3.2
=====================================

**Comment by shresthasan** [comment]
now i have new issues jsreport/jsreport-phantom-pdf is not working .

=============================================
2022-01-20T10:51:51.989Z - debug: Adding sample data Sy5S19ncg rootId=3kwbi5m9bmcl61e, id=3kwbi5m9bmcl61e
2022-01-20T10:51:51.990Z - debug: Base url not specified, skipping its injection. rootId=3kwbi5m9bmcl61e, id=3kwbi5m9bmcl61e
2022-01-20T10:51:51.991Z - debug: Rendering engine handlebars rootId=3kwbi5m9bmcl61e, id=3kwbi5m9bmcl61e
2022-01-20T10:51:52.346Z - error: Report render failed: Cannot find module 'phantomjs'
Require stack:
- /home/devops/jsreport/node_modules/phantom-html-to-pdf/lib/dedicatedProcessStrategy.js
- /home/devops/jsreport/node_modules/phantom-html-to-pdf/lib/conversion.js
- /home/devops/jsreport/node_modules/phantom-html-to-pdf/index.js
- /home/devops/jsreport/node_modules/@jsreport/jsreport-phantom-pdf/lib/recipe.js
- /home/devops/jsreport/node_modules/@jsreport/jsreport-phantom-pdf/lib/worker.js
- /home/devops/jsreport/node_modules/@jsreport/jsreport-core/lib/worker/extensionsManager.js
- /home/devops/jsreport/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js
- /home/devops/jsreport/node_modules/@jsreport/jsreport-core/lib/worker/workerHandler.js
- /home/devops/jsreport/node_modules/@jsreport/advanced-workers/lib/workerHandler.js Error: Cannot find module 'phantomjs'
Require stack:
- /home/devops/jsreport/node_modules/phantom-html-to-pdf/lib/dedicatedProcessStrategy.js
- /home/devops/jsreport/node_modules/phantom-html-to-pdf/lib/conversion.js
- /home/devops/jsreport/node_modules/phantom-html-to-pdf/index.js
- /home/devops/jsreport/node_modules/@jsreport/jsreport-phantom-pdf/lib/recipe.js
- /home/devops/jsreport/node_modules/@jsreport/jsreport-phantom-pdf/lib/worker.js
- /home/devops/jsreport/node_modules/@jsreport/jsreport-core/lib/worker/extensionsManager.js
- /home/devops/jsreport/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js
- /home/devops/jsreport/node_modules/@jsreport/jsreport-core/lib/worker/workerHandler.js
- /home/devops/jsreport/node_modules/@jsreport/advanced-workers/lib/workerHandler.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (/home/devops/jsreport/node_modules/phantom-html-to-pdf/lib/dedicatedProcessStrategy.js:9:31)
    at /home/devops/jsreport/node_modules/phantom-html-to-pdf/lib/conversion.js:71:60
    at /home/devops/jsreport/node_modules/phantom-html-to-pdf/lib/conversion.js:30:17
    at writeHtmlFile (/home/devops/jsreport/node_modules/phantom-html-to-pdf/lib/conversion.js:10:16)
    at /home/devops/jsreport/node_modules/phantom-html-to-pdf/lib/conversion.js:26:13
    at writeHtmlFile (/home/devops/jsreport/node_modules/phantom-html-to-pdf/lib/conversion.js:10:16) rootId=3kwbi5m9bmcl61e, id=3kwbi5m9bmcl61e
==========================================
