### ISSUE TITLE
Cannot read properties of undefined (reading 'compressed') pdf utils

### ISSUE THREAD

**Issue by Ackhuman** [jsreport/jsreport#861]
I have been getting an error that is difficult to reproduce without the exact configuration and template I'm trying to use. I have a .NET console app solution with a minimal repro that I will attach to this issue. The error only happens when I'm using a 3.2.1 server with the MergeWholeDocument option selected and some condition I can't figure out with the specific template. If I turn off that option, or downgrade to 3.2.0, or use a significantly different template, the error does not happen.

The error message is: 

**Error when processing render request 17 Error while executing pdf-utils operations. Cannot read properties of undefined (reading 'compressed') Error: Error while executing pdf-utils operations. Cannot read properties of undefined (reading 'compressed')**

    at module.exports (C:\dev\jsreport\node_modules\@jsreport\jsreport-core\lib\shared\createError.js:10:13)
    at WorkerReporter.createError (C:\dev\jsreport\node_modules\@jsreport\jsreport-core\lib\shared\reporter.js:47:12)
    at AsyncFunction.<anonymous> (C:\dev\jsreport\node_modules\@jsreport\jsreport-pdf-utils\lib\worker.js:191:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ListenerCollection.fire (C:\dev\jsreport\node_modules\@jsreport\jsreport-core\lib\shared\listenerCollection.js:157:21)
    at async afterRender (C:\dev\jsreport\node_modules\@jsreport\jsreport-core\lib\worker\render\render.js:104:5)
    at async WorkerReporter._render (C:\dev\jsreport\node_modules\@jsreport\jsreport-core\lib\worker\render\render.js:152:7)
    at async C:\dev\jsreport\node_modules\@jsreport\jsreport-core\lib\worker\reporter.js:177:19
    at async Domain.<anonymous> (C:\dev\jsreport\node_modules\@jsreport\advanced-workers\lib\workerHandler.js:141:19)
**caused by: TypeError: Cannot read properties of undefined (reading 'compressed')**

    at parseObject (C:\dev\jsreport\node_modules\@jsreport\pdfjs\lib\object\reference.js:81:15)
    at PDFReference.get [as object] (C:\dev\jsreport\node_modules\@jsreport\pdfjs\lib\object\reference.js:15:17)
    at Function.addObjectsRecursive (C:\dev\jsreport\node_modules\@jsreport\pdfjs\lib\parser\parser.js:61:35)
    at C:\dev\jsreport\node_modules\@jsreport\pdfjs\lib\parser\parser.js:82:18
    at Array.forEach (<anonymous>)
    at Function.addObjectsRecursive (C:\dev\jsreport\node_modules\@jsreport\pdfjs\lib\parser\parser.js:81:15)
    at Function.addObjectsRecursive (C:\dev\jsreport\node_modules\@jsreport\pdfjs\lib\parser\parser.js:77:18)
    at Function.addObjectsRecursive (C:\dev\jsreport\node_modules\@jsreport\pdfjs\lib\parser\parser.js:68:16)
    at parsePages (C:\dev\jsreport\node_modules\@jsreport\pdfjs\lib\external.js:38:18)
    at new ExternalDocument (C:\dev\jsreport\node_modules\@jsreport\pdfjs\lib\external.js:47:5) rootId=14958qtoe1q9ox4, id=14958qtoe1q9ox4

I tried just a simple text template with page numbers and that worked fine. Then I thought it might be a function of the size of the resulting document, since the error mentions compression, so I created a template with 100 pages of images that was >200kB, but that also did not reproduce the error. It was only by copy-pasting the HTML from the production app that was experiencing the issue that I was able to do it. I've tried removing various parts of that template: images, styles, handlebars bindings, scripts, external references; none of that prevents the error. I'm not sure what exact combination of factors is causing the problem.

Here is the project with the templates included: [JsReportServerTest.zip](https://github.com/jsreport/jsreport-pdf-utils/files/7908308/JsReportServerTest.zip)

**Comment by pofider** [comment]
Thank you. It seems to work 3.3.0 linux but doesn't work on 3.3.0 windows (same error). At least for me.
I will check it and come back to you.

**Comment by pofider** [comment]
I've pushed the fix, we should release it during the week. I apologize for the inconvenience.

**Comment by pofider** [comment]
We've just release the 3.4.0 update.
