### ISSUE TITLE
OData Get Error (Store - Postgres) Current Version 3.3

### ISSUE THREAD

**Issue by gregorymey-dev** [jsreport/jsreport#866]
Hi Jan,

You mentioned that there would be a hotfix for this issue. Do you perhaps have an ETA on this, as we are upgrading our JS Reports from the 1.8.2 version to the latest?

 error: Error when processing OData GET: /odata/assets?$select=isSharedHelper,scope,name,shortid,tags,folder&$orderby=name TypeError: Cannot read properties of undefined (reading 'forEach')
    at module.exports (/home/jsreport/projects/jsreport/node_modules/@jsreport/odata-to-sql/lib/query.js:54:28)
    at Object.query (/home/jsreport/projects/jsreport/node_modules/@jsreport/odata-to-sql/lib/transformer.js:46:14)
    at Cursor.toArray (/home/jsreport/projects/jsreport/node_modules/@jsreport/sql-store/lib/sqlProvider.js:22:29)
    at replay (/home/jsreport/projects/jsreport/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:51:21)
    at /home/jsreport/projects/jsreport/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:58:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by pofider** [comment]
Likely today or tomorrow.

**Comment by pofider** [comment]
The jsreport v3.2.0 doesn't have this regression though.

**Comment by gregorymey-dev** [comment]
Much appreciated Jan
