### ISSUE TITLE
Can not find template. 

### ISSUE THREAD

**Issue by bklosterman-seon** [jsreport/jsreport#868]
Everything was working fine and then this error:
"Unable to find specified template or user does not have permissions to read it"

I have been trying to sort this for hours.  

I have a handlebars template I want to import.  Can I just import it as a module? 

```
import { ApolloServer } from 'apollo-server-express';
import express, { Application } from 'express';
import http, { Server } from 'http';
import JsReport from 'jsreport';
import apolloServerConfig from './lib/config/apolloServerConfig';
// require('source-map-support').install()

const router = express.Router();

const { SEON_RESTAPI_BASEURL, HOST_PORT } = process.env;

const startServer = async () => {
  const app: Application = express();
  const httpServer: Server = http.createServer(app);

  app.use(express.json());
  app.use('/reporting', router);

  const jsreport = JsReport(<any>{
    extensions: {
      express: { app, server: httpServer },
    },
    appdPath: '/reporting',
  });

  jsreport.init();

  const apolloServer = new ApolloServer(apolloServerConfig);
  await apolloServer.start();
  apolloServer.applyMiddleware({ app, path: '/' });

  router.get('/customer-alarm-activity', async (req, res, next) => {
    try {
      const data = {
        headers: {
          client: req.headers.client,
          expiry: req.headers.expiry,
          uid: req.headers.uid,
          'access-token': req.headers['access-token'],
        },
        params: {
          from: req.body.from,
          to: req.body.to,
          client_id: req.body.client_id,
          base_url: SEON_RESTAPI_BASEURL,
        },
      };

      const renderResponse = await jsreport.render({
        template: {
          name: '/alarms/Activity/activity-main',
          engine: 'handlebars',
          recipe: 'chrome-pdf',
          chrome: {
            marginTop: '1.5cm',
            marginRight: '1.5cm',
            marginBottom: '1.5cm',
            marginLeft: '1.5cm',
            waitForJS: true,
            printBackground: true,
            headerTemplate: '',
            footerTemplate: '',
          },
        },
        data,
        options: {
          reports: { save: false },
        },
      });
      renderResponse.stream.pipe(res);
    } catch (e) {
      next(e);
    }
  });

  app.listen(HOST_PORT, () => {
    console.log(
      `SEON SSP SERVICE IS RUNNING http://localhost:${HOST_PORT}${apolloServer.graphqlPath}`
    );
  });
};

startServer();

```

```
{
  "httpPort": 4000,
  "store": {
    "provider": "fs"
  },
  "blobStorage": {
    "provider": "fs"
  },
  "logger": {
    "console": {
      "transport": "console",
      "level": "debug"
    },
    "file": {
      "transport": "console",
      "level": "debug"
    }
  },
  "allowLocalFilesAccess": true,
  "sandbox": { "allowedModules": ["https"] },
  "reportTimeout": 60000,
  "templatingEngines": {
    "templateCache": { "enabled": false }
  },
  "extensions": {
    "fs-store": {
      "dataDirectory": "src/reports",
      "externalModificationsSync": true
    },
    "sample-template": {
      "createSamples": false
    }
  }
}
```

**Comment by bklosterman-seon** [comment]
Can I just import a handlebars template into the jsreport template without all the config files?

**Comment by pofider** [comment]
Please share the console output from jsreport.

- you can't `import` handlebars template, but you can read its string content and pass it in the `template.content`
- `jsreport.init();` returns promise you should await to be sure jsreport is fully started.

**Comment by bklosterman-seon** [comment]
```
 warn: Error when processing render request 1 Unable to find specified template or user does not have permissions to read it: /alarms/Activity/activity-main Error: Unable to find specified template or user does not have permissions to read it: /alarms/Activity/activity-main
    at module.exports (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/shared/createError.js:10:13)
    at WorkerReporter.createError (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/shared/reporter.js:47:12)
    at AsyncFunction.<anonymous> (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/worker/templates.js:31:22)
    at ListenerCollection.fire (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/shared/listenerCollection.js:157:32)
    at async beforeRender (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:26:5)
    at async WorkerReporter._render (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:150:7)
    at async /Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js:177:19
    at async Domain.<anonymous> (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/advanced-workers/lib/workerHandler.js:141:19) rootId=lws3k2ww59pkdfd, id=lws3k2ww59pkdfd
2022-02-08T16:58:07.306Z - warn: Error when processing render request 1 Unable to find specified template or user does not have permissions to read it: /alarms/Activity/activity-main Error: Unable to find specified template or user does not have permissions to read it: /alarms/Activity/activity-main
    at module.exports (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/shared/createError.js:10:13)
    at WorkerReporter.createError (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/shared/reporter.js:47:12)
    at AsyncFunction.<anonymous> (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/worker/templates.js:31:22)
    at ListenerCollection.fire (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/shared/listenerCollection.js:157:32)
    at async beforeRender (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:26:5)
    at async WorkerReporter._render (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:150:7)
    at async /Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js:177:19
    at async Domain.<anonymous> (/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/node_modules/@jsreport/advanced-workers/lib/workerHandler.js:141:19) rootId=lws3k2ww59pkdfd, id=lws3k2ww59pkdfd
2022-02-08T16:58:07.312Z - warn: Rendering request 1 finished with error in 2 ms rootId=lws3k2ww59pkdfd, id=lws3k2ww59pkdfd
2022-02-08T16:58:07.312Z - warn: Rendering request 1 finished with error in 2 ms rootId=lws3k2ww59pkdfd, id=lws3k2ww59pkdfd

```

**Comment by pofider** [comment]
That is just the error... I would need to see the logs from the start as well. Thank you

**Comment by bklosterman-seon** [comment]
Sure thing.

```
2022-02-08T17:01:24.127Z - info: Initializing jsreport (version: 3.4.0, configuration file: jsreport.config.json, nodejs: 16.13.2)
2022-02-08T17:01:24.126Z - info: Initializing jsreport (version: 3.4.0, configuration file: jsreport.config.json, nodejs: 16.13.2)
2022-02-08T17:01:24.129Z - info: Searching for available extensions in /Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/
2022-02-08T17:01:24.129Z - info: Searching for available extensions in /Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/
2022-02-08T17:01:24.149Z - info: Extensions location cache contains up to date information, skipping crawling in /Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/
2022-02-08T17:01:24.149Z - info: Extensions location cache contains up to date information, skipping crawling in /Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/
2022-02-08T17:01:24.235Z - info: Found 35 extension(s)
2022-02-08T17:01:24.234Z - info: Found 35 extension(s)
2022-02-08T17:01:24.255Z - debug: Writing extension locations cache to /var/folders/w4/zq7qw2d93790wr5jj9z_mk0c0000gn/T/jsreport/core/locations.json
2022-02-08T17:01:24.255Z - debug: Writing extension locations cache to /var/folders/w4/zq7qw2d93790wr5jj9z_mk0c0000gn/T/jsreport/core/locations.json
2022-02-08T17:01:24.256Z - debug: Discovered 35 extensions
2022-02-08T17:01:24.256Z - debug: Discovered 35 extensions
2022-02-08T17:01:24.293Z - info: Using extension authentication@3.2.0
2022-02-08T17:01:24.293Z - info: Using extension authentication@3.2.0
2022-02-08T17:01:24.437Z - debug: Extension authentication@3.2.0 was disabled
2022-02-08T17:01:24.436Z - debug: Extension authentication@3.2.0 was disabled
2022-02-08T17:01:24.437Z - info: Using extension base@3.0.0
2022-02-08T17:01:24.437Z - info: Using extension base@3.0.0
2022-02-08T17:01:24.440Z - info: Using extension child-templates@3.0.1
2022-02-08T17:01:24.440Z - info: Using extension child-templates@3.0.1
2022-02-08T17:01:24.441Z - info: Using extension cli@3.1.0
2022-02-08T17:01:24.441Z - info: Using extension cli@3.1.0
2022-02-08T17:01:24.443Z - info: Using extension components@3.2.0
2022-02-08T17:01:24.443Z - info: Using extension components@3.2.0
2022-02-08T17:01:24.444Z - info: Using extension data@3.0.1
2022-02-08T17:01:24.444Z - info: Using extension data@3.0.1
2022-02-08T17:01:24.445Z - info: Using extension express@3.3.1
2022-02-08T17:01:24.445Z - info: Using extension express@3.3.1
2022-02-08T17:01:24.726Z - info: Using extension freeze@3.0.1
2022-02-08T17:01:24.726Z - info: Using extension freeze@3.0.1
2022-02-08T17:01:24.727Z - info: Using extension fs-store@3.1.0
2022-02-08T17:01:24.727Z - info: Using extension fs-store@3.1.0
2022-02-08T17:01:24.823Z - info: Using extension handlebars@3.0.0
2022-02-08T17:01:24.823Z - info: Using extension handlebars@3.0.0
2022-02-08T17:01:24.824Z - info: Using extension import-export@3.1.1
2022-02-08T17:01:24.824Z - info: Using extension import-export@3.1.1
2022-02-08T17:01:24.834Z - info: Using extension jsrender@3.0.0
2022-02-08T17:01:24.834Z - info: Using extension jsrender@3.0.0
2022-02-08T17:01:24.835Z - info: Using extension licensing@3.0.2
2022-02-08T17:01:24.835Z - info: Using extension licensing@3.0.2
2022-02-08T17:01:24.851Z - info: Using extension localization@3.2.0
2022-02-08T17:01:24.851Z - info: Using extension localization@3.2.0
2022-02-08T17:01:24.852Z - info: Using extension npm@3.1.1
2022-02-08T17:01:24.852Z - info: Using extension npm@3.1.1
2022-02-08T17:01:24.854Z - info: Using extension pdf-utils@3.3.0
2022-02-08T17:01:24.854Z - info: Using extension pdf-utils@3.3.0
2022-02-08T17:01:24.855Z - info: Using extension reports@3.0.3
2022-02-08T17:01:24.855Z - info: Using extension reports@3.0.3
2022-02-08T17:01:24.859Z - info: Using extension tags@3.1.0
2022-02-08T17:01:24.859Z - info: Using extension tags@3.1.0
2022-02-08T17:01:24.860Z - info: Using extension text@3.0.0
2022-02-08T17:01:24.860Z - info: Using extension text@3.0.0
2022-02-08T17:01:24.860Z - info: Using extension version-control@3.1.0
2022-02-08T17:01:24.860Z - info: Using extension version-control@3.1.0
2022-02-08T17:01:24.873Z - info: Using extension assets@3.3.0
2022-02-08T17:01:24.873Z - info: Using extension assets@3.3.0
2022-02-08T17:01:24.885Z - info: Using extension authorization@3.2.0
2022-02-08T17:01:24.885Z - info: Using extension authorization@3.2.0
2022-02-08T17:01:24.890Z - debug: Extension authorization@3.2.0 was disabled
2022-02-08T17:01:24.890Z - debug: Extension authorization@3.2.0 was disabled
2022-02-08T17:01:24.890Z - info: Using extension browser-client@3.1.0
2022-02-08T17:01:24.890Z - info: Using extension browser-client@3.1.0
2022-02-08T17:01:24.892Z - info: Using extension chrome-pdf@3.1.0
2022-02-08T17:01:24.892Z - info: Using extension chrome-pdf@3.1.0
2022-02-08T17:01:24.895Z - debug: Chrome strategy is chrome-pool, numberOfWorkers: 1
2022-02-08T17:01:24.895Z - debug: Chrome strategy is chrome-pool, numberOfWorkers: 1
2022-02-08T17:01:24.895Z - info: Using extension docx@3.2.0
2022-02-08T17:01:24.895Z - info: Using extension docx@3.2.0
2022-02-08T17:01:24.897Z - info: Using extension html-to-xlsx@3.2.0
2022-02-08T17:01:24.897Z - info: Using extension html-to-xlsx@3.2.0
2022-02-08T17:01:24.966Z - info: html-to-xlsx detected chrome as available html engine
2022-02-08T17:01:24.965Z - info: html-to-xlsx detected chrome as available html engine
2022-02-08T17:01:24.966Z - info: Using extension pptx@3.1.0
2022-02-08T17:01:24.966Z - info: Using extension pptx@3.1.0
2022-02-08T17:01:24.967Z - info: Using extension scheduling@3.0.1
2022-02-08T17:01:24.967Z - info: Using extension scheduling@3.0.1
2022-02-08T17:01:25.004Z - info: Using extension scripts@3.2.0
2022-02-08T17:01:25.004Z - info: Using extension scripts@3.2.0
2022-02-08T17:01:25.004Z - info: Using extension static-pdf@3.0.0
2022-02-08T17:01:25.004Z - info: Using extension static-pdf@3.0.0
2022-02-08T17:01:25.005Z - info: Using extension studio@3.4.0
2022-02-08T17:01:25.005Z - info: Using extension studio@3.4.0
2022-02-08T17:01:25.108Z - info: Using extension xlsx@3.1.0
2022-02-08T17:01:25.108Z - info: Using extension xlsx@3.1.0
2022-02-08T17:01:25.128Z - info: Using extension public-templates@3.0.0
2022-02-08T17:01:25.128Z - info: Using extension public-templates@3.0.0
2022-02-08T17:01:25.129Z - debug: Extension public-templates@3.0.0 was disabled
2022-02-08T17:01:25.129Z - debug: Extension public-templates@3.0.0 was disabled
2022-02-08T17:01:25.130Z - info: Using extension sample-template@3.1.0
2022-02-08T17:01:25.130Z - info: Using extension sample-template@3.1.0
2022-02-08T17:01:25.132Z - info: Using extension studio-theme-dark@3.0.1
2022-02-08T17:01:25.132Z - info: Using extension studio-theme-dark@3.0.1
2022-02-08T17:01:25.133Z - info: Using general timeout for rendering (reportTimeout: 60000)
2022-02-08T17:01:25.133Z - info: Using general timeout for rendering (reportTimeout: 60000)
2022-02-08T17:01:25.133Z - info: Using fs provider for template store.
2022-02-08T17:01:25.133Z - info: Using fs provider for template store.
2022-02-08T17:01:25.138Z - info: fs store is persisting using fs for /Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/src/reports
2022-02-08T17:01:25.138Z - info: fs store is persisting using fs for /Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/src/reports
2022-02-08T17:01:25.145Z - info: fs store is loading data
2022-02-08T17:01:25.145Z - info: fs store is loading data
2022-02-08T17:01:25.153Z - info: fs store is initialized successfully
2022-02-08T17:01:25.153Z - info: fs store is initialized successfully
2022-02-08T17:01:25.158Z - debug: studio default theme is: light
2022-02-08T17:01:25.158Z - debug: studio default theme is: light
2022-02-08T17:01:25.164Z - info: Configuring routes for existing express app.
2022-02-08T17:01:25.164Z - info: Configuring routes for existing express app.
2022-02-08T17:01:25.179Z - info: Using existing server instance.
2022-02-08T17:01:25.179Z - info: Using existing server instance.
2022-02-08T17:01:25.180Z - info: Verifying license key free
2022-02-08T17:01:25.180Z - info: Verifying license key free
2022-02-08T17:01:25.181Z - info: Using free license
2022-02-08T17:01:25.181Z - info: Using free license
2022-02-08T17:01:25.184Z - debug: Creating samples is disabled
2022-02-08T17:01:25.184Z - debug: Creating samples is disabled
2022-02-08T17:01:25.184Z - info: Initializing worker threads
2022-02-08T17:01:25.184Z - info: Initializing worker threads
2022-02-08T17:01:25.184Z - debug: Extensions in workers: base, child-templates, components, data, express, handlebars, jsrender, localization, npm, pdf-utils, reports, text, version-control, assets, browser-client, chrome-pdf, docx, html-to-xlsx, pptx, scripts, static-pdf, studio, xlsx
2022-02-08T17:01:25.184Z - debug: Extensions in workers: base, child-templates, components, data, express, handlebars, jsrender, localization, npm, pdf-utils, reports, text, version-control, assets, browser-client, chrome-pdf, docx, html-to-xlsx, pptx, scripts, static-pdf, studio, xlsx
2022-02-08T17:01:25.364Z - info: 2 worker threads initialized in 180ms
2022-02-08T17:01:25.364Z - info: 2 worker threads initialized in 180ms
2022-02-08T17:01:25.365Z - info: Starting temp files cleanup with 180000ms threshold
2022-02-08T17:01:25.365Z - info: Starting temp files cleanup with 180000ms threshold
2022-02-08T17:01:25.365Z - info: reporter initialized
2022-02-08T17:01:25.365Z - info: reporter initialized
```

**Comment by pofider** [comment]
Thank you. 
The templates are being searched here, I believe it is correct right? `/Users/bklosterman/Documents/SEON/seon-ssp-customers-graph/src/reports`

This line in log is a bit strange
```
2022-02-08T17:01:24.255Z - debug: Writing extension locations cache to 
/var/folders/w4/zq7qw2d93790wr5jj9z_mk0c0000gn/T/jsreport/core/locations.json
```
Don't you use some docker with mapped tmpfs volume? If this is the case, are you sure everything is mapped to your container properly?

Please try to reach in browser (http://yourlocalhost/reporting:xxxx), do the templates pop up in the studio?

**Comment by bklosterman-seon** [comment]
Yes I was thinking there is something going on with the cache. 

I am using tsconfig with nodemon.

```
{
  "watch": ["src"],
  "ext": "ts,js,json",
  "ignore": ["node_modules", "coverage", "dist"],
  "execMap": {
    "ts": "ts-node -r tsconfig-paths/register -r dotenv/config"
  },
  "restartable": "rs"
}
```

**Comment by bklosterman-seon** [comment]
```
{
  "compilerOptions": {
    /* Basic Options */
    "target": "es6" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */,
    "module": "commonjs" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */,
    "lib": [
      "dom",
      "esnext"
    ] /* Specify library files to be included in the compilation. */,
    "allowJs": true /* Allow javascript files to be compiled. */,
    "outDir": "dist" /* Redirect output structure to the directory. */,
    "rootDir": "src" /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */,
    "removeComments": true /* Do not emit comments to output. */,

    /* Strict Type-Checking Options */
    "strict": true /* Enable all strict type-checking options. */,
    "noImplicitAny": false /* Raise error on expressions and declarations with an implied 'any' type. */,

    /* Module Resolution Options */
    "moduleResolution": "node" /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */,
    "baseUrl": "." /* Base directory to resolve non-absolute module names. */,
    "paths": {
      /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
      "@src/*": ["src/*"]
    },
    "sourceMap": true,
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,

    /* Experimental Options */
    "experimentalDecorators": true /* Enables experimental support for ES7 decorators. */,
    "emitDecoratorMetadata": true /* Enables experimental support for emitting type metadata for decorators. */,

    /* Advanced Options */
    "skipLibCheck": true /* Skip type checking of declaration files. */,
    "forceConsistentCasingInFileNames": true /* Disallow inconsistently-cased references to the same file. */
  },
  "exclude": ["node_modules", "dist", "coverage"],
  "include": ["src", "__tests__"]
}
```

**Comment by bklosterman-seon** [comment]
same error when I try and reach in the browser

**Comment by bklosterman-seon** [comment]
I was able to start a project from scratch and get it working with the generated samples.  I deployed to a server and now have the same error again.  
Do you have an example where I can use template.content and that uses beforeRender? 
Or is it better to use fs store?  Is there a reason it doesn't work once it is deployed?

**Comment by pofider** [comment]
Maybe some problem with your deployment, no clue....

> Do you have an example where I can use template.content and that uses beforeRender?

https://jsreport.net/learn/scripts#api

> Or is it better to use fs store? Is there a reason it doesn't work once it is deployed?

That is up to you and your environment. Persisted templates in the template store are, however, used in the most of the cases.

**Comment by bklosterman-seon** [comment]
I am building inside a Docker container.  Do I include the auto generated config files when I push to build pipeline?

**Comment by bklosterman-seon** [comment]
I have noticed I am only able to edit the auto generated samples.  When I create a new template in the same directory I receive  the same error.

**Comment by pofider** [comment]
I recommend trying things out first locally without docker. If things work ok, then start troubleshooting docker.

I see from your logs that you have mapped the folder with templates from your dev machine to the docker container... When you deploy these data are not there I guess. So you may need to copy them to the container during the build. However, all of this depends on your specific build/deploy flow and not so much on jsreport.

**Comment by pofider** [comment]
Closing because of long inactivity here. 
However, don't hesitate to post further comments.
