### ISSUE TITLE
Rendering request counter reset to 1 when rendering failed

### ISSUE THREAD

**Issue by jorisdebock** [jsreport/jsreport#884]
On our test environment with the new v3 version of jsreport I noticed when the following error happens the request counter did reset to 1

```
2022-02-20T21:14:53.204Z - info: Rendering template { name: xx.pdf, recipe: chrome-pdf, engine: jsrender, preview: false } rootId=8j7j58jiyue2xse, id=8j7j58jiyue2xse
2022-02-20T21:15:02.402Z - info: pdf-utils is starting pdf processing rootId=8j7j58jiyue2xse, id=8j7j58jiyue2xse
2022-02-20T21:15:02.503Z - info: Starting rendering request 68 (user: xx) rootId=8j7j58jiyue2xse, id=9td701qrbsngr83
2022-02-20T21:15:02.503Z - info: Rendering template { name: xx.pdf, recipe: chrome-pdf, engine: jsrender, preview: false } rootId=8j7j58jiyue2xse, id=9td701qrbsngr83
2022-02-20T21:15:03.511Z - warn: Report render failed: Report cancelled Error: Report cancelled
    at Object.close (/usr/local/opt/jsreport/2.0.3-0/node_modules/@jsreport/advanced-workers/lib/threadWorker.js:138:21)
    at Object.release (/usr/local/opt/jsreport/2.0.3-0/node_modules/@jsreport/advanced-workers/lib/pool.js:38:22)
    at EventEmitter.<anonymous> (/usr/local/opt/jsreport/2.0.3-0/node_modules/@jsreport/jsreport-core/lib/main/reporter.js:338:16)
    at Object.onceWrapper (node:events:509:28)
    at EventEmitter.emit (node:events:390:28)
    at Socket.<anonymous> (/usr/local/opt/jsreport/2.0.3-0/node_modules/@jsreport/jsreport-express/lib/routes.js:68:20)
    at Object.onceWrapper (node:events:510:26)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12) rootId=8j7j58jiyue2xse, id=8j7j58jiyue2xse
2022-02-20T21:15:03.528Z - warn: Error during processing request at xx/api/report, details: Report cancelled, stack: Error: Report cancelled
    at Object.close (/usr/local/opt/jsreport/2.0.3-0/node_modules/@jsreport/advanced-workers/lib/threadWorker.js:138:21)
    at Object.release (/usr/local/opt/jsreport/2.0.3-0/node_modules/@jsreport/advanced-workers/lib/pool.js:38:22)
    at EventEmitter.<anonymous> (/usr/local/opt/jsreport/2.0.3-0/node_modules/@jsreport/jsreport-core/lib/main/reporter.js:338:16)
    at Object.onceWrapper (node:events:509:28)
    at EventEmitter.emit (node:events:390:28)
    at Socket.<anonymous> (/usr/local/opt/jsreport/2.0.3-0/node_modules/@jsreport/jsreport-express/lib/routes.js:68:20)
    at Object.onceWrapper (node:events:510:26)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12)
```

after "report render failed" the request counter did reset to 1

```
2022-02-20T21:16:09.741Z - info: Starting rendering request 1 (user: xx) rootId=qt95bj8aegbmg2l, id=qt95bj8aegbmg2l
```

**Comment by pofider** [comment]
Thank you.

This was actually already fixed to the master the last week.
I will be part of the next release.
