### ISSUE TITLE
Maximum Call Stack

### ISSUE THREAD

**Issue by 1Map** [jsreport/jsreport#889]
https://github.com/jsreport/jsreport/blob/e89683c1efaeeec7d5dc6757cdc4cd0acac026c6/packages/jsreport-core/lib/worker/render/diff.js#L20

The line to the link above gives error on large result in Full Profiling:

```
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at formatPatch (/home/schalk/onemapjsreport/node_modules/@jsreport/jsreport-core/lib/worker/render/diff.js:20:14)
    at createPatch (/home/schalk/onemapjsreport/node_modules/@jsreport/jsreport-core/lib/worker/render/diff.js:130:10)
    at Profiler.emit (/home/schalk/onemapjsreport/node_modules/@jsreport/jsreport-core/lib/worker/render/profiler.js:94:23)
    at Scripts.handleBeforeRender (/home/schalk/onemapjsreport/node_modules/@jsreport/jsreport-scripts/lib/worker.js:73:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ListenerCollection.fire (/home/schalk/onemapjsreport/node_modules/@jsreport/jsreport-core/lib/shared/listenerCollection.js:157:21)
    at async beforeRender (/home/schalk/onemapjsreport/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:26:5)
    at async WorkerReporter._render (/home/schalk/onemapjsreport/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:150:7)
    at async /home/schalk/onemapjsreport/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js:177:19
    at async Domain.<anonymous> (/home/schalk/onemapjsreport/node_modules/@jsreport/advanced-workers/lib/workerHandler.js:141:19)
```

**Comment by pofider** [comment]
Could you please try to replicate the same in the playground?
https://playground.jsreport.net/

**Comment by 1Map** [comment]
No, as I said,  It is failing on a simple sample like the default Orders sample.  Basically anything where the template contains a css or js to an external file.  As if puppeteer are trying to fetch the scripts and css and then fail.

**Comment by 1Map** [comment]
@pofider 

I created a sample at playground:

https://playground.jsreport.net/w/anon/uDtB1oMH

**Comment by pofider** [comment]
Thank you. We will take a look.
However, at the first glance, the data and report look too big for full profiling.

**Comment by 1Map** [comment]
What is too big?  Even if not profiling it does not work.

**Comment by pofider** [comment]
15 000 tables and at least 3000 pages. Is that expected?

This can take about 10minutes to render in chrome and convert to pdf.
You may get better results without using HTML tables and complex styles though.

**Comment by pofider** [comment]
We've limited the profiling diffs to a fixed size to avoid this error.
This is part of the jsreport 3.5.0.
