### ISSUE TITLE
Error during rendering report: connect ECONNREFUSED Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by mikejohanson** [jsreport/jsreport#89]
Hi Folks, 

I've got jsReport up and running on a Windows Azure Cloud Service, however when I try to render the sample template I'm getting a response in the preview pane of : The page cannot be displayed because an internal server error has occurred.

Upon looking at the logs this is what I have discovered, but I'm not exactly sure what the cause of it is. I came across https://github.com/jsreport/jsreport/issues/76 but I didn't see a resolution come out of it.  

```
Wed, 01 Jul 2015 05:28:33 GMT express deprecated req.host: Use req.hostname instead at node_modules\jsreport\node_modules\toner-phantom\node_modules\node.extend\lib\extend.js:42:23
2015-07-01T05:28:41.706Z - [31merror[39m: Error when processing render request Error during rendering report: connect ECONNREFUSED Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
From previous event:
    at Object.phantom-pdf (E:\sitesroot\1\node_modules\jsreport\lib\reporter.js:136:46)
    at E:\sitesroot\1\node_modules\jsreport\node_modules\toner\lib\toner.js:126:47
    at E:\sitesroot\1\node_modules\jsreport\node_modules\toner\lib\toner.js:85:17
    at E:\sitesroot\1\node_modules\jsreport\node_modules\toner\lib\listeners.js:38:17
    at E:\sitesroot\1\node_modules\jsreport\lib\reporter.js:113:43
2015-07-01T05:28:41.706Z - [31merror[39m: Error during processing request: http://mycloudapp.cloudapp.net/api/report?studio=normal details: Error during rendering report: connect ECONNREFUSED Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
From previous event:
    at Object.phantom-pdf (E:\sitesroot\1\node_modules\jsreport\lib\reporter.js:136:46)
    at E:\sitesroot\1\node_modules\jsreport\node_modules\toner\lib\toner.js:126:47
    at E:\sitesroot\1\node_modules\jsreport\node_modules\toner\lib\toner.js:85:17
    at E:\sitesroot\1\node_modules\jsreport\node_modules\toner\lib\listeners.js:38:17
    at E:\sitesroot\1\node_modules\jsreport\lib\reporter.js:113:43
```

my config file: 

```
{
    "certificate": {
        "key": "certificates/jsreport.net.key",    
        "cert": "certificates/jsreport.net.cert"
    },
    "connectionString": { "name": "neDB" }
    "blobStorage": "fileSystem",
    "phantom": {
        "numberOfWorkers" : 2,
        "timeout": 180000
    },
    "tasks": {
        "numberOfWorkers" : 2,
        "timeout": 10000
    }
}
```

Any guidance would greatly appreciated!

**Comment by pofider** [comment]
Could you please try to replace following in the configuration? 

```js
{
  ....
   "phantom": {
        "timeout": 180000,
        "strategy": "dedicated-process"
    },
    "tasks": {
        "timeout": 10000,
        "strategy": "dedicated-process"
    }
```

This is a web role with iisnode right? I will need to try it on my own, currently I host my instances in worker roles, but web roles should work as well.

**Comment by mikejohanson** [comment]
Yes, it is a worker role. Yup! That did the trick! Thank you!

**Comment by Ackhuman** [comment]
A coworker had this issue as well and this fix worked.  Would it be possible to put this in the documentation somewhere?

**Comment by pofider** [comment]
Yes, sure this needs to be documented, I will do it.

I am also planning to make this settings the default one. It makes jsreport a little slower but it doesn't have issues with proxies and other networking settings. This should be shipped with the next version...
