### ISSUE TITLE
Error in Preview

### ISSUE THREAD

**Issue by 1Map** [jsreport/jsreport#892]
What does this error means?

```
preview error
Cannot create a string longer than 0x1fffffe8 characters
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:642:37)
    at Buffer.toString (node:buffer:811:14)
    at Profiler.emit (/home/schalk/onemapjsreport/node_modules/@jsreport/jsreport-core/lib/worker/render/profiler.js:77:34)
    at invokeRender (/home/schalk/onemapjsreport/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:97:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WorkerReporter._render (/home/schalk/onemapjsreport/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:151:7)
    at async /home/schalk/onemapjsreport/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js:177:19
    at async Domain.<anonymous> (/home/schalk/onemapjsreport/node_modules/@jsreport/advanced-workers/lib/workerHandler.js:141:19)
```

Seems it is happening on Line 77 in:
`jsreport-core/lib/worker/render/profiler.js:77:34`

**Comment by pofider** [comment]
Profiler diff is too big to fit the memory.
Don't use full profiling for such giant outputs.
https://jsreport.net/learn/studio#profiles

**Comment by pofider** [comment]
We have now max profiling limits in config so this error shouldn't be popping up.
