### ISSUE TITLE
Dangling `TOCTitle` tags with jsreport-docx 3.3.0+

### ISSUE THREAD

**Issue by pdecat** [jsreport/jsreport#934]
Hi @bjrmatos, thanks for the [fix about supporting other languages](https://github.com/jsreport/jsreport/issues/871).

However, the issue reported in [my comment](https://github.com/jsreport/jsreport/issues/871#issuecomment-1034937992) about dangling `TOCTitle` tags is still present with jsreport-docx 3.3.0+, even if the template document does not have a ToC section at all:

```
# xmllint --format --recover tmp/word/document.xml  | tail -n 45
tmp/word/document.xml:2570: parser error : Opening and ending tag mismatch: TOCTitle line 2570 and w:body
:titlePg/><w:docGrid w:linePitch="360" w:charSpace="12288"/></w:sectPr></w:body>
                                                                               ^
tmp/word/document.xml:2570: parser error : Opening and ending tag mismatch: TOCTitle line 2570 and w:document
docGrid w:linePitch="360" w:charSpace="12288"/></w:sectPr></w:body></w:document>
                                                                               ^
tmp/word/document.xml:2570: parser error : Premature end of data in tag TOCTitle line 2570
docGrid w:linePitch="360" w:charSpace="12288"/></w:sectPr></w:body></w:document>
                                                                               ^
              </w:rPr>
            </w:pPr>
          </w:p>
          <TOCTitle>
            <TOCTitle>
              <w:p w:rsidR="00004CC9" w:rsidP="2FD47C27" w:rsidRDefault="00004CC9" w14:paraId="1136B6CE" w14:textId="77777777">
                <w:pPr>
                  <w:rPr>
                    <w:noProof/>
                    <w:lang w:val="en-US"/>
                  </w:rPr>
                </w:pPr>
              </w:p>
              <TOCTitle>
                <w:p w:rsidRPr="00A55DF1" w:rsidR="00004CC9" w:rsidP="2FD47C27" w:rsidRDefault="00004CC9" w14:paraId="23114891" w14:textId="77777777">
                  <w:pPr>
                    <w:rPr>
                      <w:noProof/>
                      <w:lang w:val="en-US"/>
                    </w:rPr>
                  </w:pPr>
                </w:p>
                <TOCTitle>
                  <TOCTitle>
                    <TOCTitle>
                      <w:sectPr w:rsidR="161C1780" w:rsidSect="008F46CE">
                        <w:footerReference w:type="first" r:id="rId60"/>
                        <w:pgSz w:w="16838" w:h="11906" w:orient="landscape"/>
                        <w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720" w:header="850" w:footer="1417" w:gutter="0"/>
                        <w:cols w:space="720"/>
                        <w:formProt w:val="0"/>
                        <w:titlePg/>
                        <w:docGrid w:linePitch="360" w:charSpace="12288"/>
                      </w:sectPr>
                    </TOCTitle>
                  </TOCTitle>
                </TOCTitle>
              </TOCTitle>
            </TOCTitle>
          </TOCTitle>
        </TOCTitle>
      </TOCTitle>
    </TOCTitle>
  </w:body>
</w:document>
```
Note: closing `</TOCTitle>` tags are added by the `--recover` option of `xmllint`.

Raw xml at the end of `document.xml`:
```
# fold -w 120 -s tmp/word/document.xml | tail -n 15
w:val="restart"/><w:tcW
w:type="auto"/></w:tcPr><w:p><w:r><w:t>$34.56</w:t></w:r></w:p></w:tc></w:tr></w:tbl><TOCTitle><TOCTitle><TOCTitle><w:p
w:rsidRPr="00A55DF1" w:rsidR="003C5309" w:rsidP="001A2FDB" w:rsidRDefault="003C5309" w14:paraId="088B23E8"
w14:textId="77777777"><w:pPr><w:rPr><w:noProof/><w:lang w:val="en-US"/></w:rPr></w:pPr></w:p><w:p w:rsidRPr="00A55DF1"
w:rsidR="00D46180" w:rsidP="3F4485B1" w:rsidRDefault="00D46180" w14:paraId="427AF8AD"
w14:textId="77777777"><w:pPr><w:rPr><w:noProof/><w:lang w:val="en-US"/></w:rPr></w:pPr></w:p><TOCTitle><TOCTitle><w:p
w:rsidR="00004CC9" w:rsidP="2FD47C27" w:rsidRDefault="00004CC9" w14:paraId="1136B6CE"
w14:textId="77777777"><w:pPr><w:rPr><w:noProof/><w:lang w:val="en-US"/></w:rPr></w:pPr></w:p><TOCTitle><w:p
w:rsidRPr="00A55DF1" w:rsidR="00004CC9" w:rsidP="2FD47C27" w:rsidRDefault="00004CC9" w14:paraId="23114891"
w14:textId="77777777"><w:pPr><w:rPr><w:noProof/><w:lang
w:val="en-US"/></w:rPr></w:pPr></w:p><TOCTitle><TOCTitle><TOCTitle><w:sectPr w:rsidR="161C1780"
w:rsidSect="008F46CE"><w:footerReference w:type="first" r:id="rId60"/><w:pgSz w:w="16838" w:h="11906"
w:orient="landscape"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720" w:header="850" w:footer="1417"
w:gutter="0"/><w:cols w:space="720"/><w:formProt w:val="0"/><w:titlePg/><w:docGrid w:linePitch="360"
w:charSpace="12288"/></w:sectPr></w:body></w:document>
```
**The closing `</TOCTitle>` tags are all missing, so the `toc` post-processor do not match them.**

**Comment by pdecat** [comment]
Here is a minimal template to reproduce the issue:
[content.docx](https://github.com/jsreport/jsreport/files/8990263/content.docx)

It only contains the following text with some formatting:

```
1.1.1 {{#if false}}Some title
{{/if}}
``` 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:cx="http://schemas.microsoft.com/office/drawing/2014/chartex" xmlns:cx1="http://schemas.microsoft.com/office/drawing/2015/9/8/chartex" xmlns:cx2="http://schemas.microsoft.com/office/drawing/2015/10/21/chartex" xmlns:cx3="http://schemas.microsoft.com/office/drawing/2016/5/9/chartex" xmlns:cx4="http://schemas.microsoft.com/office/drawing/2016/5/10/chartex" xmlns:cx5="http://schemas.microsoft.com/office/drawing/2016/5/11/chartex" xmlns:cx6="http://schemas.microsoft.com/office/drawing/2016/5/12/chartex" xmlns:cx7="http://schemas.microsoft.com/office/drawing/2016/5/13/chartex" xmlns:cx8="http://schemas.microsoft.com/office/drawing/2016/5/14/chartex" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:aink="http://schemas.microsoft.com/office/drawing/2016/ink" xmlns:am3d="http://schemas.microsoft.com/office/drawing/2017/model3d" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:oel="http://schemas.microsoft.com/office/2019/extlst" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:w16cex="http://schemas.microsoft.com/office/word/2018/wordml/cex" xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns:w16="http://schemas.microsoft.com/office/word/2018/wordml" xmlns:w16sdtdh="http://schemas.microsoft.com/office/word/2020/wordml/sdtdatahash" xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 w15 w16se w16cid w16 w16cex w16sdtdh wp14">
  <w:body>
    <w:p w14:paraId="2570E273" w14:textId="143ED4C6" w:rsidR="79F10C16" w:rsidRPr="005A6EFE" w:rsidRDefault="3A031C06" w:rsidP="0213D798">
      <w:pPr>
        <w:pStyle w:val="Heading3"/>
        <w:rPr>
          <w:noProof/>
          <w:lang w:val="en-US"/>
        </w:rPr>
      </w:pPr>
      <w:bookmarkStart w:id="0" w:name="_Toc57805962"/>
      <w:bookmarkStart w:id="1" w:name="_Toc63171199"/>
      <w:r w:rsidRPr="28748B2A">
        <w:rPr>
          <w:rFonts w:eastAsia="Calibri"/>
          <w:lang w:val="en-US"/>
        </w:rPr>
        <w:t>{{#if</w:t>
      </w:r>
      <w:r w:rsidRPr="28748B2A">
        <w:rPr>
          <w:noProof/>
          <w:lang w:val="en-US"/>
        </w:rPr>
        <w:t xml:space="preserve"> false}}</w:t>
      </w:r>
      <w:r w:rsidR="3A8AEE9C" w:rsidRPr="28748B2A">
        <w:rPr>
          <w:noProof/>
          <w:lang w:val="en-US"/>
        </w:rPr>
        <w:t>Some title</w:t>
      </w:r>
      <w:bookmarkEnd w:id="0"/>
      <w:bookmarkEnd w:id="1"/>
    </w:p>
    <w:p w14:paraId="2366E6F5" w14:textId="77777777" w:rsidR="00910B20" w:rsidRDefault="00434CD9">
      <w:pPr>
        <w:rPr>
          <w:rFonts w:ascii="Calibri" w:eastAsia="Calibri" w:hAnsi="Calibri" w:cs="Calibri"/>
          <w:noProof/>
          <w:lang w:val="en-US"/>
        </w:rPr>
      </w:pPr>
      <w:r w:rsidRPr="00A3430A">
        <w:rPr>
          <w:rFonts w:ascii="Calibri" w:eastAsia="Calibri" w:hAnsi="Calibri" w:cs="Calibri"/>
          <w:noProof/>
          <w:lang w:val="en-US"/>
        </w:rPr>
        <w:t>{{/if}}</w:t>
      </w:r>
    </w:p>
    <w:sectPr w:rsidR="00910B20" w:rsidSect="008F46CE">
      <w:pgSz w:w="16838" w:h="11906" w:orient="landscape"/>
      <w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720" w:header="850" w:footer="1417" w:gutter="0"/>
      <w:cols w:space="720"/>
      <w:formProt w:val="0"/>
      <w:titlePg/>
      <w:docGrid w:linePitch="360" w:charSpace="12288"/>
    </w:sectPr>
  </w:body>
</w:document>
```

**Comment by pdecat** [comment]
So, this seems to be caused by the usage of `{{if xxx}}` conditions in titles when the closing `{{/if}}` is not in the title itself. The reason for using conditions like that is described in https://github.com/jsreport/jsreport-docx/issues/29.

**Comment by bjrmatos** [comment]
@pdecat thanks for the bug report, and the details, we have not given any priority to the https://github.com/jsreport/jsreport-docx/issues/29 we will try to give it some time, analyze and try to come up with a solution to the dangling tags. however it may take some time, perhaps some weeks to get to it, right now we are focusing our time in preparing another release so please expect the updates here.

**Comment by pdecat** [comment]
Thanks @bjrmatos! In the meantime, I've submitted #935 that resolves this issue, and addresses https://github.com/jsreport/jsreport-docx/issues/29 at the same time.

**Comment by bjrmatos** [comment]
i have added the changes to the PR you submitted [here](https://github.com/jsreport/jsreport/commit/fd75c9a8860914fb6ccba1fa241ba45dae86131e), also with tests

please let me know if this work ok for your reports, if everything is ok we should be releasing this soon

**Comment by pdecat** [comment]
Hi @bjrmatos, using that [latest fd75c9a8 commit](https://github.com/jsreport/jsreport/commit/fd75c9a8860914fb6ccba1fa241ba45dae86131e) is producing invalid XML with my complex docx template (but not with the one from https://github.com/jsreport/jsreport/issues/934#issuecomment-1167075683):

```
# unzip -p report.docx word/document.xml | xmllint -
-:2571: parser error : Opening and ending tag mismatch: TOCTitle line 2571 and w:body
:titlePg/><w:docGrid w:linePitch="360" w:charSpace="12288"/></w:sectPr></w:body>
                                                                               ^
-:2571: parser error : Opening and ending tag mismatch: TOCTitle line 2571 and w:document
docGrid w:linePitch="360" w:charSpace="12288"/></w:sectPr></w:body></w:document>
                                                                               ^
-:2571: parser error : Premature end of data in tag TOCTitle line 2571
docGrid w:linePitch="360" w:charSpace="12288"/></w:sectPr></w:body></w:document>
```

```
# unzip -p 3cr-report.docx word/document.xml | fold -w 120 -s | tail -n 15
w:val="restart"/><w:tcW
w:type="auto"/></w:tcPr><w:p><w:r><w:t>$34.56</w:t></w:r></w:p></w:tc></w:tr></w:tbl><TOCTitle><TOCTitle><TOCTitle><w:p
w14:paraId="088B23E8" w14:textId="77777777" w:rsidR="003C5309" w:rsidRPr="00A55DF1" w:rsidRDefault="003C5309"
w:rsidP="001A2FDB"><w:pPr><w:rPr><w:noProof/><w:lang w:val="en-US"/></w:rPr></w:pPr></w:p><w:p w14:paraId="427AF8AD"
w14:textId="77777777" w:rsidR="00D46180" w:rsidRPr="00A55DF1" w:rsidRDefault="00D46180"
w:rsidP="3F4485B1"><w:pPr><w:rPr><w:noProof/><w:lang w:val="en-US"/></w:rPr></w:pPr></w:p><TOCTitle><TOCTitle><w:p
w14:paraId="1136B6CE" w14:textId="77777777" w:rsidR="00004CC9" w:rsidRDefault="00004CC9"
w:rsidP="2FD47C27"><w:pPr><w:rPr><w:noProof/><w:lang w:val="en-US"/></w:rPr></w:pPr></w:p><TOCTitle><w:p
w14:paraId="23114891" w14:textId="77777777" w:rsidR="00004CC9" w:rsidRPr="00A55DF1" w:rsidRDefault="00004CC9"
w:rsidP="2FD47C27"><w:pPr><w:rPr><w:noProof/><w:lang
w:val="en-US"/></w:rPr></w:pPr></w:p><TOCTitle><TOCTitle><TOCTitle><w:sectPr w:rsidR="161C1780"
w:rsidSect="008F46CE"><w:footerReference w:type="first" r:id="rId60"/><w:pgSz w:w="16838" w:h="11906"
w:orient="landscape"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720" w:header="850" w:footer="1417"
w:gutter="0"/><w:cols w:space="720"/><w:formProt w:val="0"/><w:titlePg/><w:docGrid w:linePitch="360"
w:charSpace="12288"/></w:sectPr></w:body></w:document>
```

I'll try to provide a minimal reproduction test case.

**Comment by pdecat** [comment]
FWIW, using the [previous commit (3ef9e8b2)](https://github.com/jsreport/jsreport/commit/3ef9e8b256b7b891907b2c72255e7ef6bd777b98) makes the XML valid again.

**Comment by pdecat** [comment]
Here's a minimal reproduction case that works with previous commit https://github.com/jsreport/jsreport/commit/3ef9e8b256b7b891907b2c72255e7ef6bd777b98 but not last commit https://github.com/jsreport/jsreport/commit/fd75c9a8860914fb6ccba1fa241ba45dae86131e

```
1. {{#if true}}Title1
Some text
1.1 {{#if true}}{{#if false}}Title1.1
Some text
{{/if}}
1.1.1 {{#if true}}Title1.1.1
Some text
{{/if}}
{{/if}}
{{/if}}
```

[GH-934-template.docx](https://github.com/jsreport/jsreport/files/9027785/GH-934-template.docx)

**Comment by pdecat** [comment]
Here's an even simpler reproduction test case:

```
1 {{#if true}}Title1
Some text
1.1 {{#if false}}Title1.1
Some text
1.1.1 {{#if true}}Title1.1.1
Some text
{{/if}}
{{/if}}
{{/if}}
```

```
# unzip -p GH-934.docx word/document.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:cx="http://schemas.microsoft.com/office/drawing/2014/chartex" xmlns:cx1="http://schemas.microsoft.com/office/drawing/2015/9/8/chartex" xmlns:cx2="http://schemas.microsoft.com/office/drawing/2015/10/21/chartex" xmlns:cx3="http://schemas.microsoft.com/office/drawing/2016/5/9/chartex" xmlns:cx4="http://schemas.microsoft.com/office/drawing/2016/5/10/chartex" xmlns:cx5="http://schemas.microsoft.com/office/drawing/2016/5/11/chartex" xmlns:cx6="http://schemas.microsoft.com/office/drawing/2016/5/12/chartex" xmlns:cx7="http://schemas.microsoft.com/office/drawing/2016/5/13/chartex" xmlns:cx8="http://schemas.microsoft.com/office/drawing/2016/5/14/chartex" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:aink="http://schemas.microsoft.com/office/drawing/2016/ink" xmlns:am3d="http://schemas.microsoft.com/office/drawing/2017/model3d" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:oel="http://schemas.microsoft.com/office/2019/extlst" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:w16cex="http://schemas.microsoft.com/office/word/2018/wordml/cex" xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns:w16="http://schemas.microsoft.com/office/word/2018/wordml" xmlns:w16sdtdh="http://schemas.microsoft.com/office/word/2020/wordml/sdtdatahash" xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 w15 w16se w16cid w16 w16cex w16sdtdh wp14"><w:body><w:p w14:paraId="55457E5A" w14:textId="3ECDBAC2" w:rsidR="00A6275F" w:rsidRDefault="00A6275F" w:rsidP="00A6275F"><w:pPr><w:pStyle w:val="Titre1"/></w:pPr><w:bookmarkStart w:id="1" w:name="_Toc37588284_r'"/><w:r><w:t>Title1</w:t></w:r><w:bookmarkEnd w:id="1"/></w:p><w:p w14:paraId="6D3E6C99" w14:textId="17756894" w:rsidR="00A6275F" w:rsidRPr="00A6275F" w:rsidRDefault="00A6275F" w:rsidP="00A6275F"><w:r><w:t>Some text</w:t></w:r></w:p><TOCTitle><w:p w14:paraId="1AF9A1AE" w14:textId="4765AE4C" w:rsidR="00A6275F" w:rsidRDefault="00A6275F" w:rsidP="00A6275F"><w:pPr><w:pStyle w:val="Titre2"/></w:pPr><w:bookmarkStart w:id="2" w:name="_Toc51411624_r'"/><w:r><w:t></w:t></w:r><!--__block_helper_container__--></w:p><w:p w14:paraId="4DD9FA35" w14:textId="6ABFA5B8" w:rsidR="00601C15" w:rsidRPr="00A6275F" w:rsidRDefault="00601C15" w:rsidP="00A6275F"/><w:sectPr w:rsidR="00601C15" w:rsidRPr="00A6275F"><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1417" w:right="1417" w:bottom="1417" w:left="1417" w:header="708" w:footer="708" w:gutter="0"/><w:cols w:space="708"/><w:docGrid w:linePitch="360"/></w:sectPr></w:body></w:document>
```

```
# unzip -p GH-934.docx word/document.xml | xmllint -
-:2: parser error : Opening and ending tag mismatch: TOCTitle line 2 and w:body
r="0"/><w:cols w:space="708"/><w:docGrid w:linePitch="360"/></w:sectPr></w:body>
                                                                               ^
-:2: parser error : Opening and ending tag mismatch: body line 2 and document
s w:space="708"/><w:docGrid w:linePitch="360"/></w:sectPr></w:body></w:document>
                                                                               ^
-:2: parser error : Premature end of data in tag document line 2
s w:space="708"/><w:docGrid w:linePitch="360"/></w:sectPr></w:body></w:document>
                                                                               ^

**Comment by bjrmatos** [comment]
FYI with both docx templates i don't see the xmllint issues, uses both files for report, render and inspected two outputs again the xmllint and they don't throw the same error than yours (there is no errors in the lint), in both cases there is no dangling TOCTitle tags

but i can see now how your case is more complex, i will take this into account and add new test, thanks

**Comment by bjrmatos** [comment]
I think I found a better approach now, please verify your reports against the last commit https://github.com/jsreport/jsreport/commit/2fb460ec9c156e206e2973e114ccd6e1bd175dce.  

of course, my implementation is not perfect also, I think it will fail if there is more than one close if tag on the same paragraph (like `{{/if}}{{/if}}`), however, it seems you don't this, so I skipped to handle that because it makes things more complex. 

this case is very special, so I prefer to handle this case by case If we find new scenarios which fail for you, also this process gets me the chance to know and understand what you do. 

so please try it again and let me know if it gets broken again for your complex report

**Comment by pdecat** [comment]
With commit 2fb460e, the rendering phase is failing:

```
rendering has finished with errors:
An error ocurred while trying to execute "render" command (3). A critical error occurred while trying to execute the render command (2). Error while executing docx recipe. Error when evaluating engine handlebars for template anonymous
docxChart helper requires data parameter to be set

(system-helpers.js line 622:11)

  620 |
  621 |   if (options.hash.data == null) {
> 622 |     throw new Error('docxChart helper requires data parameter to be set')
      |           ^
  623 |   }
  624 |
  625 |   if (!Array.isArray(options.hash.data.labels) || options.hash.data.labels.length === 0) {

 (1).
caused by error (3):
-> stack
Error:
    at startCLI (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-cli/lib/commander/startCommand.js:127:19)
    at async startCommand (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-cli/lib/commander/startCommand.js:67:5)
    at async startProcessing (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-cli/lib/commander/startProcessing.js:195:3)
caused by error (2):
-> stack
Error:
    at onCriticalError (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-cli/lib/commands/render.js:304:19)
    at exports.handler (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-cli/lib/commands/render.js:300:12)
    at async executeCommand (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-cli/lib/commander/executeCommand.js:22:20)
    at async Object.handler (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-cli/lib/commander/registerCommand.js:76:9)
    at async parseCLI (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-cli/lib/commander/startCommand.js:156:3)
    at async startCLI (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-cli/lib/commander/startCommand.js:121:20)
    at async startCommand (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-cli/lib/commander/startCommand.js:67:5)
    at async startProcessing (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-cli/lib/commander/startProcessing.js:195:3)
caused by error (1):
-> meta = {"lineNumber":622,"property":"helpers","weak":true,"logged":true,"previousOperationId":"bwdcdnh3k144h83"}
-> stack
Error: Error while executing docx recipe. Error when evaluating engine handlebars for template anonymous
docxChart helper requires data parameter to be set

(system-helpers.js line 622:11)

  620 |
  621 |   if (options.hash.data == null) {
> 622 |     throw new Error('docxChart helper requires data parameter to be set')
      |           ^
  623 |   }
  624 |
  625 |   if (!Array.isArray(options.hash.data.labels) || options.hash.data.labels.length === 0) {


    at module.exports (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-core/lib/shared/createError.js:10:13)
    at WorkerReporter.createError (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-core/lib/shared/reporter.js:47:12)
    at /home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-docx/lib/processDocx.js:93:20
    at async module.exports (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-docx/lib/recipe.js:38:28)
    at async invokeRender (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:95:5)
    at async WorkerReporter._render (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-core/lib/worker/render/render.js:147:7)
    at async /home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-core/lib/worker/reporter.js:179:19
    at async Domain.<anonymous> (/home/patrick/workspaces/myproject/node_modules/@jsreport/advanced-workers/lib/workerHandler.js:141:19)
caused by: Error: docxChart helper requires data parameter to be set
    at Object.docxChart (system-helpers.js:622:11)
    at Object.<anonymous> (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-core/lib/worker/render/executeEngine.js:301:27)
    at Object.wrapper (/home/patrick/workspaces/myproject/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at 28 (eval at compile (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-handlebars/lib/handlebarsEngine.js:34:30), <anonymous>:228:108)
    at Object.prog [as fn] (/home/patrick/workspaces/myproject/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
    at Object.<anonymous> (/home/patrick/workspaces/myproject/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:29:22)
    at Object.wrapper (/home/patrick/workspaces/myproject/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at 27 (eval at compile (/home/patrick/workspaces/myproject/node_modules/@jsreport/jsreport-handlebars/lib/handlebarsEngine.js:34:30), <anonymous>:185:47)
    at Object.prog [as fn] (/home/patrick/workspaces/myproject/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
    at Object.<anonymous> (/home/patrick/workspaces/myproject/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:29:22)
make: *** [Makefile:38: render] Error 1
```

We do also use `docxChart` helpers in our template.

I'll try to provide a reproduction test case.

**Comment by bjrmatos** [comment]
hmm strange, yes let me know if you can share a reproduction test, happy to continue improving the support for you.

**Comment by pdecat** [comment]
> happy to continue improving the support for you

Thanks again!

Alright, here's the reproduction test case, issue happens if the closing `{{/if}}` is on the same paragraph as the chart with `{{docxChart}}`:

![image](https://user-images.githubusercontent.com/318490/177284110-3964196e-21ec-47ec-b90b-273a58d027b1.png)


[GH-934-template-docxChart.docx](https://github.com/jsreport/jsreport/files/9044649/GH-934-template-docxChart.docx)

**Comment by pdecat** [comment]
The issue seems to be that with the latest version, the condition that is supposed to prevent rendering the graph if data is missing is no longer effective.

**Comment by bjrmatos** [comment]
thanks for the new case, will work on it

**Comment by bjrmatos** [comment]
please try again with the latest commit https://github.com/jsreport/jsreport/commit/02b04adba4a0a05220834941267f18413611d230

**Comment by bjrmatos** [comment]
thanks for confirmation @pdecat, we will include this in next release. thanks again for all the work and time your put into this.
