### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'equals')

### ISSUE THREAD

**Issue by norbornen** [jsreport/jsreport#959]
I'm use @jsreport/jsreport-postgres-store v3.0.0 as template storage.
I'm upgrated jsreport from v3.2 to current version v3.7.1.
After that not working profiling and similar services:

```
const jsreportConfig = {
  ...
  store: {
    provider: 'postgres',
  },
  extensions: {
    'postgres-store': {
      host: process.env.REPORT_DB_HOST || 'localhost',
      port: process.env.REPORT_DB_PORT || 5432,
      database: process.env.REPORT_DB_NAME,
      user: process.env.REPORT_DB_USERNAME,
      password: process.env.REPORT_DB_PASSWORD,
      ssl: false,
    },
  }
};
```

```
2022-09-09T18:57:29.965Z - error: Error when processing OData GET: /odata/profiles/$count?$filter=state%20eq%20%27success%27%20and%20timestamp%20gt%20datetimeoffset%272022-09-09T17:57:29.939Z%27 TypeError: Cannot read properties of undefined (reading 'equals')
    at module.exports (/usr/data/node_modules/@jsreport/odata-to-sql/lib/count.js:15:39)
    at Object.count (/usr/data/node_modules/@jsreport/odata-to-sql/lib/transformer.js:49:14)
    at Cursor.count (/usr/data/node_modules/@jsreport/sql-store/lib/sqlProvider.js:38:29)
    at replay (/usr/data/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:48:23)
    at /usr/data/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:58:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by pofider** [comment]
It's now fixed in the jsreport-postgres-store@3.1.0
I apologize for the problems.

**Comment by norbornen** [comment]
will I need to reinitialize the database?

**Comment by pofider** [comment]
No, it shouldn't be needed.
Its just a fix for a particular query used by the profiler.

**Comment by norbornen** [comment]
Thank you
