### ISSUE TITLE
Chrome-pdf timeout on windows

### ISSUE THREAD

**Issue by froschi123** [jsreport/jsreport#962]
Hi, i am using jsreport on windows 11. I have a fresh installation and only trying to run the samples. But non of them works. I get a timeout error:
Error when processing render request 11 Timeout Error: chrome pdf generation not completed after 58052ms Error: Timeout Error: chrome pdf generation not completed after 58052ms
    at Timeout._onTimeout (D:\001-Work\jsreportapp\node_modules\@jsreport\jsreport-chrome-pdf\lib\conversion.js:395:21)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7)

This is how the config looks like:
{
  "httpPort": 5488,
  "store": {
    "provider": "fs"
  },
  "blobStorage": {
    "provider": "fs"
  },
  "logger": {
    "console": {
      "transport": "console",
      "level": "debug"
    },
    "file": {
      "transport": "file",
      "level": "info",
      "filename": "logs/reporter.log"
    },
    "error": {
      "transport": "file",
      "level": "error",
      "filename": "logs/error.log"
    }
  },
  "trustUserCode": true,
  "reportTimeout": 60000,
  "workers": {
    "numberOfWorkers": 2
  },
  "extensions": {
    "authentication": {
      "cookieSession": {},
      "admin": {
        "username": "admin",
        "password": "password"
      },
      "enabled": false
    },
    "chrome-pdf": {
      "timeout": 30000,
      "launchOptions": {}
    },
    "sample-template": {
      "createSamples": true
    }
  }
}

Rendereing html or text works fine - tested it with a simple <h1>Hello world</h1>

I diabled all extentions in chrome so it should not interfere with any of them.

I tried the same on a linux environment as well, as well failing with the same error.

Any idea?
Bernd

**Comment by pofider** [comment]
Hmm, that is very strange.

If you try exactly the following in a new folder, on windows
```
npm i -g @jsreport/jsreport-cli
jsreport init
jsreport start
```
Can you open studio and render invoice sample?

**Comment by froschi123** [comment]
I did as you adviced,

Still the same problem. This is the output.

PS C:\temp> cd jsr
PS C:\temp\jsr> npm i -g @jsreport/jsreport-cli
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

changed 286 packages, and audited 287 packages in 15s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\temp\jsr> jsreport init
jsreport installation not found, installing jsreport the latest version now, wait a moment...
jsreport installation finished..
Creating server.js
Creating package.json
Creating default config jsreport.config.json
Initialized
PS C:\temp\jsr> jsreport start
2022-09-16T11:43:07.588Z - info: Initializing jsreport (version: 3.7.1, configuration file: jsreport.config.json, nodejs: 17.3.0)
2022-09-16T11:43:07.591Z - info: Searching for available extensions in C:\temp\jsr\
2022-09-16T11:43:07.595Z - info: Extensions location cache doesn't contain entry yet, crawling
2022-09-16T11:43:08.725Z - info: Found 35 extension(s)
2022-09-16T11:43:08.750Z - debug: Writing extension locations cache to C:\Users\beweR\AppData\Local\Temp\jsreport\core\locations.json
2022-09-16T11:43:08.752Z - debug: Discovered 35 extensions
2022-09-16T11:43:08.799Z - debug: Extension authentication@3.3.2 is disabled, skipping
2022-09-16T11:43:08.800Z - info: Using extension base@3.0.1
2022-09-16T11:43:08.806Z - info: Using extension child-templates@3.0.3
2022-09-16T11:43:08.810Z - info: Using extension cli@3.2.1
2022-09-16T11:43:08.811Z - info: Using extension components@3.2.1
2022-09-16T11:43:08.813Z - info: Using extension data@3.0.1
2022-09-16T11:43:08.814Z - info: Using extension express@3.4.2
2022-09-16T11:43:09.078Z - info: Using extension freeze@3.0.1
2022-09-16T11:43:09.080Z - info: Using extension fs-store@3.2.2
2022-09-16T11:43:09.168Z - info: Using extension handlebars@3.2.1
2022-09-16T11:43:09.170Z - info: Using extension import-export@3.1.3
2022-09-16T11:43:09.180Z - info: Using extension jsrender@3.0.0
2022-09-16T11:43:09.181Z - info: Using extension licensing@3.0.2
2022-09-16T11:43:09.204Z - info: Using extension localization@3.2.1
2022-09-16T11:43:09.205Z - info: Using extension npm@3.1.2
2022-09-16T11:43:09.211Z - info: Using extension pdf-utils@3.4.1
2022-09-16T11:43:09.213Z - info: Using extension reports@3.0.6
2022-09-16T11:43:09.215Z - info: Using extension tags@3.1.1
2022-09-16T11:43:09.217Z - info: Using extension text@3.0.0
2022-09-16T11:43:09.218Z - info: Using extension version-control@3.1.2
2022-09-16T11:43:09.232Z - info: Using extension assets@3.4.3
2022-09-16T11:43:09.244Z - info: Using extension authorization@3.2.2
2022-09-16T11:43:09.247Z - debug: Extension authorization@3.2.2 was disabled
2022-09-16T11:43:09.248Z - info: Using extension browser-client@3.1.1
2022-09-16T11:43:09.250Z - info: Using extension chrome-pdf@3.2.0
2022-09-16T11:43:09.252Z - debug: Chrome strategy is chrome-pool, numberOfWorkers: 1
2022-09-16T11:43:09.253Z - info: Using extension docx@3.4.0
2022-09-16T11:43:09.255Z - info: Using extension html-to-xlsx@3.2.3
2022-09-16T11:43:09.312Z - info: html-to-xlsx detected chrome as available html engine
2022-09-16T11:43:09.313Z - info: Using extension pptx@3.2.1
2022-09-16T11:43:09.315Z - info: Using extension scheduling@3.0.3
2022-09-16T11:43:09.352Z - info: Using extension scripts@3.2.1
2022-09-16T11:43:09.353Z - info: Using extension static-pdf@3.0.0
2022-09-16T11:43:09.354Z - info: Using extension studio@3.7.0
2022-09-16T11:43:09.426Z - info: Using extension xlsx@3.2.2
2022-09-16T11:43:09.450Z - info: Using extension public-templates@3.0.0
2022-09-16T11:43:09.452Z - debug: Extension public-templates@3.0.0 was disabled
2022-09-16T11:43:09.452Z - info: Using extension sample-template@3.2.1
2022-09-16T11:43:09.454Z - info: Using extension studio-theme-dark@3.0.1
2022-09-16T11:43:09.455Z - info: Using general timeout for rendering (reportTimeout: 60000)
2022-09-16T11:43:09.456Z - info: Using fs provider for template store.
2022-09-16T11:43:09.461Z - info: fs store is persisting using fs for C:\temp\jsr\data
2022-09-16T11:43:09.466Z - info: fs store is loading data
2022-09-16T11:43:09.473Z - info: fs store is initialized successfully
2022-09-16T11:43:09.482Z - debug: studio default theme is: light
2022-09-16T11:43:09.528Z - info: Creating default express app.
2022-09-16T11:43:09.547Z - info: jsreport server successfully started on http port: 5488
2022-09-16T11:43:09.549Z - info: Verifying license key free
2022-09-16T11:43:09.549Z - info: Using free license
2022-09-16T11:43:09.563Z - info: Migrating templates chrome settings (waitForNetworkIddle -> waitForNetworkIdle)
2022-09-16T11:43:09.568Z - info: Migration successful
2022-09-16T11:43:09.569Z - debug: Inserting samples
2022-09-16T11:43:09.575Z - debug: Creating folder "samples" for sample entities
2022-09-16T11:43:09.583Z - debug: Inserting sample entity Invoice (entitySet: folders)
2022-09-16T11:43:09.589Z - debug: Inserting sample entity Orders (entitySet: folders)
2022-09-16T11:43:09.595Z - debug: Inserting sample entity Sales (entitySet: folders)
2022-09-16T11:43:09.600Z - debug: Inserting sample entity shared (entitySet: folders)
2022-09-16T11:43:09.606Z - debug: Inserting sample entity invoice-data (entitySet: data)
2022-09-16T11:43:09.614Z - debug: Inserting sample entity sales-data (entitySet: data)
2022-09-16T11:43:09.621Z - debug: Inserting sample entity sales-main (entitySet: templates)
2022-09-16T11:43:09.638Z - debug: Inserting sample entity invoice-main (entitySet: templates)
2022-09-16T11:43:09.644Z - debug: Inserting sample entity orders-main (entitySet: templates)
2022-09-16T11:43:09.651Z - debug: Inserting sample entity orders-header (entitySet: templates)
2022-09-16T11:43:09.658Z - debug: Inserting sample entity invoice-styles.css (entitySet: assets)
2022-09-16T11:43:09.667Z - debug: Inserting sample entity orders-styles.css (entitySet: assets)
2022-09-16T11:43:09.673Z - debug: Inserting sample entity sales-styles.css (entitySet: assets)
2022-09-16T11:43:09.679Z - debug: Inserting sample entity invoice-logo.png (entitySet: assets)
2022-09-16T11:43:09.685Z - debug: Inserting sample entity global helpers.js (entitySet: assets)
2022-09-16T11:43:09.690Z - debug: Inserting sample entity orders-script (entitySet: scripts)
2022-09-16T11:43:09.699Z - info: Initializing worker threads
2022-09-16T11:43:09.699Z - debug: Extensions in workers: base, child-templates, components, data, express, handlebars, jsrender, localization, npm, pdf-utils, reports, text, version-control, assets, browser-client, chrome-pdf, docx, html-to-xlsx, pptx, scripts, static-pdf, studio, xlsx
2022-09-16T11:43:09.948Z - info: 2 worker threads initialized in 249ms
2022-09-16T11:43:09.949Z - info: Starting temp files cleanup with 180000ms threshold
2022-09-16T11:43:09.949Z - info: reporter initialized
2022-09-16T11:43:31.939Z - debug: OData query on templates
2022-09-16T11:43:31.944Z - debug: OData query on folders
2022-09-16T11:43:31.948Z - debug: OData query on components
2022-09-16T11:43:31.951Z - debug: OData query on data
2022-09-16T11:43:31.954Z - debug: OData query on tags
2022-09-16T11:43:31.956Z - debug: OData query on assets
2022-09-16T11:43:31.960Z - debug: OData query on scripts
2022-09-16T11:43:31.962Z - debug: OData query on schedules
2022-09-16T11:43:31.970Z - debug: OData query on settings
2022-09-16T11:43:32.082Z - debug: OData query on templates
2022-09-16T11:43:32.100Z - debug: OData query on profiles
2022-09-16T11:43:32.125Z - debug: OData query on profiles
2022-09-16T11:43:32.135Z - debug: OData query on profiles
2022-09-16T11:43:32.141Z - debug: OData query on profiles
2022-09-16T11:43:32.147Z - debug: OData query on profiles
2022-09-16T11:43:32.154Z - debug: OData query on profiles
2022-09-16T11:43:32.159Z - debug: OData query on templates
2022-09-16T11:43:37.050Z - debug: OData query on data
2022-09-16T11:43:43.163Z - debug: OData query on templates
2022-09-16T11:43:44.626Z - info: Render request 1 queued for execution and waiting for available worker rootId=u1it2ou104espkw, id=u1it2ou104espkw
2022-09-16T11:43:44.716Z - info: Starting rendering request 1 (user: null) rootId=u1it2ou104espkw, id=u1it2ou104espkw
2022-09-16T11:43:44.718Z - info: Rendering template { name: invoice-main, recipe: chrome-pdf, engine: handlebars, preview: true } rootId=u1it2ou104espkw, id=u1it2ou104espkw
2022-09-16T11:43:44.719Z - debug: Inline data specified. rootId=u1it2ou104espkw, id=u1it2ou104espkw
2022-09-16T11:43:44.860Z - debug: Base url not specified, skipping its injection. rootId=u1it2ou104espkw, id=u1it2ou104espkw
2022-09-16T11:43:44.861Z - debug: Rendering engine handlebars rootId=u1it2ou104espkw, id=u1it2ou104espkw
2022-09-16T11:43:45.484Z - debug: Calculating item Website design; you should see this message in debug run userLevel=true, rootId=u1it2ou104espkw, id=u1it2ou104espkw
2022-09-16T11:43:45.587Z - debug: Executing recipe chrome-pdf rootId=u1it2ou104espkw, id=u1it2ou104espkw
2022-09-16T11:43:46.550Z - debug: Converting with chrome HeadlessChrome/98.0.4758.0 using chrome-pool strategy rootId=u1it2ou104espkw, id=u1it2ou104espkw
2022-09-16T11:44:45.517Z - error: Error when processing render request 1 Timeout Error: chrome pdf generation not completed after 59023ms Error: Timeout Error: chrome pdf generation not completed after 59023ms
    at Timeout._onTimeout (C:\temp\jsr\node_modules\@jsreport\jsreport-chrome-pdf\lib\conversion.js:395:21)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7) rootId=u1it2ou104espkw, id=u1it2ou104espkw
2022-09-16T11:44:45.518Z - error: Rendering request 1 finished with error in 60903 ms rootId=u1it2ou104espkw, id=u1it2ou104espkw

**Comment by pofider** [comment]
Strange. Is there something specific about your system?
Can you pause the antivirus? Do you run with a local admin user?
Can you try to add the following to the config `"tempDirectory": "c:/temp"`
Try using nodejs 16 which is LTS instead.
Are you able to start "node_modules\puppeteer\.local-chromium\win64-950341\chrome-win\chrome.exe" ?

**Comment by froschi123** [comment]
_Can you pause the antivirus_ - done, still mot working
_Do you run with a local admin user_ - Yes
_Can you try to add the following to the config "tempDirectory": "c:/temp"_ - done, still not working

_Are you able to start "node_modules\puppeteer.local-chromium\win64-950341\chrome-win\chrome.exe" ?_
No, i can not even find any folder puppeteer in my path.  npm is installed at C:\Users\myuser\AppData\Roaming\npm but there is no puppeteer folder. Maybe i got u wrong?

_Try using nodejs 16 which is LTS instead._ - I dont know how to do that. I am running 17.3.0 and dont want to downgrade, as i am using node in different projects.

**Comment by pofider** [comment]
> Are you able to start "node_modules\puppeteer.local-chromium\win64-950341\chrome-win\chrome.exe" ?
No, i can not even find any folder puppeteer in my path. npm is installed at C:\Users\myuser\AppData\Roaming\npm but there is no puppeteer folder. Maybe i got u wrong?

It should be at the directory where is your app... 
`C:\temp\jsr\node_modules...`

> Try using nodejs 16 which is LTS instead. - I dont know how to do that. I am running 17.3.0 and dont want to downgrade, as i am using node in different projects.

I've tested the nodejs 17 and it works fine, so its likely not that problem. But you can still downgrade to node 16, test it and install node 17 back then.

**Comment by HugoAVRIL** [comment]
Hi, similar problem for me, any update ?

**Comment by froschi123** [comment]
Sorry, i did not investigate further as i have an Linux Server and moved from windows to linux. 
But i couldnt solve the problem. Maybe we find a solution if you have the same problem, so maybe it is not only because of my setup.

**Comment by pofider** [comment]
I do all work on windows, so chrome needs to work.
We shipped yesterday jsreport 3.8.0, which uses updated Chrome 102, there is some chance that it could help. Could you try it?

**Comment by HugoAVRIL** [comment]
Updated, I can't say the problem persists since the new version but it seems like a different one, and I think it concern puppeteer, I'll check on this side.

**Comment by pofider** [comment]
I'm closing this because it's quite old.
Don't hesitate to open a new issue or comment if you still have problems.
