### ISSUE TITLE
Upgraded from 0.5.0 to 0.8.2, but phantom-pdf recipe is no longer working

### ISSUE THREAD

**Issue by zheffie** [jsreport/jsreport#99]
I executed following command in my jsreport folder (ubuntu): ```npm update jsreport```
Now rending phantom-pdf is no longer possible. It throws the following exception

```
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (child_process.js:1136:26)
    at exports.spawn (child_process.js:995:9)
    at Object.exports.execFile (child_process.js:689:15)
    at /opt/tnt-node/tnt-jsreport/node_modules/jsreport/node_modules/toner-phantom/node_modules/phantom-html-to-pdf/node_modules/phantom-workers/lib/phantomWorker.js:68:43
    at Server.<anonymous> (/opt/tnt-node/tnt-jsreport/node_modules/jsreport/node_modules/toner-phantom/node_modules/phantom-html-to-pdf/node_modules/phantom-workers/lib/phantomWorker.js:18:9)
    at Server.emit (events.js:104:17)
    at net.js:1419:10
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by pofider** [comment]
I tried to reproduce this with installing 0.5.0 on ubuntu and then updating using `npm update jsreport` but the upgrade was successful in my case .

It looks the phantomjs was not downoladed/initialized correctly for you.

Maybe you tried to update with jsreport running on the background?

To fix this you can try to type `npm install toner-phantom` or delete jsreport from node_modules and type complete installation `npm install jsreport`

**Comment by zheffie** [comment]
deleting the folder and reinstalling jsreport fixed it.

Thanks
